Scripts/Gumps/Props/PropsGump.cs
Scripts/Misc/VendorGenerator.cs
Scripts/Regions/HouseRegion.cs

Note: Due to a sync error with Github, I had to revert the previous PR #9. This PR includes that code too.

Fixes bug with props gump

---

Scripts/Gumps/Props/PropsGump.cs
Scripts/Items/Food/Beverage.cs
Scripts/Misc/VendorGenerator.cs
Scripts/Mobiles/PlayerMobile.cs
Scripts/Regions/HouseRegion.cs
Server/Mobile.cs
Server/Region.cs
Server/packages.config

Merges crash bugs into master.
Still don't have a good way to automatically download/apply Roslyn for windows.

Merges crash bugs into master

---

Scripts/Engines/RemoteAdmin/Network.cs
Server/NativeReader.cs
Server/Persistence/FileOperations.cs
Server/Persistence/SaveMetrics.cs
Server/TileMatrix.cs
Server/TileMatrixPatch.cs

Addresses mono builds from #11.

Fixes mono builds in #11

---

Scripts/Accounting/Account.cs
Scripts/Commands/Docs.cs
Scripts/Engines/ConPVP/Arena.cs
Scripts/Engines/ConPVP/Games/BombingRun.cs
Scripts/Engines/ConPVP/Games/KingOfTheHill.cs
Scripts/Engines/ConPVP/Ladder.cs
Scripts/Engines/Factions/Core/Faction.cs
Scripts/Engines/Factions/Core/PlayerState.cs
Scripts/Engines/Factions/Core/Town.cs
Scripts/Engines/Reports/Objects/Staffing/Info.cs
Scripts/Engines/Reports/Reports.cs
Scripts/Gumps/SkillsGump.cs
Scripts/Mobiles/BaseCreature.cs
Server/ClientVersion.cs
Server/Commands.cs
Server/Geometry.cs
Server/IEntity.cs
Server/Insensitive.cs
Server/Item.cs
Server/Items/Container.cs
Server/Map.cs
Server/Mobile.cs
Server/Serial.cs

Removes old comparable/comparers.

---

Projects/Server/Random.cs

Fixes bug with copying bytes in Software Random.

Fixes Software Random

---

Contributing.md
LICENSE
README.md
THIRD-PARTY-NOTICES

Adds contributions, notices, etc.

Contributions & Notices

---

.gitignore
Projects/Scripts/Scripts.csproj
Projects/Server/Server.csproj

Fixes dependencies & copying modules

Fixes dependencies & copying modules

---

Projects/Scripts/Commands/SignParser.cs

Sign parser fix

---

Projects/Scripts/Commands/Add.cs
Projects/Scripts/Commands/Decorate.cs
Projects/Scripts/Commands/DecorateMag.cs
Projects/Scripts/Commands/GenCategorization.cs
Projects/Scripts/Commands/Generic/Commands/Commands.cs
Projects/Scripts/Commands/Generic/Implementors/ObjectConditional.cs
Projects/Scripts/Commands/Profiling.cs
Projects/Scripts/Commands/Properties.cs
Projects/Scripts/Engines/BulkOrders/Books/BOBLargeSubEntry.cs
Projects/Scripts/Engines/BulkOrders/Books/BOBSmallEntry.cs
Projects/Scripts/Engines/BulkOrders/LargeBulkEntry.cs
Projects/Scripts/Engines/BulkOrders/SmallBOD.cs
Projects/Scripts/Engines/BulkOrders/SmallBulkEntry.cs
Projects/Scripts/Engines/Doom/GauntletSpawner.cs
Projects/Scripts/Engines/Factions/Core/Reflector.cs
Projects/Scripts/Engines/MLQuests/Items/Teleporters.cs
Projects/Scripts/Engines/MLQuests/MLQuestSystem.cs
Projects/Scripts/Engines/Quests/Core/QuestSerializer.cs
Projects/Scripts/Engines/Spawner/SpawnerType.cs
Projects/Scripts/Gumps/AddGump.cs
Projects/Scripts/Gumps/CategorizedAddGump.cs
Projects/Scripts/Items/Talismans/TalismanAttribute.cs
Projects/Scripts/Spells/Base/SpellRegistry.cs
Projects/Server/AssemblyHandler.cs
Projects/Server/Region.cs
Projects/Server/World.cs

Rebuilt TypeCache in a way that is running almost 10x faster and is more accurate when finding types.
Primary update -> Projects/Server/AssemblyHandler.cs
The rest are just updating the function calls.

Fixes TypeCache lookup speed and errors

---

Projects/Scripts/Engines/Factions/Items/Traps/FactionExplosionTrap.cs
Projects/Scripts/Engines/Factions/Items/Traps/FactionGasTrap.cs
Projects/Scripts/Engines/Factions/Items/Traps/FactionSawTrap.cs
Projects/Scripts/Engines/Factions/Items/Traps/FactionSpikeTrap.cs
Projects/Scripts/Engines/Factions/Mobiles/FactionWarHorse.cs
Projects/Scripts/Engines/Khaldun/RaiseSwitch.cs
Projects/Scripts/Holiday Stuff/Halloween/Treats/Jellybeans.cs
Projects/Scripts/Holiday Stuff/Halloween/Treats/Taffy.cs
Projects/Scripts/Holiday Stuff/Halloween/Treats/WrappedCandy.cs
Projects/Scripts/Items/Addons/ArcheryButteAddon.cs
Projects/Scripts/Items/Deeds/CommodityDeed.cs
Projects/Scripts/Items/Guilds/GuildTeleporter.cs
Projects/Scripts/Items/Guilds/Guildstone.cs
Projects/Scripts/Items/Skill Items/Fishing/Misc/MessageInABottle.cs
Projects/Scripts/Items/Skill Items/Magical/Spellbook.cs
Projects/Scripts/Items/Skill Items/Misc/RepairDeed.cs
Projects/Scripts/Items/Skill Items/Tinkering/Clocks.cs
Projects/Scripts/Items/Special/House Raffle/HouseRaffleDeed.cs
Projects/Scripts/Mobiles/Guards/ArcherGuard.cs
Projects/Scripts/Mobiles/Guards/WarriorGuard.cs
Projects/Scripts/Mobiles/Monsters/Misc/Melee/PlagueSpawn.cs
Projects/Scripts/Mobiles/Special/HarrowerTentacles.cs

There is a bunch of types missing 'ConstructibleAttribute' that had 'ConstructableAttribute' in RunUO

Add ConstructibleAttribute to types missing it that had it in RunUO

---

Projects/Scripts/Items/Misc/MorphItem.cs

Fixes InRange error with MorphItem

Fixes InRange error

---

Projects/Scripts/Commands/LocationCommand.cs

Updates location command

---

Projects/Server/Gumps/GumpSpriteImage.cs

Adds Gump Sprite Images (picinpic)

Adds Gump Sprite Images (picinpic)

---

.circleci/config.yml

Updates CircleCI to test builds/linting/

Adds analyzers to Circle CI

---

README.md

Fixes links in README.md

---

Projects/Scripts.Tests/Accounting/PBKDF2PasswordProtectionTest.cs
Projects/Scripts.Tests/Misc/HexStringConverterTest.cs
Projects/Scripts.Tests/Scripts.Tests.csproj
Projects/Scripts/Accounting/Account.cs
Projects/Scripts/Accounting/AccountHandler.cs
Projects/Scripts/Accounting/AccountSecurity.cs
Projects/Scripts/Accounting/IPasswordProtection.cs
Projects/Scripts/Accounting/PBKDF2PasswordProtection.cs
Projects/Scripts/Misc/HexStringConverter.cs

Adds PBKDF2 protection for account passwords.

---

Projects/Scripts/Accounting/Account.cs
Projects/Scripts/Accounting/AccountAttackLimiter.cs
Projects/Scripts/Accounting/AccountHandler.cs
Projects/Scripts/Accounting/IPLimiter.cs
Projects/Scripts/Accounting/Security/AccountSecurity.cs
Projects/Scripts/Configuration/ExpansionConfiguration.cs
Projects/Scripts/Engines/Ethics/Core/Ethic.cs
Projects/Scripts/Engines/Pathing/PathFollower.cs
Projects/Scripts/Engines/VeteranRewards/RewardSystem.cs
Projects/Scripts/Misc/BuffIcons.cs
Projects/Scripts/Misc/ClientVerification.cs
Projects/Scripts/SpecialSystems/Engines/TestCenter.cs

Fixes configurations.
Closes #127

Fixes configurations.

---

Projects/Scripts/Misc/MapDefinitions.cs
Projects/Scripts/Misc/ServerList.cs
Projects/Server.Tests/Network/Packets/DamageOldPacketTests.cs
Projects/Server.Tests/ServerFixture.cs
Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Main.cs
Projects/Server/Map.cs
Projects/Server/Mobile.cs
Projects/Server/Network/PacketHandlers.cs
Projects/Server/Network/Packets.cs

Fixes configurations

---

Projects/Argon2/Argon2.cs
Projects/Argon2/Argon2.csproj
Projects/Argon2/Argon2.nuspec
Projects/Argon2/Argon2Error.cs
Projects/Argon2/Argon2Exception.cs
Projects/Argon2/Argon2PasswordHasher.cs
Projects/Argon2/HashMetadata.cs
Projects/Server/Utilities/RandomProviders.cs
Projects/UOContent/Accounting/Security/Argon2PasswordProtection.cs

Cleans up Argon2

---

Projects/UOContent/Engines/BulkOrders/Books/BOBGump.cs
Projects/UOContent/Engines/Harvest/Core/HarvestDefinition.cs
Projects/UOContent/Gumps/ViewHousesGump.cs

Updates to text definitions

---

Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Main.cs
Projects/Server/MultiData.cs
Projects/Server/Network/Packets.cs
Projects/Server/TileData.cs
Projects/Server/TileMatrix.cs
Projects/Server/TileMatrixPatch.cs
Projects/UOContent/Commands/Docs.cs
Projects/UOContent/Engines/MLQuests/Objectives/CollectObjective.cs
Projects/UOContent/Misc/ClientVerification.cs

Fixes data file loading

---

Projects/Server/Server.csproj

Release 0.4.0

---

Projects/UOContent/Items/Skill Items/Musical Instruments/BaseInstrument.cs

Fixes NPE in GetPoisonLevel

---

.github/workflows/dotnet-core.yml
Projects/Argon2/Argon2.csproj
Projects/Server.Tests/packages.lock.json
Projects/Server/packages.lock.json
Projects/UOContent.Tests/packages.lock.json
Projects/UOContent/UOContent.csproj
Projects/UOContent/packages.lock.json
Tools/publish.cmd

Fixes a missing reference to libargon2.dylib.
Not sure how it happened unfortunately, but it did.

Fixes argon2 for osx

---

.github/workflows/dotnet-core.yml
README.md
azure-pipelines.yml

Set up CI with Azure Pipelines

---

Projects/Server.Tests/Network/Packets/GumpUtilities.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/AccountPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/EffectPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/EquipmentPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/GumpPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ItemPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MenuPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/SecureTradePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/VendorBuyPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/VendorSellPacketTests.cs
Projects/Server.Tests/Network/Packets/PacketTestUtilities.cs
Projects/Server.Tests/Server.Tests.csproj
Projects/Server.Tests/packages.lock.json
Projects/Server/Gumps/Gump.cs
Projects/Server/Items/Container.cs
Projects/Server/Main.cs
Projects/Server/Network/Packets/Old Packets/GumpPackets.cs
Projects/Server/Network/Packets/Old Packets/ItemPackets.cs
Projects/Server/TileData.cs
Projects/UOContent.Tests/UOContent.Tests.csproj
Projects/UOContent.Tests/packages.lock.json
Projects/UOContent/Items/Skill Items/Magical/Spellbook.cs

Adds more packet tests to help convert packet code to use stackalloc

Adds more packet tests

---

Projects/Server.Tests/Network/Packets/Old/Outgoing/AccountPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/EffectPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ItemPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MessageTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ObjectHelpResponseTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/PlayerPacketTests.cs
Projects/Server.Tests/Network/Packets/PacketTestUtilities.cs
Projects/Server/Buffers/SpanExtensions.cs
Projects/Server/Mobile.cs
Projects/Server/Network/Packets/Old Packets/PlayerPackets.cs
Projects/Server/Network/StaticPacketHandlers.cs
Projects/UOContent/Misc/Paperdoll.cs
Projects/UOContent/Misc/Profile.cs
azure-pipelines.yml

Adds more packets

---

Projects/UOContent/Misc/Profile.cs
Projects/UOContent/Spells/Fifth/MagicReflect.cs
Projects/UOContent/Spells/First/ReactiveArmor.cs
Projects/UOContent/Spells/Second/Protection.cs

Fixes NPE with Protection Spell

---

Projects/Server/Network/MessagePumpService.cs
Projects/Server/Network/PacketHandlers.cs

Fixes the vendor packets and batch query packet.
Closes #182 
Closes #183

Fixes getting packet length for receiving packets

---

Projects/UOContent/Mobiles/PlayerMobile.cs

Fixes a crash related to the unequip macro.

Fixes the bug with unequip macro

---

Projects/UOContent/Engines/Pathing/Movement.cs

Should hopefully address z-level issues with movement.
Closes #191

Should fix movement

---

.github/workflows/create-release.yml

Adds in all operating systems as a matrix for Release

Adds all OS for Release

---

.github/workflows/create-release.yml

Fixes actual operating system used for building Release

Fixes actual operating system used for building Release

---

Projects/UOContent/Gumps/Go/GoGump.cs

Fixes bug where categories/locations in the same go gump entry was crashing.
Thanks nkr!

Fixes GoGump NPE

---

.github/workflows/create-release.yml
version.json

Release Version 0.6.3

---

Projects/Server/Configuration/ServerConfiguration.cs
Projects/UOContent/Configuration/EmailConfiguration.cs
Projects/UOContent/Misc/ServerList.cs

Fixes email configurations

---

Projects/Server/JsonConfiguration/Converters/Rectangle3DConverter.cs
Projects/Server/Mobile.cs
Projects/Server/Sector.cs
Projects/UOContent/Mobiles/Townfolk/Messenger.cs

Fixes regions with implicit z level.
Bumps the release.

Fixes regions implicit z level

---

Projects/UOContent/Items/Weapons/Abilities/WeaponAbility.cs
Projects/UOContent/Spells/Base/SpellRegistry.cs

Fixes NPE from Weapon Ability & Updates [cast

---

Directory.Build.props
Distribution/Configuration/email-settings.json
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj

While using Visual Studio, build using F6, then use F5 for debugging.

Fixes building with VS2019

---

Directory.Build.props
Projects/Server.Tests/Network/Packets/Old/Outgoing/AttributeNormalizerTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/SequentialTestCollectionDefinition.cs

Fixes leaking tests with AttributeNormalizer

---

Projects/UOContent/Misc/AccountPrompt.cs

when Console.IsInputRedirected is true for shells like git bash

Add workaround for Console.ReadKey

---

Projects/Server.Tests/Network/Packets/Old/Outgoing/EffectPacketTests.cs
Projects/Server/AssemblyHandler.cs
Projects/Server/Main.cs
Projects/Server/Network/MessagePumpService.cs
Projects/Server/Network/NetState.cs
Projects/Server/Network/TcpServer.cs
Projects/UOContent/Misc/AutoRestart.cs
Projects/UOContent/Misc/Broadcasts.cs
Projects/UOContent/Misc/CrashGuard.cs

TODO: Create a mode where restarting won't actually restart to support linux daemons.

Fixes exiting/crash handling/ctrl+c

---

docs/CNAME

Adds CNAME to docs

---

docs/building-server.md
docs/index.md
docs/installation.md
docs/quick-start.md
mkdocs.yml

Created a quick start for the docs.

Creates quick start for docs

---

Projects/UOContent/Items/Addons/BaseAddon.cs

Fixes NPE with CouldFit

---

Projects/UOContent/Misc/BuffIcons.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

Fixes BuffIcon NPE

---

.gitattributes

Fixes more potential line ending issues.

Fixes line endings for md/rules

---

Projects/Server/Mobiles/Mobile.cs

Fixes a bug with mobile lifting requests.

Updates Mobile Lift

---

Projects/Server.Tests/Utility/TestStringHelpers.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Commands/Logging.cs
Projects/UOContent/Engines/Chat/Channel.cs
Projects/UOContent/Engines/Chat/ChatActionHandlers.cs
Projects/UOContent/Engines/ConPVP/Games/KingOfTheHill.cs
Projects/UOContent/Gumps/BanDurationGump.cs
Projects/UOContent/Gumps/Guilds/GuildGump.cs
Projects/UOContent/Gumps/Guilds/New Guild System/GuildInfoGump.cs
Projects/UOContent/Gumps/HouseGumpAOS.cs
Projects/UOContent/Gumps/WhoGump.cs
Projects/UOContent/Items/Misc/PlayerBulletinBoards.cs
Projects/UOContent/Items/Skill Items/Magical/Misc/RecallRune.cs
Projects/UOContent/Items/Skill Items/Magical/Runebook.cs
Projects/UOContent/Items/Special/Solen Items/BallOfSummoning.cs
Projects/UOContent/Items/Special/Solen Items/BraceletOfBinding.cs
Projects/UOContent/Mobiles/Vendors/PlayerVendor.cs
Projects/UOContent/Multis/Boats/BaseBoat.cs

Updates IsNullOrDefault so the function takes a null receiver instead of never being executed due to null accessor short circuit.

Fixes IsNullOrDefault

---

Projects/Server.Tests/Network/Packets/AttributeNormalizerUtilities.cs
Projects/Server.Tests/Network/Packets/GumpUtilities.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/AccountPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ArrowPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/AttributeNormalizerTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/CombatPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/DamagePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/DisplayHuePickerTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/EffectPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/EquipmentPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/GumpPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ItemPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/LightPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MapPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MenuPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MessageTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/MovementPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/ObjectHelpResponseTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/PlayerPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/SecureTradePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/TargetPacketsTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/UnicodePromptTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/VendorBuyPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/VendorSellPacketTests.cs
Projects/Server.Tests/Network/Packets/PacketTestUtilities.cs

Resolves a conflict due to Class/Namespace collision. No functional change.

Changes packet test namespaces

---

Projects/Server/Buffers/CircularBuffer.cs
Projects/Server/Buffers/SpanReader.cs
Projects/Server/Buffers/SpanWriter.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/NetworkCompression.cs
Projects/Server/Network/Packet.cs

Changes Huffman to in-place & Adds CircularBuffer

---

Projects/Server.Tests/Network/PipeTests.cs
Projects/Server/Buffers/CircularBuffer.cs
Projects/Server/Buffers/CircularBufferReader.cs
Projects/Server/Buffers/CircularBufferWriter.cs
Projects/Server/Items/Item.cs
Projects/Server/Main.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/NetworkCompression.cs
Projects/Server/Network/Packet.cs
Projects/Server/Network/PacketHandlers.cs
Projects/Server/Network/PacketUtilities.cs
Projects/Server/Network/Pipe.cs
Projects/Server/Timer/Timer.cs

Updates pipe eliminate result and segments from being allocated.

Updates Pipe & Makes NetState more testable

---

Projects/Server.Tests/Network/PipeTests.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/Pipe.cs

Cleans up API

---

Projects/Server/Comparers/LocationComparer.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Mobiles/MovementRecord.cs
Projects/Server/Mobiles/SimplePrompt.cs
Projects/Server/Mobiles/SimpleTarget.cs
Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

Splits up Mobile file

---

Projects/Server/Guild.cs
Projects/Server/IEntity.cs
Projects/Server/Items/Item.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Serialization/BinaryFileReader.cs
Projects/Server/Serialization/BinaryFileWriter.cs
Projects/Server/Serialization/BufferWriter.cs
Projects/Server/Serialization/IGenericReader.cs
Projects/Server/Serialization/ISerializable.cs
Projects/Server/World/World.cs
Projects/UOContent/Commands/Handlers.cs
Projects/UOContent/Misc/AutoSave.cs

- In a future optimization I will copy the entire object to a buffer, deserialize using a SpanReader, then use that buffer for the SaveBuffer

Optimizes & fixes bugs in world saves

---

Projects/Server.Tests/Network/Packets/Old/Outgoing/CombatPacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/CombatPackets.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/DamagePacketTests.cs
Projects/Server.Tests/Network/Packets/Old/Outgoing/DamagePackets.cs
Projects/Server.Tests/Utility/EncodingHelpers.cs
Projects/Server/Guild.cs
Projects/Server/IEntity.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingDamagePackets.cs
Projects/UOContent.Tests/Misc/HexStringConverterTest.cs
Projects/UOContent/Accounting/Security/MD5PasswordProtection.cs
Projects/UOContent/Accounting/Security/PBKDF2PasswordProtection.cs
Projects/UOContent/Accounting/Security/SHA1PasswordProtection.cs
Projects/UOContent/Accounting/Security/SHA2PasswordProtection.cs
Projects/UOContent/Engines/Chat/ChatActionHandlers.cs
Projects/UOContent/Engines/Chat/ChatUser.cs
Projects/UOContent/Misc/Fastwalk.cs
Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

Changes damage packets

---

azure-pipelines.yml
publish.cmd

Adds CentOS 7/8 to the build process.
Docker Image: [centos-net5:8](https://hub.docker.com/repository/docker/modernuo/centos-net5)

Adds CentOS to the CI/CD

---

publish.cmd

Fixes publishing

---

Projects/Server/Network/NetState/NetState.ClientVersion.cs

Fixes NPE with a client that doesn't support expansions.
Thanks Icculus!

Fixes NPE with expansions

---

Projects/Server/Network/NetState/NetState.ClientVersion.cs

Fixes another NPE with expansion info

Fixes another NPE with Expansion checks

---

Projects/Server/World/World.cs
Projects/UOContent/Items/Armor/BaseArmor.cs

Fixes an NPE because items should be loaded after mobiles.

Fixes NPE for Items during World Load

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/EffectPackets.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/EquipmentPackets.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/LightPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/LightPackets.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Network/Packets/OutgoingLightPackets.cs
Projects/Server/Serialization/BufferReader.cs
Projects/Server/World/World.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

Updates Light Packets & World Loading

---

.github/workflows/build-test.yml
Directory.Build.props
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
version.json

Fixes NBGV & Adds Big Sur to CI/CD

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MapPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MapPackets.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/IncomingAccountPackets.cs
Projects/Server/Network/Packets/OutgoingLightPackets.cs
Projects/Server/Network/Packets/OutgoingMapPackets.cs

Updates map packets

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MenuPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MenuPackets.cs
Projects/Server/Menus/ItemListMenu.cs
Projects/Server/Menus/QuestionMenu.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingMenuPackets.cs

Updates menu packets

---

publish.cmd

Fixes the argument in publish.cmd

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/SecureTradePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/SecureTradePackets.cs
Projects/Server/Network/Packets/OutgoingSecureTradePackets.cs
Projects/Server/SecureTrade.cs

Converts secure trade packets

---

Projects/Server.Tests/Helpers/AssertExtensions.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/EquipmentPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/ItemPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/LightPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MenuPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MessageTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/SecureTradePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/TargetPackets.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/TargetPacketsTests.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/Network/Packets/OutgoingTargetPackets.cs
Projects/Server/Targeting/MultiTarget.cs
Projects/Server/Targeting/Target.cs
Projects/Server/World/World.cs
Projects/UOContent/Engines/ConPVP/Gumps/TournamentBracketGump.cs
Projects/UOContent/Items/Misc/Corpses/Corpse.cs
Projects/UOContent/Spells/Mysticism/HailStormSpell.cs
Projects/UOContent/Spells/Mysticism/NetherCycloneSpell.cs

```cs
public virtual Packet GetPacketFor(NetState ns)
```
Changed to:
```cs
public virtual void SendPacketTo(NetState ns)
```

Converts targeting packets

---

docs/overrides/main.html

Bumps docs to fix embed image not showing up for modernuo.com

docs: Fixes embed images for modernuo.com

---

Projects/UOContent/Mobiles/BaseCreature.cs

fix (basecreature): NPE crash for IsFriendPet

---

Projects/UOContent/Engines/Spawners/BaseSpawner.cs
Projects/UOContent/Engines/Spawners/SpawnerEntry.cs
Projects/UOContent/Items/Farming/FarmableCrop.cs
Projects/UOContent/Mobiles/BaseCreature.cs

fix(spawner): Fixes spawners infinitely spawning

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MovementPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/TargetPacketsTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/VendorBuyPacketTests.cs
Projects/Server.Tests/Tests/Utility/IPAddressTests.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Network/Packets/OutgoingMovementPackets.cs

fix(core): Converts death animation

---

Directory.Build.props
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/PacketUtilities.cs
Projects/Server/Network/Packets/MobilePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

fix(core): Converts mobile moving packet

---

Projects/Server.Tests/Tests/Utility/StringHelperTests.cs
Projects/Server/Utilities/StringHelpers.cs

fix(core): Fixes wrap not slicing properly

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/IncomingMobilePackets.cs
Projects/Server/Network/Packets/MobilePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/UOContent/Engines/Party/Party.cs

fix(core): Converts mobile name and animation packets

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/ClientVersion.cs
Projects/Server/Geometry/Rectangle2D.cs
Projects/Server/Guild.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/MobilePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Commands/Generic/Implementors/BaseCommandImplementor.cs
Projects/UOContent/Commands/HelpInfo.cs
Projects/UOContent/Commands/SignParser.cs
Projects/UOContent/Engines/Chat/ChatActionHandlers.cs
Projects/UOContent/Engines/Spawners/BaseSpawner.cs
Projects/UOContent/Gumps/Guilds/GuildDeclareWarPrompt.cs
Projects/UOContent/Gumps/Guilds/New Guild System/BaseGuildGump.cs
Projects/UOContent/Items/Body Parts/Head.cs
Projects/UOContent/Items/Books/BaseBook.cs
Projects/UOContent/Items/Misc/Teleporter.cs
Projects/UOContent/Misc/InhumanSpeech.cs
Projects/UOContent/Mobiles/Vendors/NPC/AnimalTrainer.cs
Projects/UOContent/Skills/ForensicEval.cs

fix(core): Converts healthbar packets

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/IncomingAccountPackets.cs
Projects/Server/Network/Packets/IncomingPlayerPackets.cs
Projects/Server/Network/Packets/MobilePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs

fix(core): Converts MobileUpdate packet

---

Projects/Server/Main.cs
Projects/Server/Mobiles/Mobile.cs
Projects/UOContent/Engines/Pathing/PathFollower.cs
Projects/UOContent/Mobiles/AI/AnimalAI.cs
Projects/UOContent/Mobiles/AI/ArcherAI.cs
Projects/UOContent/Mobiles/AI/BaseAI.cs
Projects/UOContent/Mobiles/AI/BerserkAI.cs
Projects/UOContent/Mobiles/AI/MeleeAI.cs
Projects/UOContent/Mobiles/AI/PredatorAI.cs
Projects/UOContent/Mobiles/AI/ThiefAI.cs
Projects/UOContent/Mobiles/Familiars/BaseFamiliar.cs

TODO: Fix other direction/movement issues and duplicate packets.

fix(AI): Fixes direction issue with NPCs

---

Projects/Server/Buffers/CircularBufferWriter.cs
Projects/Server/Buffers/SpanWriter.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/NetworkCompression.cs
Projects/Server/Network/Packets/IncomingAccountPackets.cs
Projects/Server/Network/Packets/OutgoingAccountPackets.cs
Projects/UOContent/Skills/Tracking/OutgoingArrowPackets.cs

fix(core): Converts account packets to spanwriter

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/ContainerPacketTests.cs
Projects/Server/Network/PacketUtilities.cs
Projects/Server/Network/Packets/OutgoingCombatPackets.cs
Projects/Server/Network/Packets/OutgoingContainerPackets.cs
Projects/Server/Utilities/Utility.cs

fix(core): Converts combat and container packets

---

Projects/Server/Network/Packets/OutgoingDamagePackets.cs
Projects/Server/Network/Packets/OutgoingEffectPackets.cs
Projects/Server/Network/Packets/OutgoingEquipmentPackets.cs
Projects/Server/Network/Packets/OutgoingGumpPackets.cs
Projects/Server/Network/Packets/OutgoingLightPackets.cs
Projects/Server/Network/Packets/OutgoingMapPackets.cs
Projects/Server/Network/Packets/OutgoingMenuPackets.cs

fix(core): Converts more packets

---

Projects/Server/Network/Packets/OutgoingAccountPackets.cs
Projects/Server/Network/Packets/OutgoingCombatPackets.cs
Projects/Server/Network/Packets/OutgoingLightPackets.cs
Projects/Server/Network/Packets/OutgoingMapPackets.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Network/Packets/OutgoingMovementPackets.cs
Projects/Server/Network/Packets/OutgoingPlayerPackets.cs

fix(core): Converts message, mobile, movement, player packets

---

Projects/Server/Network/Packets/OutgoingAccountPackets.cs
Projects/Server/Network/Packets/OutgoingContainerPackets.cs
Projects/Server/Network/Packets/OutgoingEquipmentPackets.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Network/Packets/OutgoingPlayerPackets.cs
Projects/Server/Network/Packets/OutgoingSecureTradePackets.cs
Projects/Server/Network/Packets/OutgoingTargetPackets.cs
Projects/Server/Network/Packets/OutgoingVendorBuyPackets.cs
Projects/Server/Network/Packets/OutgoingVendorSellPackets.cs

fix(core): Converts the rest of the packets

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/GumpPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/PlayerPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/VendorSellPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/VirtualHairPacketTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/VirtualHairPackets.cs
Projects/Server/Items/VirtualHair.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/UOContent/Items/Misc/Corpses/Packets.cs

fix(core): Converts virtual hair packets

---

Projects/Server/Buffers/SpanWriter.cs
Projects/Server/Network/Packets/IncomingMessagePackets.cs
Projects/Server/Network/Packets/IncomingPackets.cs
Projects/UOContent.Tests/Tests/Network/Packets/ArrowPacketTests.cs
Projects/UOContent.Tests/Tests/Network/Packets/BuffIconPacketTests.cs
Projects/UOContent.Tests/Tests/Network/Packets/BuffIconPackets.cs
Projects/UOContent/Misc/BuffIcons.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

fix(content): Converts buff icon packets

---

Projects/Server/Buffers/SpanWriter.cs
Projects/Server/Gumps/GumpAlphaRegion.cs
Projects/Server/Gumps/GumpBackground.cs
Projects/Server/Gumps/GumpButton.cs
Projects/Server/Gumps/GumpCheck.cs
Projects/Server/Gumps/GumpECHandleInput.cs
Projects/Server/Gumps/GumpGroup.cs
Projects/Server/Gumps/GumpHtml.cs
Projects/Server/Gumps/GumpHtmlLocalized.cs
Projects/Server/Gumps/GumpImage.cs
Projects/Server/Gumps/GumpImageTileButton.cs
Projects/Server/Gumps/GumpImageTiled.cs
Projects/Server/Gumps/GumpItem.cs
Projects/Server/Gumps/GumpItemProperty.cs
Projects/Server/Gumps/GumpLabel.cs
Projects/Server/Gumps/GumpLabelCropped.cs
Projects/Server/Gumps/GumpMasterGump.cs
Projects/Server/Gumps/GumpPage.cs
Projects/Server/Gumps/GumpRadio.cs
Projects/Server/Gumps/GumpSpriteImage.cs
Projects/Server/Gumps/GumpTextEntry.cs
Projects/Server/Gumps/GumpTextEntryLimited.cs
Projects/Server/Gumps/GumpTooltip.cs
Projects/Server/Network/Packets/OutgoingMovementPackets.cs
Projects/Server/Network/Packets/OutgoingPlayerPackets.cs
Projects/Server/Network/Packets/OutgoingTargetPackets.cs
Projects/Server/Network/Packets/OutgoingVendorBuyPackets.cs
Projects/Server/ObjectPropertyList.cs

chore(core): Makes gump builder code a little more readable

---

Projects/UOContent/Network/ProtocolExtensions.cs

fix(network): Adds protocol extensions

---

Projects/Server/Items/Container.cs
Projects/Server/Items/Item.cs
Projects/UOContent/Items/Misc/Blocker.cs
Projects/UOContent/Items/Misc/Corpses/Corpse.cs
Projects/UOContent/Items/Misc/LOSBlocker.cs
Projects/UOContent/Multis/HouseFoundation.cs

fix(core): Cleans up OPL code

---

Projects/Server/Effects.cs
Projects/Server/Items/Item.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/PacketUtilities.cs
Projects/Server/Network/Packets/OutgoingEffectPackets.cs
Projects/Server/Network/Packets/OutgoingEntityPackets.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/Server/Network/Packets/OutgoingPlayerPackets.cs
Projects/Server/World/World.cs
Projects/UOContent/Commands/Handlers.cs
Projects/UOContent/Commands/VisibilityList.cs
Projects/UOContent/Engines/Doom/LeverPuzzle/LeverPuzzleController.cs
Projects/UOContent/Engines/MLQuests/Mobiles/SirHelper.cs
Projects/UOContent/Engines/Party/Party.cs
Projects/UOContent/Items/Games/BaseBoard.cs
Projects/UOContent/Misc/Guild.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

fix(core): Cleans up uninitialized packets

---

Projects/Server/Geometry/Rectangle2D.cs
Projects/Server/Items/Item.cs
Projects/Server/Json/Converters/IPEndPointConverter.cs
Projects/Server/Json/Converters/TimeSpanConverter.cs
Projects/Server/Json/JsonConfig.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/IncomingEntityPackets.cs
Projects/Server/Network/Pipe.cs
Projects/Server/TileMatrix.cs
Projects/Server/TileMatrixPatch.cs
Projects/UOContent/Commands/Handlers.cs
Projects/UOContent/Engines/BulkOrders/SmallSmithBOD.cs
Projects/UOContent/Engines/BulkOrders/SmallTailorBOD.cs
Projects/UOContent/Engines/CannedEvil/ChampionSkullBrazier.cs
Projects/UOContent/Engines/Chat/Channel.cs
Projects/UOContent/Engines/Craft/Core/CraftItem.cs
Projects/UOContent/Engines/Craft/DefBlacksmithy.cs
Projects/UOContent/Engines/Craft/DefCarpentry.cs
Projects/UOContent/Engines/Craft/DefGlassblowing.cs
Projects/UOContent/Engines/Craft/DefMasonry.cs
Projects/UOContent/Engines/Doom/LeverPuzzle/LeverPuzzleItems.cs
Projects/UOContent/Engines/Events/BroadcastEvent.cs
Projects/UOContent/Engines/Khaldun/KhaldunPitTeleporter.cs
Projects/UOContent/Engines/MLQuests/Mobiles/BoonCollector.cs
Projects/UOContent/Engines/Pathing/SlowAStarAlgorithm.cs
Projects/UOContent/Engines/Plants/PlantItem.cs
Projects/UOContent/Items/Misc/TrashBarrel.cs
Projects/UOContent/Misc/CharacterCreation.cs
Projects/UOContent/Skills/Anatomy.cs
Projects/UOContent/Skills/EvalInt.cs

chore: Code cleanup

---

Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Items/Item.cs
Projects/Server/Items/VirtualHair.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingEntityPackets.cs
Projects/Server/Network/Packets/OutgoingItemPackets.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/UOContent.Tests/Tests/Engines/Party/Packets.cs
Projects/UOContent.Tests/Tests/Engines/Party/PartyPacketTests.cs
Projects/UOContent.Tests/Tests/Items/Misc/Corpses/CorpsePacketTests.cs
Projects/UOContent.Tests/Tests/Items/Misc/Corpses/Packets.cs
Projects/UOContent.Tests/UOContent.Tests.csproj
Projects/UOContent/Engines/Party/Party.cs
Projects/UOContent/Engines/Party/PartyPackets.cs
Projects/UOContent/UOContent.csproj

fix(party): Converts party packets

---

Projects/Server/ExpansionInfo.cs
Projects/Server/Network/PacketUtilities.cs
Projects/UOContent.Tests/Tests/Items/Games/Mahjong/MahjongPacketTests.cs
Projects/UOContent.Tests/Tests/Items/Games/Mahjong/Packets.cs
Projects/UOContent/Items/Games/Mahjong/MahjongGame.cs
Projects/UOContent/Items/Games/Mahjong/MahjongPackets.cs
Projects/UOContent/Items/Games/Mahjong/MahjongPlayers.cs

fix(content): Converts mahjong packets

---

Projects/UOContent.Tests/Tests/Items/Maps/Packets.cs
Projects/UOContent.Tests/Tests/Items/Maps/TestMapItemPackets.cs
Projects/UOContent/Items/Maps/MapItem.cs
Projects/UOContent/Items/Maps/MapItemPackets.cs

fix(core): Converts map item packets

---

Projects/UOContent.Tests/Tests/Items/Bulletin Boards/BulletinBoardPacketTests.cs
Projects/UOContent.Tests/Tests/Items/Games/Mahjong/MahjongPacketTests.cs
Projects/UOContent.Tests/Tests/Items/Maps/TestMapItemPackets.cs
Projects/UOContent.Tests/Tests/Items/Misc/Corpses/CorpsePacketTests.cs

fix(tests): Fixes tests failing

---

Directory.Build.props

fix(build): Adds MUO constant

---

Projects/Server/Serialization/Persistence.cs

Notes:
- Optimizations and parallel writing will not be supported in this PR.

fix(core): Adds back persistence.

---

Projects/Server/Mobiles/Mobile.cs

I want the ability to override the Freeze and Paralyze methods in my custom scripts to be able to call a hook and determine if the player is immune to paralyzing effects and need these methods to be virtual in order to do this.

feat(mobile): Make Mobile Paralyze and Freeze functions virtual

---

Projects/Server/AssemblyHandler.cs
Projects/Server/Items/BaseMulti.cs
Projects/Server/Items/Item.cs
Projects/Server/Skills.cs
Projects/UOContent.Tests/Tests/Multis/Boats/BoatPacketTests.cs
Projects/UOContent.Tests/Tests/Multis/Boats/Packets.cs
Projects/UOContent/Commands/Profiling.cs
Projects/UOContent/Engines/ConPVP/Games/BombingRun.cs
Projects/UOContent/Gumps/AdminGump.cs
Projects/UOContent/Multis/Boats/BaseBoat.cs
Projects/UOContent/Multis/Boats/BoatPackets.cs
Projects/UOContent/Multis/Boats/Plank.cs
Projects/UOContent/Multis/HousePlacementTool.cs
Projects/UOContent/Network/EntityPackets.cs

fix(core): Converts to ref struct enumerators

---

Directory.Build.props

fix: Reverts GitVersioning

---

Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/TcpServer.cs

fix(core): Fixes a few netstate issues

---

Projects/UOContent/Gumps/AdminGump.cs

fix(admin): Replaces vendors with spawners

---

Projects/Server.Tests/Tests/Buffers/CircularBufferReaderTests.cs
Projects/Server.Tests/Tests/Utility/IPAddressTests.cs
Projects/Server/Network/ServerInfo.cs
Projects/Server/Utilities/Utility.cs
Projects/Server/World/World.cs
Projects/UOContent/Commands/Object Creation/Categorization.cs
Projects/UOContent/Misc/ServerList.cs
Projects/UOContent/Misc/ShrinkTable.cs

fix(core): Fixes IPMatch and some cleanup

---

Projects/Server/Gumps/GumpHtml.cs
Projects/Server/Gumps/GumpLabel.cs
Projects/Server/Gumps/GumpLabelCropped.cs
Projects/Server/Gumps/GumpTextEntry.cs
Projects/Server/Gumps/GumpTextEntryLimited.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/Packets/IncomingVendorPackets.cs

fix(core): Fixes buy packet

---

Projects/UOContent/Engines/Factions/Items/Traps/FactionSawTrap.cs

Adds back missing serial constructor for faction saw trap.

fix(factions): Fixes faction saw trap

---

Projects/Server/TileMatrix/TileMatrix.cs

fix(core): Removes UOP file error message

---

Projects/UOContent/Items/Misc/Corpses/CorpsePackets.cs

fix(network): Fixes corpse packet

---

Projects/Server/Buffers/ValueStringBuilder.cs
Projects/Server/Collections/OrderedHashSet.cs
Projects/Server/Items/Item.cs
Projects/Server/Main.cs
Projects/Server/Mobiles/Mobile.cs
Projects/UOContent/Commands/Object Creation/CAGObject.cs

fix(core): Fixes nullables being disabled

---

Projects/Server/Buffers/SpanReader.cs

fix(network): SpanReader ReadAscii

---

Projects/UOContent/Mobiles/PlayerMobile.cs

fix(recipes): Fixes NPE with recipes on PlayerMobile

---

.github/workflows/build-test.yml
.github/workflows/create-release.yml
azure-pipelines.yml

Notes: We may need multiple release updates to get this right.

fix(releases): Updates releases

---

Projects/Server/Network/NetState/NetState.cs

fix(core): Fixes connecting with CUO/Orion

---

Projects/Server.Tests/Fixtures/ServerFixture.cs
Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Events/AccountLoginEvent.cs
Projects/Server/Events/AggressiveActionEvent.cs
Projects/Server/Events/CharacterCreatedEvent.cs
Projects/Server/Events/EventSink.cs
Projects/Server/Events/FastwalkEvent.cs
Projects/Server/Events/GameLoginEvent.cs
Projects/Server/Events/MovementEvent.cs
Projects/Server/Events/ServerCrashedEvent.cs
Projects/Server/Events/ServerListEvent.cs
Projects/Server/Events/SocketConnectionEvent.cs
Projects/Server/Events/SpeechEvent.cs
Projects/Server/Utilities/Utility.cs
Projects/Server/World/World.cs
Projects/Server/World/WorldEvents.cs
Projects/UOContent/Configuration/EmailConfiguration.cs
Projects/UOContent/Misc/AutoSave.cs
Projects/UOContent/Misc/CrashGuard.cs

fix(core): Fixes flow for saves, adds logging and configurations

---

Projects/Server/Guild.cs

Fixes issues with guild type serialization.

fix(core): Fixes guild serialization

---

Projects/Server/Utilities/Utility.cs

Fix for TimeStamp

---

azure-pipelines.yml

Fixes azure pipelines not running on merge to main.

fix(workflow): Fixes azure pipelines

---

Projects/Server/Main.cs
Projects/UOContent/Commands/Object Creation/Add.cs
Projects/UOContent/Engines/Pathing/MovementPath.cs

fix(core): Fixes date time uses by using stop watch

---

Projects/Server/Buffers/ValueStringBuilder.cs
Projects/Server/Maps/Map.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Commands/Object Creation/Decorate.cs
Projects/UOContent/Commands/Object Creation/DecorateMag.cs
Projects/UOContent/Engines/Harvest/Mining.cs
Projects/UOContent/Engines/Pathing/FastMovement.cs
Projects/UOContent/Engines/Pathing/Movement.cs
Projects/UOContent/Engines/Pathing/PathFollower.cs
Projects/UOContent/Engines/Pathing/SlowAStarAlgorithm.cs
Projects/UOContent/Engines/Treasures of Tokuno/TreasuresOfTokuno.cs
Projects/UOContent/Items/Construction/Doors/HouseDoors.cs
Projects/UOContent/Items/Misc/Guillotine.cs
Projects/UOContent/Items/Skill Items/Tools/BaseRunicTool.cs
Projects/UOContent/Items/Special/Veteran Rewards/Cannon.cs
Projects/UOContent/Misc/Geometry.cs
Projects/UOContent/Mobiles/Special/Paragon.cs
Projects/UOContent/Multis/Boats/BaseBoat.cs
Projects/UOContent/Multis/Houses/BaseHouse.cs
Projects/UOContent/Network/ConnectUO.cs
Projects/UOContent/Network/UOGateway.cs
Projects/UOContent/Skills/Discordance.cs
Projects/UOContent/Spells/Fifth/PoisonField.cs
Projects/UOContent/Spells/Fourth/FireField.cs

fix(network): Adds UOG & Fixes ConnectUO packet

---

Projects/Server/Attributes.cs
Projects/UOContent/Commands/HelpInfo.cs
Projects/UOContent/Network/ConnectUO.cs
Projects/UOContent/Network/UOGateway.cs

fix(core): Fixes call priority

---

Projects/UOContent/Mobiles/Animals/Mounts/BaseMount.cs

https://github.com/modernuo/ModernUO/issues/560

Prevent gargoyles from hopping on a mount

---

Projects/Server/Network/Packets/IncomingPlayerPackets.cs

* Fixes check on virtue packet
Closes #562

fix(core): Fixes virtue packet

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Items/Item.cs
Projects/Server/Network/Packets/OutgoingEntityPackets.cs
Projects/Server/Network/Packets/OutgoingItemPackets.cs
Projects/Server/Network/Packets/OutgoingMobilePackets.cs
Projects/UOContent/Items/Misc/Blocker.cs
Projects/UOContent/Items/Misc/LOSBlocker.cs
Projects/UOContent/Multis/Boats/BoatPackets.cs
Projects/UOContent/Network/EntityPackets.cs

fix(core): Fixes item mask in incoming mobile packet

---

Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Configuration/ServerSettings.cs
Projects/Server/IAccount.cs
Projects/Server/Items/VirtualCheck.cs
Projects/Server/Json/Converters/JsonNullableEnumConverter.cs
Projects/Server/Json/Converters/JsonNullableEnumConverterFactory.cs
Projects/Server/Json/JsonConfig.cs
Projects/Server/Main.cs
Projects/Server/Maps/MapLoader.cs
Projects/Server/Network/Packets/OutgoingGumpPackets.cs
Projects/Server/World/World.cs
Projects/UOContent.Tests/Tests/Items/Books/BookPacketTests.cs
Projects/UOContent/Configuration/ExpansionConfiguration.cs
Projects/UOContent/Items/Books/BaseBook.cs

TODO:
Expand the nullable enums deserialization factory to work with any type by pulling the factory and creating an instance of the converter.

fix(core): Updates expansion and map configurations (fixes map issues)

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/SecureTradePackets.cs
Projects/Server/Network/Packets/OutgoingSecureTradePackets.cs

- Updates secure trade packets. Ref: https://docs.polserver.com/packets/index.php?Packet=0x6F

fix(networking): Standardizes SecureTrade packets

---

Projects/UOContent/Gumps/Props/PropsGump.cs

fix: Fixes props gump read only

---

Projects/Server/World/World.cs
Projects/UOContent/Accounting/AccessRestrictions.cs
Projects/UOContent/Accounting/AccountHandler.cs
Projects/UOContent/Accounting/Accounts.cs
Projects/UOContent/Commands/Dupe.cs
Projects/UOContent/Configuration/EmailConfiguration.cs
Projects/UOContent/Engines/ML Quests/Objectives/DeliverObjective.cs
Projects/UOContent/Misc/CharacterCreation.cs
Projects/UOContent/Misc/Cleanup.cs
Projects/UOContent/Misc/ClientVerification.cs
Projects/UOContent/Misc/CrashGuard.cs
Projects/UOContent/Misc/ServerList.cs
Projects/UOContent/Multis/Houses/ContestHouses.cs
Projects/UOContent/Multis/Houses/HousePackets.cs
Projects/UOContent/Network/ConnectUO.cs
Projects/UOContent/Regions/GuardedRegion.cs

This pull requests replaces some common usages of `Console.WriteLine` for calls to `ILogger`.

chore(logging): Migrate some logs to ILogger

---

Projects/Benchmarks/Benchmarks/Logging/BenchmarkConsoleLogging.cs
Projects/Server/Items/Container.cs
Projects/Server/Main.cs
Projects/Server/Maps/Map.cs
Projects/Server/Network/Packets/IncomingTargetingPackets.cs
Projects/Server/Network/TcpServer.cs
Projects/Server/TileData.cs
Projects/Server/TileMatrix/TileMatrix.cs
Projects/Server/World/EntityPersistence.cs
Projects/Server/World/World.cs

Example of what the logs look like:

chore(logging): Logging cleanup

---

Projects/Server/AssemblyHandler.cs

- Fixes assembly handler so it properly loads type aliases.

fix(core): Fixes assembly handler of alias types

---

Projects/Server/AssemblyHandler.cs
Projects/UOContent/Mobiles/Monsters/ML/Animal/RagingGrizzlyBear.cs

fix(content): Fixes duplicate alias type

---

Projects/Server/Network/NetState/NetState.cs

Fixes an issue with awaiting for a seed that matches an informational packet.
Thanks @andreakarasho!

Fixes awaiting seed for < v6 clients

---

Projects/Server/World/World.cs

Reverts some clever code that is not clever.

fix(serial): Fixes type inference for serialization

---

Projects/UOContent/Multis/Houses/HouseFoundation.cs
Projects/UOContent/Multis/Houses/HousePackets.cs

fix(houses): Fixes custom house packets

---

Projects/Server/Items/VirtualCheck.cs

Changes virtual checks to enable with Core.TOL instead.

fix(currency): Changes virtual checks setting

---

Projects/UOContent/Gumps/Props/PropsGump.cs

fix: Reverts PR #96

---

Projects/Server/Main.cs

Some architectures (specifically docker) have an issue with tick count and high precision timing.
This handles those weird cases so instead of outright freezing, you may get timer precision loss.

fix(core): Fixes core tick count for VMs

---

Directory.Build.props
Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Server.csproj
Projects/UOContent.Tests/UOContent.Tests.csproj
Projects/UOContent/UOContent.csproj
README.md

fix(core): Adds Fedora 32/33 & RHEL 7/8 support.

---

Distribution/Data/Locations/tokuno.json

fix(admin): Fixes Tokuno Go Locations

---

Projects/Server/Random/BaseRandomSource.cs

Changes RNG to not crash in release mode with bad values.

fix(core): Changes random source to use debut assert

---

Directory.Build.props
azure-pipelines.yml

Adds Fedora for build testing

---

Projects/SerializationGenerator/EntitySerializationGenerator.cs
Projects/SerializationGenerator/SerializableMigration/Rules/PrimitiveTypeMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/Rules/PrimitiveUOTypeMigrationRule.cs
Projects/SerializationGenerator/SerializerSyntaxReceiver.cs

Fixes code genning classes with no fields.
Fixes code genning primitives.

fix(codegen): Fixes serializing classes with no fields

---

Projects/Server/Guild.cs
Projects/Server/Items/Item.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Serialization/ISerializable.cs
Projects/UOContent/Accounting/AccessRestrictions.cs
Projects/UOContent/Accounting/Account.cs
Projects/UOContent/Accounting/AccountHandler.cs
Projects/UOContent/Accounting/Security/PBKDF2PasswordProtection.cs

Fixes a major issue where serialization was not respecting the dirty tracking feature flag.

fix(core): Fixes issues with deserialization due to bad checking of dirty tracking

---

Projects/Server/Guild.cs
Projects/Server/IEntity.cs
Projects/Server/Items/Item.cs
Projects/Server/Main.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Serialization/ISerializable.cs
Projects/Server/Serialization/ManualDirtyChecking.cs
Projects/Server/TileMatrix/TileMatrix.cs
Projects/Server/World/World.cs
Projects/UOContent/Accounting/Account.cs

- Adds `[ManualDirtyChecking]` for anyone that adds it themselves.
- Adds detection of `[Serializable]` and `[ManualDirtyChecking]` at startup to help identify scripts that need migration.

fix(codegen): Adds manual dirty checking

---

Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.DeserializeMethod.cs
Projects/SerializationGenerator/SerializableMigration/Rules/ArrayMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/Rules/HashSetMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/Rules/ListMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/SerializableMigrationSchema.cs
Projects/SerializationGenerator/SerializationGenerator.csproj
Projects/SerializationGenerator/SerializerSyntaxReceiver.cs
Projects/SerializationSchemaGenerator/Application.cs
Projects/SerializationSchemaGenerator/SyntaxVisitor.cs
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
publish.cmd

fix(codegen): Fixes codegen on VS2019

---

Distribution/Data/regions.json
Projects/Server/Json/DynamicJson.cs
Projects/Server/Main.cs
Projects/Server/Regions/Region.cs
Projects/UOContent/Regions/BaseRegion.cs

Fixes `Region` being loaded instead of `BaseRegion` as the default region type.

fix(core): Fixes region base type

---

Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.SerializeMethod.cs
Projects/SerializationGenerator/SerializableMigration/Rules/PrimitiveTypeMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/Rules/SerializationMethodSignatureMigrationRule.cs
Projects/SerializationGenerator/SourceGeneration/SymbolMetadata/SymbolMetadata.Builtin.cs
Projects/SerializationGenerator/SourceGeneration/SymbolMetadata/SymbolMetadata.UO.cs
Projects/Server/IAccount.cs
Projects/Server/Serialization/BufferReader.cs
Projects/UOContent/Accounting/Account.cs
Projects/UOContent/Accounting/AccountComment.cs
Projects/UOContent/Accounting/AccountTag.cs
Projects/UOContent/Accounting/Accounts.cs
Projects/UOContent/Gumps/AdminGump.cs
Projects/UOContent/Migrations/Server.Accounting.Account.v2.json

fix(core): Fixes accounts and moves it to codegen

---

Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/OutgoingMessagePackets.cs
Projects/Server/ObjectPropertyList.cs
Projects/UOContent/Skills/AnimalTaming.cs

fix(core): Fixes OPL with stale header

---

Projects/Server/Main.cs

Fixes bad check

---

Projects/UOContent/Commands/Generic/Commands/Commands.cs
Projects/UOContent/Commands/Object Creation/AddGump.cs
Projects/UOContent/Spells/Base/SpellRegistry.cs

* Fixes `[cast`
* Fixes `[add` search

fix(types): Fixes casting spell by type and [Add keyword search

---

Projects/UOContent/Engines/Quests/Collector/Mobiles/Impresario.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleStone.cs
Projects/UOContent/Mobiles/Townfolk/Banker.cs
Projects/UOContent/Mobiles/Vendors/BaseVendor.cs
Projects/UOContent/Mobiles/Vendors/NPC/AnimalTrainer.cs

Fixes various locations where account gold is not used.

fix: Fixes bank box withdraw using account gold

---

Projects/Server/Collections/PooledRefQueue.cs

Adds a queue that is a ref struct using pooled arrays. This is perfect for temporary iterations.

Adds pooled ref queue

---

Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Main.cs

fix: Updates first load configuration

---

Projects/UOContent/Items/Weapons/Artifacts/AxeOfTheHeavens.cs
Projects/UOContent/Items/Weapons/Artifacts/BladeOfInsanity.cs
Projects/UOContent/Items/Weapons/Artifacts/BladeOfTheRighteous.cs
Projects/UOContent/Items/Weapons/Artifacts/BoneCrusher.cs
Projects/UOContent/Items/Weapons/Artifacts/BreathOfTheDead.cs
Projects/UOContent/Items/Weapons/Artifacts/Frostbringer.cs
Projects/UOContent/Items/Weapons/Artifacts/LegacyOfTheDreadLord.cs
Projects/UOContent/Items/Weapons/Artifacts/SerpentsFang.cs
Projects/UOContent/Items/Weapons/Artifacts/StaffOfTheMagi.cs
Projects/UOContent/Items/Weapons/Artifacts/TheBeserkersMaul.cs
Projects/UOContent/Items/Weapons/Artifacts/TheDragonSlayer.cs
Projects/UOContent/Items/Weapons/Artifacts/TheDryadBow.cs
Projects/UOContent/Items/Weapons/Artifacts/TheTaskmaster.cs
Projects/UOContent/Items/Weapons/Artifacts/TitansHammer.cs
Projects/UOContent/Items/Weapons/Artifacts/ZyronicClaw.cs
Projects/UOContent/Migrations/Server.Items.AxeOfTheHeavens.v0.json
Projects/UOContent/Migrations/Server.Items.BladeOfInsanity.v0.json
Projects/UOContent/Migrations/Server.Items.BladeOfTheRighteous.v0.json
Projects/UOContent/Migrations/Server.Items.BoneCrusher.v0.json
Projects/UOContent/Migrations/Server.Items.BreathOfTheDead.v0.json
Projects/UOContent/Migrations/Server.Items.Frostbringer.v0.json
Projects/UOContent/Migrations/Server.Items.LegacyOfTheDreadLord.v0.json
Projects/UOContent/Migrations/Server.Items.SerpentsFang.v0.json
Projects/UOContent/Migrations/Server.Items.StaffOfTheMagi.v0.json
Projects/UOContent/Migrations/Server.Items.TheBeserkersMaul.v0.json
Projects/UOContent/Migrations/Server.Items.TheDragonSlayer.v0.json
Projects/UOContent/Migrations/Server.Items.TheDryadBow.v0.json
Projects/UOContent/Migrations/Server.Items.TheTaskmaster.v0.json
Projects/UOContent/Migrations/Server.Items.TitansHammer.v0.json
Projects/UOContent/Migrations/Server.Items.ZyronicClaw.v0.json

This PR will
- Convert Weapons/Artifacts  to code gen

fix(codegen): weapons/artifacts

---

README.md

Was messing around with codespaces on GitHub and thought I'd fix this link!

Fix README publish link

---

Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Skills/AnimalTaming.cs
Projects/UOContent/Spells/Base/Spell.cs
Projects/UOContent/Spells/Fourth/ArchProtection.cs
Projects/UOContent/Spells/Fourth/FireField.cs
Projects/UOContent/Spells/Second/Protection.cs

* Fixes interruption of spells
* Changes arch protection to use a ref queue
* Some syntax cleanup

fix(spells): Fixes interruption of spells

---

Projects/SerializationGenerator/SerializableEntityGeneration/SerializationEntityGeneration.ContentStruct.cs

* Fixes bool? not being a valid type for save flag property migrations.
* Fixes wrong SaveFlag type used in the if check for boolean save flags.

fix(codegen): Fixes bool in migration structs

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MapPacketTests.cs
Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Maps/MapLoader.cs
Projects/Server/NativeReader.cs
Projects/Server/Network/Packets/OutgoingMapPackets.cs
Projects/Server/TileData.cs
Projects/Server/TileMatrix/TileMatrix.cs
Projects/Server/TileMatrix/TileMatrixPatch.cs

* Fixes reading map/static diffs

fix(map): Fixes map diffs (Old Haven/Minax)

---

Projects/UOContent/Commands/Generic/Implementors/AreaCommandImplementor.cs

fix: Fixes area command not working

---

Projects/UOContent/Misc/CharacterCreation.cs

Added Human Armor to Warrior Template when making new character. Accurate with OSI.

fix: Fixes warrior starting items

---

Projects/UOContent/Items/Weapons/BaseWeapon.cs

GetDamageTypes should be called everytime. Only when wearing quiver there should be alteredBowDamage into this types.

Fixes damagetypes when wearing quivers

---

Projects/Server/Items/Item.cs
Projects/Server/Network/Packets/OutgoingMapPackets.cs
Projects/UOContent/Items/Weapons/Abilities/Dismount.cs
Projects/UOContent/Items/Weapons/Abilities/WeaponAbility.cs
Projects/UOContent/Mobiles/Vendors/SBInfo/SBAnimalTrainer.cs

* Fixes race messaging for required race restrictions
* Removes double mana check for abilities
* Reverts brown bear back to original body conv value so CUO can render the vendor buy graphic.

fix: Fixes various issues

---

Projects/UOContent/Spells/Seventh/MeteorSwarm.cs

According to the following:
- uo.com wiki
- UO -> LBR original paper guides
- Prima Strategy Guides for UO -> AOS

fix: Fixes meteor swarm words of power

---

Projects/UOContent/Gumps/AdminGump.cs

Quick fix to admingump.cs to generate spawners.

fix: Fixes spawner generation in admin gump

---

Projects/UOContent/Commands/Object Creation/Add.cs
Projects/UOContent/Commands/Properties.cs
Projects/UOContent/Engines/Spawners/BaseSpawner.cs
Projects/UOContent/Gumps/Props/PropsGump.cs
Projects/UOContent/Gumps/Props/SetGump.cs
Projects/UOContent/Utilities/Types.cs

* Marks GUID a parsable type
* Cleans up type conversions
Closes #757

fix: Makes guid settable. Cleans up type conversions

---

Projects/UOContent/Engines/Craft/DefBlacksmithy.cs
Projects/UOContent/Gumps/AdminGump.cs

Removing whitespace and streamlining code for a more organized look.

chore: Cleans up code

---

Projects/UOContent/Commands/Batch.cs
Projects/UOContent/Commands/Generic/Commands/Interface.cs
Projects/UOContent/Commands/Object Creation/Add.cs
Projects/UOContent/Commands/Properties.cs

* Consolidates the property logic between properties and add.
* Fixes a bug with setting properties

fix: Consolidates properties code

---

Projects/UOContent/Items/Decoration Artifacts/StealableArtifactsSpawner.cs

fix: Don't crash the world if a stealable artifact fails to construct

---

Projects/Server/EventLoopTasks.cs
Projects/Server/Items/Item.cs
Projects/Server/Main.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/TcpServer.cs
Projects/Server/Timer/Timer.TimerWheel.cs

* Adds `core.enableIdleCPU` to modernuo.json
* Forces idle CPU on in DEBUG
* Reverts idle detection back to CPS
Closes #772

fix: Adds idle cpu config and forces on in debug

---

Projects/UOContent/Skills/Meditation.cs
Projects/UOContent/Spells/Base/SpellHelper.cs
Projects/UOContent/Spells/Fifth/PoisonField.cs
Projects/UOContent/Spells/Fourth/FireField.cs
Projects/UOContent/Spells/Seventh/EnergyField.cs
Projects/UOContent/Spells/Sixth/ParalyzeField.cs
Projects/UOContent/Spells/Third/WallOfStone.cs

Fixed Meditation skill check
Fixed eastToWest calc of magic fields

Some minor fixes

---

Projects/UOContent/Items/Quivers/BaseQuiver.cs

Reverts the bad logic change.
Closes #800

fix: Fixes quiver logic

---

Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.DeserializeMethod.cs
Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.SerializeMethod.cs
Projects/SerializationGenerator/SerializableMigration/SerializableMigrationRulesEngine.cs
Projects/Server/Network/NetworkCompression.cs
Projects/Server/Network/Packets/OutgoingEquipmentPackets.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Commands/Properties.cs
Projects/UOContent/Compression/ZstdArchive.cs
Projects/UOContent/Engines/Bulk Orders/BaseBOD.cs
Projects/UOContent/Engines/CannedEvil/ChampionSpawn.cs
Projects/UOContent/Gumps/Props/SetGump.cs
Projects/UOContent/Items/Addons/BaseAddon.cs
Projects/UOContent/Items/Addons/BaseAddonContainer.cs
Projects/UOContent/Items/Armor/BaseArmor.cs
Projects/UOContent/Items/Clothing/BaseClothing.cs
Projects/UOContent/Items/Talismans/BaseTalisman.cs
Projects/UOContent/Migrations/Server.Engines.BulkOrders.BaseBOD.v1.json
Projects/UOContent/Migrations/Server.Items.BaseAddon.v3.json
Projects/UOContent/Migrations/Server.Items.BaseAddonContainer.v2.json
Projects/UOContent/Migrations/Server.Items.BaseArmor.v8.json
Projects/UOContent/Migrations/Server.Items.BaseClothing.v6.json
Projects/UOContent/Misc/CharacterCreation.cs
Projects/UOContent/Misc/PacketThrottles.cs
Projects/UOContent/Mobiles/PlayerMobile.cs
Projects/UOContent/Skills/Tracking/OutgoingArrowPackets.cs
Projects/UOContent/Spells/Base/SpellHelper.cs
Projects/UOContent/World Saves/AutoArchive.cs

* Fixes code genning clothing
* Fixes code genning armor
* Fixes code genning BODs
Close #808

fix: Fixes code genning armor, clothing, and BODs

---

Projects/Server/TileData.cs
Projects/UOContent/Engines/Pathing/Movement.cs

* Fixes wrong item list used for item detection

fix: Fixes movement issue

---

Projects/SerializationGenerator/SerializableMigration/Rules/DictionaryMigrationRule.cs
Projects/SerializationGenerator/SerializableMigration/SerializableMigrationRulesEngine.cs
Projects/SerializationGenerator/SourceGeneration/SymbolMetadata/SymbolMetadata.Builtin.cs
Projects/Server/Utilities/Utility.cs

* Adds Dictionary serialization rule for codegen
* Adds Tidy for Dictionary. By default will remove key/value pairs where the key or value is either null or deleted. Only works for ISerializable keys or values (or both).

Adds dictionary to codegen

---

Projects/Server/Interfaces.cs
Projects/UOContent/Items/Weapons/BaseWeapon.cs
Projects/UOContent/Items/Weapons/Fists.cs
Projects/UOContent/Items/Weapons/Ranged/BaseRanged.cs

* Removes linq
* Removes list allocation for area effect
* Removes redundant swing overload
* Cleans up code

fix: Weapons cleanup

---

Projects/UOContent/Mobiles/BaseCreature.cs

* Removes LINQ
* Removes some list allocations
TODO: Remove list allocations in OnDeath

fix: BaseCreature cleanup

---

Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj

* Bumps zlib
* Bumps zstd
* Bumps argon2

fix: Bumps native runtimes to .NET 6

---

Projects/Server/Configuration/ServerConfiguration.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/TcpServer.cs
Projects/UOContent/Misc/ClientVerification.cs

* Adds MinRequired and MaxRequired settings
* Removes god client detection
* Streamlines the kick messaging
* Fixes detecting client version on mac/linux
Supersedes #847

fix: Adds better client verification

---

Projects/Server/Serialization/BufferReader.cs
Projects/Server/World/World.cs
Projects/UOContent/Misc/Guild.cs
Projects/UOContent/Spells/Base/Spell.cs

* Fixes guilds being marked as deleted because the leader hasn't been deserialized yet.
* Fixes LastSerialization issue.

fix: Fixes guild deserialization

---

Projects/UOContent/Items/Skill Items/Magical/Potions/Explosion Potions/BaseExplosionPotion.cs

* Fixes the users list not being cleared out
* Removes the LINQ allocations

fix: Fixes explosion potions

---

Directory.Build.props
Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
azure-pipelines.yml

* Adds Debian 11 support
* Fixes Fedora 34 support
* Updates CentOS8 support

fix: Adds Debian 11 and fixes Fedora 34 support

---

Projects/SerializationGenerator/SerializationGenerator.csproj
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj

* Adds explicit dependencies VS requires
* Reverts back to .NET Standard 2.0

fix: Fixes VS builds by reverting back to nstd20

---

Projects/UOContent/Items/Weapons/BaseWeapon.cs

fix: Fixes damage bonus and makes it easier to read

---

Projects/UOContent/Spells/Base/MagerySpell.cs
Projects/UOContent/Spells/Bushido/CounterAttack.cs
Projects/UOContent/Spells/Bushido/Evasion.cs
Projects/UOContent/Spells/Chivalry/ConsecrateWeapon.cs
Projects/UOContent/Spells/Chivalry/NobleSacrifice.cs
Projects/UOContent/Spells/Fifth/DispelField.cs
Projects/UOContent/Spells/Fourth/ArchCure.cs
Projects/UOContent/Spells/Necromancy/AnimateDeadSpell.cs
Projects/UOContent/Spells/Necromancy/BloodOathSpell.cs
Projects/UOContent/Spells/Necromancy/CurseWeapon.cs
Projects/UOContent/Spells/Necromancy/EvilOmen.cs
Projects/UOContent/Spells/Seventh/EnergyField.cs
Projects/UOContent/Spells/Third/MagicLock.cs
Projects/UOContent/Spells/Third/Teleport.cs
Projects/UOContent/Spells/Third/Unlock.cs
Projects/UOContent/Spells/Third/WallOfStone.cs

* Fixes first/second circle scrolls crashing
* Consolidates some resistance logic
* Removes unnecessary multiple lookups for items on layer
Closes #890

fix: Fixes first/second scrolls crashing

---

Projects/Server/Commands.cs
Projects/UOContent/Commands/Batch.cs
Projects/UOContent/Commands/DragEffects.cs
Projects/UOContent/Commands/Dupe.cs
Projects/UOContent/Commands/Handlers.cs
Projects/UOContent/Commands/HelpInfo.cs
Projects/UOContent/Commands/Object Creation/AddGump.cs
Projects/UOContent/Commands/Object Creation/Decorate.cs
Projects/UOContent/Commands/Object Creation/DecorateMag.cs
Projects/UOContent/Commands/Object Creation/GenTeleporter.cs
Projects/UOContent/Commands/Profiling.cs
Projects/UOContent/Commands/ResetStaffDress.cs
Projects/UOContent/Commands/ShardTime.cs
Projects/UOContent/Commands/SignParser.cs
Projects/UOContent/Commands/Skills.cs
Projects/UOContent/Commands/SkillsMenu.cs
Projects/UOContent/Commands/StaffAccess.cs
Projects/UOContent/Commands/Statics.cs
Projects/UOContent/Commands/VisibilityList.cs
Projects/UOContent/Commands/Wipe.cs

* Adds StaffAccess command
* Adds ResetStaffDress command

feat: Adds StaffAccess and ResetStaffDress commands

---

Projects/Benchmarks/Benchmarks/Rng/BenchmarkDoubleVsFixed.cs
Projects/Benchmarks/Program.cs
Projects/UOContent/Skills/Snooping.cs

* Not allowed to snoop staff
* Staff that snoop won't broadcast messages
* Benchmarks RNG for double vs fixed int

fix: Fixes snooping staff

---

Projects/UOContent/Items/Weapons/BaseWeapon.cs

Enable instahit by adding the setting `"melee.enableInstaHit": "True"` to modernuo.json

feat: Adds instahit option

---

Projects/UOContent/Misc/ServerAccess.cs

* Removes new password on reset option.
* Fixes a bug with the feature that would allow an exploit.

fix: Fixes server access for owners

---

Distribution/Data/teleporters.json

Updated the Blighted Grove Teleporters for accuracy.

Update Blighted Grove Teleporters

---

Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/Packets/IncomingAccountPackets.cs
Projects/UOContent/Commands/Properties.cs
Projects/UOContent/Gumps/ClientGump.cs

fix: Fixes various minor issues

---

Projects/UOContent/Spells/Base/Spell.cs

Publish 100 introduced the cliloc change for insufficient mana. This was rolled out starting with v7.0.65.4 on 6/22/2018.

fix: Fixes mana insufficient message for newer clients.

---

Projects/UOContent/Gumps/HouseDemolishGump.cs
Projects/UOContent/Items/Misc/BankCheck.cs
Projects/UOContent/Items/Misc/Gold.cs
Projects/UOContent/Mobiles/Townfolk/Banker.cs

Fixes bankcheck dropping to the player's feet if their bank is full.

fix: Fixes bank checks falling to the floor.

---

Projects/UOContent/Items/Containers/TrappableContainer.ExecuteTrap.cs
Projects/UOContent/Items/Containers/TrappableContainer.cs
Projects/UOContent/Migrations/Server.Items.Talwar.v0.json
Projects/UOContent/Migrations/Server.Items.TrappableContainer.v3.json

Splits out trappable container so the logic is easier to expand.
Changes trappable containers to be code genned.

fix: Codegens trappable containers

---

Projects/UOContent/Mobiles/PlayerMobile.cs
Projects/UOContent/Spells/Ninjitsu/AnimalForm.cs

- Adds ability to block mount permanently. Great for preventing mounting in certain custom situations.
- Fixes an NPE I found while updating this code.

fix: Fixes mount blocking and adds permanent option for customization

---

Projects/UOContent/Items/Containers/TreasureMapChest.cs

fix for exception on line 364 due to _lifted hashmap not being initialized.

fix: nullptr exception

---

Projects/UOContent/Items/Misc/PoolOfAcid.cs

fix: Updates pool of acid

---

Projects/Server/Items/Item.cs
Projects/UOContent/Items/Skill Items/Magical/Spellbook.cs

fix: Fixes drag drop bounce issue

---

.config/dotnet-tools.json
Directory.Build.props
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj

Updates the serialization and schema generators to a considerably more optimized version.

fix: Updates serialization generator

---

Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj

Bumps the source gen version which has crash fixes.

fix: Fixes source gen bugs

---

Projects/UOContent/Engines/Factions/Mobiles/Guards/GuardAI.cs
Projects/UOContent/Mobiles/AI/AIControlMobileTarget.cs
Projects/UOContent/Mobiles/AI/AnimalAI.cs
Projects/UOContent/Mobiles/AI/ArcherAI.cs
Projects/UOContent/Mobiles/AI/BaseAI.cs
Projects/UOContent/Mobiles/AI/BerserkAI.cs
Projects/UOContent/Mobiles/AI/HealerAI.cs
Projects/UOContent/Mobiles/AI/MageAI.cs
Projects/UOContent/Mobiles/AI/MeleeAI.cs
Projects/UOContent/Mobiles/AI/PredatorAI.cs
Projects/UOContent/Mobiles/AI/ThiefAI.cs
Projects/UOContent/Mobiles/AI/VendorAI.cs
Projects/UOContent/Mobiles/BaseCreature.cs

View without whitespace: https://github.com/modernuo/ModernUO/pull/1084/files?diff=split&w=1

fix: Cleans up AI code

---

Projects/UOContent/Spells/Base/MagerySpell.cs

Added comment for magery circle formula
Adjusted first circle min skill value

Magery circle formula

---

Projects/Server/Gumps/GridInit.cs
Projects/Server/Gumps/GridSystem.cs
Projects/UOContent/Engines/Spawners/SpawnerControllerGump.cs

latest version

---

Projects/UOContent/Engines/Spawners/SpawnerControllerGump.cs

fix: Fixes [spawn gump headers

---

Projects/Server/Items/Item.cs
Projects/Server/Items/ItemBounds.cs
Projects/Server/Json/Converters/ClientVersionConverter.cs
Projects/Server/Json/Converters/ClientVersionConverterFactory.cs
Projects/Server/Json/Converters/FlagsConverter.cs
Projects/Server/Json/Converters/GuidConverter.cs
Projects/Server/Json/Converters/GuidConverterFactory.cs
Projects/Server/Json/Converters/IPEndPointConverter.cs
Projects/Server/Json/Converters/IPEndPointConverterFactory.cs
Projects/Server/Json/Converters/MapConverter.cs
Projects/Server/Json/Converters/MapConverterFactory.cs
Projects/Server/Json/Converters/Point2DConverter.cs
Projects/Server/Json/Converters/Point2DConverterFactory.cs
Projects/Server/Json/Converters/Point3DConverter.cs
Projects/Server/Json/Converters/Point3DConverterFactory.cs
Projects/Server/Json/Converters/Rectangle3DConverter.cs
Projects/Server/Json/Converters/Rectangle3DConverterFactory.cs
Projects/Server/Json/Converters/TimeSpanConverter.cs
Projects/Server/Json/Converters/TimeSpanConverterFactory.cs
Projects/Server/Json/Converters/TypeConverter.cs
Projects/Server/Json/Converters/TypeConverterFactory.cs
Projects/Server/Json/Converters/WorldLocationConverter.cs
Projects/Server/Json/Converters/WorldLocationConverterFactory.cs
Projects/Server/Mobiles/Body.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Network/NetState/NetState.cs
Projects/Server/Network/Packets/OutgoingContainerPackets.cs
Projects/Server/Regions/Region.cs
Projects/Server/Skills.cs
Projects/Server/Utilities/Utility.cs

Adds more serilog logging and cleans up some server files.

fix: Updates more logging to Serilog

---

Projects/UOContent/Engines/Craft/DefAlchemy.cs
Projects/UOContent/Engines/Craft/DefBlacksmithy.cs
Projects/UOContent/Engines/Craft/DefBowFletching.cs
Projects/UOContent/Engines/Craft/DefCarpentry.cs
Projects/UOContent/Engines/Craft/DefCartography.cs
Projects/UOContent/Engines/Craft/DefCooking.cs
Projects/UOContent/Engines/Craft/DefGlassblowing.cs
Projects/UOContent/Engines/Craft/DefInscription.cs
Projects/UOContent/Engines/Craft/DefMasonry.cs
Projects/UOContent/Engines/Craft/DefTailoring.cs
Projects/UOContent/Engines/Craft/DefTinkering.cs

While this fixes the bug, it introduces significant world load time.
I'll have a permanent fix soon!
See #1109

fix: Fixes crafting so it doesn't create items before world load.

---

Projects/Server/Buffers/ValueStringBuilder.cs
Projects/UOContent/Engines/Spawners/SpawnPropsGump.cs

Fixes issue with ValueStringBuilder having an empty initial buffer.

fix: Fixes ValueStringBuilder initial rented buffer

---

Projects/UOContent/Engines/Spawners/SpawnerControllerGump.cs

plase test it, i don't have old client like 5.xxx

for old client

---

Projects/UOContent/Engines/ConPVP/DuelContext.cs
Projects/UOContent/Engines/Factions/Mobiles/Guards/GuardAI.cs
Projects/UOContent/Items/Talismans/BaseTalisman.cs
Projects/UOContent/Items/Weapons/Abilities/MortalStrike.cs
Projects/UOContent/Spells/Base/SpellHelper.cs
Projects/UOContent/Spells/Chivalry/NobleSacrifice.cs
Projects/UOContent/Spells/Chivalry/RemoveCurse.cs
Projects/UOContent/Spells/Mysticism/SpellPlagueSpell.cs
Projects/UOContent/Spells/Necromancy/BloodOathSpell.cs
Projects/UOContent/Spells/Necromancy/MindRot.cs

* Fix statmod naming mismatch: everything in code searches for "[Magic] {type} Offset" but stat reductions are being added as "[Magic] {type} Curse"

fix: Fixes curses and spell effects

---

Projects/Server/Timer/Timer.DelayCall.cs
Projects/Server/Timer/Timer.DelayStateCall.cs
Projects/Server/Timer/Timer.Pool.cs
Projects/Server/Timer/Timer.TimerWheel.cs
Projects/Server/Timer/Timer.cs
Projects/Server/Timer/TimerExecutionToken.cs
Projects/UOContent/Mobiles/Monsters/ML/Special/Ilhenir.cs

View with whitespace off:
https://github.com/modernuo/ModernUO/pull/1115/files?diff=split&w=1

fix: Fixes pooled timer detach

---

Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePackets.cs
Projects/Server/Buffers/ValueStringBuilderExtensions.cs
Projects/UOContent/Accounting/Account.cs
Projects/UOContent/Engines/Craft/Core/CraftSystem.cs
Projects/UOContent/Gumps/AdminGump.cs
Projects/UOContent/Items/New Haven Quest Rewards/HammerOfHephaestus.cs
Projects/UOContent/Items/Weapons/Abilities/ForceArrow.cs
Projects/UOContent/Items/Weapons/Abilities/WeaponAbilityPackets.cs
Projects/UOContent/Misc/SkillCheck.cs
Projects/UOContent/Mobiles/Animals/Mounts/Kirin.cs
Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Mobiles/Healers/BaseHealer.cs
Projects/UOContent/Mobiles/Monsters/Humanoid/Melee/RestlessSoul.cs
Projects/UOContent/Multis/Houses/HouseSign.cs
Projects/UOContent/Multis/Houses/PreviewHouse.cs
Projects/UOContent/Skills/Stealing.cs
Projects/UOContent/Spells/Eighth/AirElemental.cs
Projects/UOContent/Spells/Eighth/EarthElemental.cs
Projects/UOContent/Spells/Eighth/EnergyVortex.cs
Projects/UOContent/Spells/Eighth/FireElemental.cs
Projects/UOContent/Spells/Eighth/SummonDaemon.cs
Projects/UOContent/Spells/Eighth/WaterElemental.cs
Projects/UOContent/Spells/Ninjitsu/MirrorImage.cs
Projects/UOContent/Spells/UnsummonTimer.cs

fix: Fixes spell mechanics and misc bugs

---

Projects/UOContent/Items/Skill Items/Fishing/Misc/SpecialFishingNet.cs

The mobs where never spawned because index == 14 was never the case.

SpecialFishingNet: fixes indexing bug

---

Projects/Server/Serialization/AdhocPersistence.cs
Projects/Server/Serialization/BinaryFileReader.cs
Projects/Server/Serialization/BufferReader.cs
Projects/Server/Serialization/GenericPersistence.cs
Projects/Server/World/EntityPersistence.cs

Note: View without whitespace - https://github.com/modernuo/ModernUO/pull/1133/files?w=1

fix: Fixes serializing strings

---

Projects/Server/Utilities/Utility.cs
Projects/UOContent/Misc/CharacterCreation.cs

- Focus is a Pre-AOS skill.
- Utility.cs was off by one. Guessing this was just overlooked when Throwing skill was added.

Focus Fixes

---

Projects/UOContent/Items/Addons/SHTeleporter.cs

As we discussed sometime ago, the solen hiven teleporters cause null reference exceptions on server start up due to the setters having extra processing for updating their parent/child objects. The exception happens because there is no guarantee on world load that those objects will have been deserialised yet, therefore can be null.
I tested it and it works, let me know if anything needs changing. I wasn't sure on a name so I went with Raw.
Thanks!

fix: Solen teleporter deserialization null pointer exception

---

Projects/UOContent/Engines/Craft/Core/CraftGumpItem.cs
Projects/UOContent/Engines/Craft/Core/CraftItem.cs
Projects/UOContent/Engines/Craft/Core/CraftSystem.cs

As we discuss together the NameNumber is different from the ItemId used for the graphic which was presenting wrong image on the craft item gump.
Thanks and best regards,

* Fix craft items having the wrong image on the craft item gump

---

Projects/Server/Buffers/PooledArraySpanFormattable.cs
Projects/Server/Mobiles/Mobile.cs
Projects/Server/Text/StringHelpers.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Engines/Help/SpeechLogGump.cs
Projects/UOContent/Items/Guilds/Guildstone.cs

A minor fix for titles not appearing in game e.g. 
Raylor "the provisioner"

fix: Fixes mobile titles not displaying properly

---

Projects/UOContent/Items/Weapons/BaseWeapon.cs
Projects/UOContent/Misc/AOS.cs
Projects/UOContent/Misc/WeightOverloading.cs
Projects/UOContent/Mobiles/PlayerMobile.cs
Projects/UOContent/Spells/Base/SpellHelper.cs
Projects/UOContent/Spells/Fifth/Paralyze.cs
Projects/UOContent/Spells/Necromancy/EvilOmen.cs
Projects/UOContent/Spells/Necromancy/PainSpike.cs
Projects/UOContent/Spells/Necromancy/Strangle.cs
Projects/UOContent/Spells/Necromancy/WraithForm.cs

I found these issues that need fixing
* Wraith form was sometimes leeching twice and sometimes not leeching…
* People frozen in place on 0 stam
* Strangle fixes
* 120 eval Paralyze vs 120 resisting spells shouldnt freeze people

fix: Blood Oath & wraith form

---

.config/dotnet-tools.json
Directory.Build.props
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
version.json

Adds diagnostics for compiling and the IDE for serialization.

feat: Bumps serialization generator (v2.3) to add diagnostics

---

Projects/UOContent/Commands/Object Creation/Decorate.cs
Projects/UOContent/Commands/Object Creation/DecorateMag.cs
Projects/UOContent/Engines/Craft/DefGlassblowing.cs
Projects/UOContent/Items/Lights/Lantern.cs
Projects/UOContent/Items/Misc/OilFlask.cs
Projects/UOContent/Migrations/Server.Items.EmptyOilFlask.v0.json
Projects/UOContent/Migrations/Server.Items.FishOilFlask.v0.json
Projects/UOContent/Migrations/Server.Items.OilFlask.v0.json
Projects/UOContent/Mobiles/Vendors/SBInfo/SBProvisioner.cs

Fixes #1079
Added Empty Oil Flask, Oil Flask & Fish Oil Flask. Non-decorative lanterns will now run out of fuel.
Added recipe for Empty Oil Flask.
Added Oil Flask to the provisions supplier.

feat: Implement Oil Flask & Refueling

---

Projects/Server/Collections/PooledRefQueue.cs
Projects/Server/Gumps/GumpAlphaRegion.cs
Projects/Server/Gumps/GumpBackground.cs
Projects/Server/Gumps/GumpButton.cs
Projects/Server/Gumps/GumpCheck.cs
Projects/Server/Gumps/GumpECHandleInput.cs
Projects/Server/Gumps/GumpEntry.cs
Projects/Server/Gumps/GumpGroup.cs
Projects/Server/Gumps/GumpHtml.cs
Projects/Server/Gumps/GumpHtmlLocalized.cs
Projects/Server/Gumps/GumpImage.cs
Projects/Server/Gumps/GumpImageTileButton.cs
Projects/Server/Gumps/GumpImageTiled.cs
Projects/Server/Gumps/GumpItem.cs
Projects/Server/Gumps/GumpItemProperty.cs
Projects/Server/Gumps/GumpLabel.cs
Projects/Server/Gumps/GumpLabelCropped.cs
Projects/Server/Gumps/GumpMasterGump.cs
Projects/Server/Gumps/GumpPage.cs
Projects/Server/Gumps/GumpRadio.cs
Projects/Server/Gumps/GumpSpriteImage.cs
Projects/Server/Gumps/GumpTextEntry.cs
Projects/Server/Gumps/GumpTextEntryLimited.cs
Projects/Server/Gumps/GumpTooltip.cs
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
global.json

Fixes support for .NET 7 SDK and VS 2022 v17.4+

fix: Fixes compiling with .NET 7 SDK

---

Projects/UOContent/Items/Skill Items/Musical Instruments/BaseInstrument.cs
Projects/UOContent/Misc/AOS.cs
Projects/UOContent/Mobiles/Abilities/AreaEffectMonsterAbility.cs
Projects/UOContent/Mobiles/Abilities/ColossalBlow.cs
Projects/UOContent/Mobiles/Abilities/DeathExplosion.cs
Projects/UOContent/Mobiles/Abilities/DestroyEquipment.cs
Projects/UOContent/Mobiles/Abilities/EnergyBoltCounter.cs
Projects/UOContent/Mobiles/Abilities/FireBreath.cs
Projects/UOContent/Mobiles/Abilities/GraspingClaw.cs
Projects/UOContent/Mobiles/Abilities/MagicalBarrier.cs
Projects/UOContent/Mobiles/Abilities/MagicalBarrierCounter.cs
Projects/UOContent/Mobiles/Abilities/MonsterAbility.Abilities.cs
Projects/UOContent/Mobiles/Abilities/MonsterAbility.cs
Projects/UOContent/Mobiles/Abilities/MonsterAbilityAttack.cs
Projects/UOContent/Mobiles/Abilities/MonsterAbilityTrigger.cs
Projects/UOContent/Mobiles/Abilities/MonsterAbilityType.cs
Projects/UOContent/Mobiles/Abilities/PoisonGasAreaAttack.cs
Projects/UOContent/Mobiles/Abilities/PoisonGasCounter.cs
Projects/UOContent/Mobiles/Abilities/StunAttack.cs
Projects/UOContent/Mobiles/Abilities/SummonLesserUndead.cs
Projects/UOContent/Mobiles/Abilities/SummonUndead.cs
Projects/UOContent/Mobiles/Abilities/ThrowHatchetCounter.cs
Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Mobiles/Monsters/LBR/Exodus/ExodusMinion.cs
Projects/UOContent/Mobiles/Monsters/LBR/Exodus/ExodusOverseer.cs
Projects/UOContent/Mobiles/Monsters/Ore Elementals/CopperElemental.cs

* Adds magical barrier ability (Pre-UOML)
* Adds ebolt counter (Post-UOML)

feat: Adds magical barrier ability

---

Projects/UOContent/Engines/CannedEvil/ChampionSpawn.cs
Projects/UOContent/Engines/Virtues/Compassion.cs
Projects/UOContent/Engines/Virtues/Honor.cs
Projects/UOContent/Engines/Virtues/Justice.cs
Projects/UOContent/Engines/Virtues/Sacrifice.cs
Projects/UOContent/Engines/Virtues/Valor.cs
Projects/UOContent/Misc/Titles.cs
Projects/UOContent/Mobiles/ChampionTitleInfo.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

* Adds ShouldAtrophy to conditionally atrophy as a tail to serialization
* Fixes champion titles throwing NPE (old RunUO bug)
* Fixes chamopion titles atrophying immediately with the first world save after acquiring it. (Also old RunUO bug)

fix: Fixes champion titles

---

Projects/Server/Mobiles/Mobile.cs
Projects/Server/Mobiles/Mods/StatMod.cs
Projects/UOContent/Spells/Base/SpellHelper.cs

* Fixes recursion with DeltaQueue causing multiple sets of packets to be sent to the client.
* Fixes StatMods that are expired not being checked properly.
* Adds a timer to properly expire/remove stat mods instead of relying on a side-effect.

fix: Fixes DeltaQueue recursion, StatMod bug, and memory leak

---

Projects/Server.Tests/Tests/Geometry/Point2DTests.cs
Projects/Server.Tests/Tests/Geometry/Point3DTests.cs
Projects/Server.Tests/Tests/Geometry/Rectangle2DTests.cs
Projects/Server.Tests/Tests/Geometry/Rectangle3DTests.cs
Projects/Server.Tests/Tests/Geometry/WorldLocationTests.cs
Projects/Server/Attributes.cs
Projects/Server/Geometry/Point2D.cs
Projects/Server/Geometry/Point3D.cs
Projects/Server/Geometry/Rectangle2D.cs
Projects/Server/Geometry/Rectangle3D.cs
Projects/Server/Geometry/WorldLocation.cs
Projects/Server/Maps/Map.cs
Projects/Server/Mobiles/Body.cs
Projects/Server/Poison.cs
Projects/Server/Race.cs
Projects/Server/Serial.cs
Projects/Server/Text/OrdinalStringHelpers.cs
Projects/Server/Text/TextDefinition.cs
Projects/UOContent/Commands/Generic/Extensions/Compilers/ConditionalCompiler.cs
Projects/UOContent/Utilities/Types.cs
Projects/UOContent/World Saves/AutoArchive.cs

* Adds `ISpanParsable<T>`
* Removes `[Parsable]`
* Fixes querying by serial, body, and a few others.
* Adds `Parse` to `Rectangle3D`
* Fixes AutoArchive NPE
Closes #1209

fix: Adds ISpanParsable and fixes command conditionals

---

Projects/UOContent/Engines/Spawners/BaseSpawner.cs

fixes:
guid will be a duplicate, lists and dictionary will be linked to the source spawner till server restart

fixes duping of spawners

---

Projects/Server/Random/WeightedValue.cs
Projects/Server/Utilities/Utility.cs

Adds weighted value.
```cs
var weightedValues = new WeightedValues<Item>[] { (10, item1), (5, item2), (1, item3) };
var randomItem = weightedValues.RandomWeightedElement();
```

feat: Adds weighted values

---

Projects/Server/Serialization/BufferReader.cs
Projects/UOContent/Holiday Stuff/Halloween/2011/Mobiles/PumpkinHead.cs
Projects/UOContent/Items/Misc/Acid.cs
Projects/UOContent/Mobiles/BaseCreature.cs
Projects/UOContent/Mobiles/Monsters/SE/Kappa.cs

You will receive a deserialization error saying cannot find type PoolOfAcid. This is ok, just hit yes to delete all.

fix: Removes PoolOfAcid and adds Acid

---

Projects/Server/Network/Packets/IncomingTargetingPackets.cs
Projects/Server/Targeting/StaticTarget.cs
Projects/Server/TileList.cs
Projects/Server/TileMatrix/TileMatrix.cs
Projects/Server/TileMatrix/TileMatrixPatch.cs

Fixes missing properties while reading static tiles.
Closes #1320

Adds hue support to StaticTile

---

Projects/Server/TimeZones/TimeZoneHandler.cs

Some windows servers are not updated properly. Specifically Windows 10/2016 and older that is missing the September 2020 rollup will throw an error:
See [here](https://support.microsoft.com/en-us/topic/dst-changes-in-windows-for-yukon-canada-september-8-2020-ae74d7b8-82ed-1d35-e131-fb0796b73b10) for information about this update and how to get it.

fix: Some computers are missing timezones apparently

---

.gitignore
Projects/Server/Json/Converters/BitArrayEnumFlagsConverter.cs
Projects/Server/Json/Converters/BitArrayEnumIndexConverter.cs
Projects/Server/Json/Converters/FlagsConverter.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent/Assistants/AssistantConfiguration.cs
Projects/UOContent/Misc/SkillCheck.cs
Projects/UOContent/Mobiles/PlayerMobile.cs

feat: Moves antimacro to a configuration

---

Projects/UOContent/Engines/Plants/PlantItem.cs

Fixes an infinite loop in PlantItem GetProperties with new clients.

fix: Fixes infinite loop in PlantItem GetProperties

---

Projects/UOContent/Engines/Spawners/Commands/ConvertPremiumSpawners.cs
Projects/UOContent/Items/Skill Items/Musical Instruments/BaseInstrument.cs
Projects/UOContent/Misc/LanguageStatistics.cs
Projects/UOContent/Misc/ShrinkTable.cs
Projects/UOContent/Misc/Titles.cs
Projects/UOContent/Skills/Provocation.cs

For pre-LBR (pub 16), the success rate was at the level of your skill. Since people like the varied difficulty, I toned down the difficulty for <LBR.

fix: Fixes provocation difficulty for pre-pub 16

---

Projects/UOContent/Utilities/Types.cs

Fixes negative numbers and hex numbers in commands.
Closes #1342

fix: Fixes negative numbers in commands

---

Projects/UOContent/Items/Special/House Raffle/HouseRaffleDeed.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleManagementGump.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleRegion.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleStone.cs
Projects/UOContent/Migrations/Server.Items.HouseRaffleDeed.v0.json
Projects/UOContent/Migrations/Server.Items.HouseRaffleStone.v4.json
Projects/UOContent/Migrations/Server.Items.RaffleEntry.v0.json

fix: Optimizes house raffle stone

---

Projects/Server/Serialization/BufferWriter.cs

Fixes an issue with serializing floats.

fix: Fixes serializing float

---

Projects/UOContent/Engines/Harvest/Mining.cs

fix: Fixes mining tile ranges

---

Projects/UOContent/Migrations/Server.Mobiles.BaseHire.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireBard.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireBardArcher.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireBeggar.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireFighter.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireMage.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HirePaladin.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HirePeasant.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireRanger.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireRangerArcher.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireSailor.v0.json
Projects/UOContent/Migrations/Server.Mobiles.HireThief.v0.json
Projects/UOContent/Mobiles/Hireables/BaseHire.cs
Projects/UOContent/Mobiles/Hireables/HireBard.cs
Projects/UOContent/Mobiles/Hireables/HireBardArcher.cs
Projects/UOContent/Mobiles/Hireables/HireBeggar.cs
Projects/UOContent/Mobiles/Hireables/HireFighter.cs
Projects/UOContent/Mobiles/Hireables/HireMage.cs
Projects/UOContent/Mobiles/Hireables/HirePaladin.cs
Projects/UOContent/Mobiles/Hireables/HirePeasant.cs
Projects/UOContent/Mobiles/Hireables/HireRanger.cs
Projects/UOContent/Mobiles/Hireables/HireRangerArcher.cs
Projects/UOContent/Mobiles/Hireables/HireSailor.cs
Projects/UOContent/Mobiles/Hireables/HireThief.cs

feat: Adds hireables

---

Projects/UOContent/Items/Bulletin Boards/BulletinBoard.cs
Projects/UOContent/Items/Bulletin Boards/BulletinMessage.cs

fix: Fixes infinite loop in bulletin board cleanup

---

Projects/UOContent/Mobiles/Vendors/BaseVendor.cs

Changes vendors so they are invulnerable with LBR+ era or with the `vendor.isInvulnerable` setting added.
Closes #1389

fix: Vendors are now invulnerable for LBR+ or by override

---

Projects/UOContent/Engines/ConPVP/Preferences.cs

Mr.Batman fix a problem when a player wrote "i wish to duel" and before starting the fight the server crashed. Replacing the UOContent/Engines/ConPVP/Preferences.cs file resolves the issue.

fix: Fixes NPE crash from "i wish to duel"

---

.github/workflows/build-test.yml
.github/workflows/create-release.yml
README.md
azure-pipelines.yml

- Bumps .NET 7
- Bumps Fedora
- Bumps Debian

chore: Bumps dependencies

---

Projects/Server/Utilities/Utility.cs
Projects/UOContent/Gumps/AdminGump.cs

The method had a non functional logic and crashed. This patch fixes both.

Fixes GetAllSharedAccounts

---

Projects/Server/Gumps/Grid/GumpGrid.cs
Projects/Server/Main.cs
Projects/Server/Skills.cs
Projects/UOContent/Assistants/AssistantHandler.cs
Projects/UOContent/Misc/ProfessionInfo.cs
Projects/UOContent/World Saves/AutoArchive.cs

Use overloads or alternative functions to resolve errors building in Linux Rider.

fix: Fixes missing ordinal string comparisons arguments.

---

Directory.Build.props
ModernUO.sln
Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Server.csproj
Projects/UOContent.Tests/Tests/Accounting/Security/PasswordProtectionTest.cs
Projects/UOContent.Tests/UOContent.Tests.csproj
Projects/UOContent/UOContent.csproj
README.md
publish.cmd

fix: Adds better arm64 support

---

Projects/UOContent/Mobiles/Hireables/HireBard.cs
Projects/UOContent/Mobiles/Hireables/HireBardArcher.cs
Projects/UOContent/Mobiles/Hireables/HireBeggar.cs
Projects/UOContent/Mobiles/Hireables/HireFighter.cs
Projects/UOContent/Mobiles/Hireables/HireMage.cs
Projects/UOContent/Mobiles/Hireables/HirePaladin.cs
Projects/UOContent/Mobiles/Hireables/HirePeasant.cs
Projects/UOContent/Mobiles/Hireables/HireRanger.cs
Projects/UOContent/Mobiles/Hireables/HireRangerArcher.cs
Projects/UOContent/Mobiles/Hireables/HireSailor.cs
Projects/UOContent/Mobiles/Hireables/HireThief.cs
Projects/UOContent/Mobiles/Monsters/Humanoid/Magic/EvilMage.cs
Projects/UOContent/Mobiles/Monsters/Humanoid/Magic/EvilMageLord.cs

fix: Fixes inaccessible items.

---

Projects/Server.Tests/Server.Tests.csproj
Projects/Server.Tests/Tests/Collections/PooledRefQueueTests.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/AccountPacketTests.cs
Projects/UOContent.Tests/Tests/Engines/ML Quests/MLQuestPacketTests.cs
Projects/UOContent.Tests/Tests/Multis/Boats/BoatPacketTests.cs
Projects/UOContent.Tests/UOContent.Tests.csproj

Due to privacy/security concerns, Moq has been removed.
See: https://github.com/moq/moq/issues/1372

fix: Removes Moq due to privacy concerns

---

Projects/Server/Utilities/ActivatorExtensions.cs
Projects/UOContent/Commands/Dupe.cs
Projects/UOContent/Gumps/PlayerVendorGumps.cs

Player vendor customization totally broken without this...

fix: Player vendor gump update so it can construct items with single parameters

---

Projects/UOContent/Commands/ResetStaffDress.cs
Projects/UOContent/Items/Suits/AdminRobe.cs
Projects/UOContent/Items/Suits/BaseSuit.cs
Projects/UOContent/Items/Suits/CounselorRobe.cs
Projects/UOContent/Items/Suits/DeathShroud.cs
Projects/UOContent/Items/Suits/DupreSuit.cs
Projects/UOContent/Items/Suits/GMRobe.cs
Projects/UOContent/Items/Suits/LordBlackthorneSuit.cs
Projects/UOContent/Items/Suits/LordBritishSuit.cs
Projects/UOContent/Items/Suits/SeerRobe.cs
Projects/UOContent/Items/Suits/StaffRobe.cs
Projects/UOContent/Migrations/Server.Items.AdminRobe.v0.json
Projects/UOContent/Migrations/Server.Items.BaseSuit.v1.json
Projects/UOContent/Migrations/Server.Items.CounselorRobe.v0.json
Projects/UOContent/Migrations/Server.Items.DeathShroud.v0.json
Projects/UOContent/Migrations/Server.Items.DupreSuit.v0.json
Projects/UOContent/Migrations/Server.Items.GMRobe.v0.json
Projects/UOContent/Migrations/Server.Items.LordBlackthorneSuit.v0.json
Projects/UOContent/Migrations/Server.Items.LordBritishSuit.v0.json
Projects/UOContent/Migrations/Server.Items.SeerRobe.v0.json
Projects/UOContent/Migrations/Server.Items.StaffRobe.v0.json

fix: Codegens suits and adds StaffRobe to replace the others

---

Projects/UOContent/Gumps/AdminGump.cs

fix: Fixes NPE in FilterAccess

---

docs/starting-server.md

Just a note and tip added to docs.

Starting a server notes and tips.

---

Projects/UOContent/Engines/ConPVP/DuelContext.cs
Projects/UOContent/Engines/Plants/MiscItems/FertileDirt.cs
Projects/UOContent/Engines/Plants/MiscItems/GreenThorns.cs
Projects/UOContent/Engines/Plants/MiscItems/OrangePetals.cs
Projects/UOContent/Engines/Plants/MiscItems/RedLeaves.cs
Projects/UOContent/Engines/Plants/MiscMobiles/GiantIceWorm.cs
Projects/UOContent/Engines/Plants/PlantBowl.cs
Projects/UOContent/Engines/Plants/PlantItem.cs
Projects/UOContent/Engines/Plants/PlantSystem.cs
Projects/UOContent/Engines/Plants/Seed.cs
Projects/UOContent/Migrations/Server.Engines.Plants.PlantBowl.v0.json
Projects/UOContent/Migrations/Server.Engines.Plants.PlantItem.v3.json
Projects/UOContent/Migrations/Server.Engines.Plants.PlantSystem.v3.json
Projects/UOContent/Migrations/Server.Engines.Plants.Seed.v3.json
Projects/UOContent/Migrations/Server.Items.FertileDirt.v0.json
Projects/UOContent/Migrations/Server.Items.GreenThorns.v0.json
Projects/UOContent/Migrations/Server.Items.GreenThornsSHTeleporter.v0.json
Projects/UOContent/Migrations/Server.Items.OrangePetals.v0.json
Projects/UOContent/Migrations/Server.Items.RedLeaves.v0.json
Projects/UOContent/Migrations/Server.Mobiles.GiantIceWorm.v0.json

fix: Codegens and fixes bugs with plant system

---

Projects/UOContent/Mobiles/AI/BaseAI.cs
Projects/UOContent/Mobiles/Hireables/BaseHire.cs

- Set CanDrop on BaseHireable to false
- Added a check to BaseAI::DoOrderRelease() to only drop if CanDrop is true

fix hireables to not drop their pack

---

Projects/Server.Tests/Tests/Client/ClientVersionTests.cs
Projects/Server/Client/ClientType.cs
Projects/Server/Client/ClientVersion.cs
Projects/Server/Client/ClientVersionExtensions.cs
Projects/Server/Effects.cs
Projects/Server/ExpansionInfo.cs
Projects/Server/Network/NetState/NetState.ClientVersion.cs
Projects/UOContent/Engines/Help/PageQueueGump.cs
Projects/UOContent/Gumps/ClientGump.cs
Projects/UOContent/Items/Games/Mahjong/MahjongPackets.cs
Projects/UOContent/Items/Skill Items/Magical/Misc/Moongate.cs
Projects/UOContent/Misc/ClientVerification.cs
Projects/UOContent/Spells/Base/Spell.cs

- Adds KR/EC client versions to ClientVersion
- Adds distinction for enhanced versions in the page queue
- Adds KR Expansion flags
- Adds ProtocolChange enum support
- Adds missing Moongate checks for TerMur
- Adds better message for why a client version is not supported, and which ones are supported.

feat: Adds KR/EC client versions (No actual support yet).

---

Projects/Server/Network/NetState/NetState.cs

Fixes an issue where throttled packets are only processed when new packets arrive.

fix: Fixes throttle receive packet issues

---

Projects/Server/Serialization/GenericEntityPersistence.cs

Fixes a major problem with items having the wrong serial.

fix: Fixes item serials

---

Projects/UOContent/Skills/SkillCheck.cs

fix: Fixes skill gain issue

---

Projects/UOContent/Skills/Tracking/Tracking.cs

Changes tracking to only loop through mobiles once. Keeps track of only the closest 12 and eliminates the sort.

fix: Cleans up Tracking skill and makes it much faster

---

Projects/Server/World/World.cs

Verified this fixes the saving issue when on a 1 vCPU server

Support for single-core machines

---

Projects/UOContent/Engines/Craft/Core/Enhance.cs
Projects/UOContent/Items/Skill Items/Magical/Potions/BasePotion.cs
Projects/UOContent/Items/Weapons/Abilities/InfectiousStrike.cs
Projects/UOContent/Items/Weapons/Abilities/SerpentArrow.cs
Projects/UOContent/Misc/RegenRates.cs
Projects/UOContent/Spells/Base/SpellHelper.cs
Projects/UOContent/Spells/Bushido/Confidence.cs
Projects/UOContent/Spells/Chivalry/PaladinSpell.cs
Projects/UOContent/Spells/Fifth/PoisonField.cs
Projects/UOContent/Spells/Fifth/SummonCreature.cs
Projects/UOContent/Spells/First/Heal.cs
Projects/UOContent/Spells/Ninjitsu/DeathStrike.cs
Projects/UOContent/Spells/Second/Protection.cs
Projects/UOContent/Spells/Seventh/EnergyField.cs
Projects/UOContent/Spells/Sixth/Invisibility.cs
Projects/UOContent/Spells/Third/Poison.cs

fix: Fixes poison field duration, cleans up skill calculations and poison calculations

---

.config/dotnet-tools.json
.github/workflows/build-test.yml
.github/workflows/create-release.yml
Directory.Build.props
Projects/Server.Tests/Server.Tests.csproj
Projects/Server/Buffers/SpanWriter.cs
Projects/Server/Server.csproj
Projects/Server/Text/OrdinalStringHelpers.cs
Projects/Server/Utilities/Utility.cs
Projects/UOContent.Tests/UOContent.Tests.csproj
Projects/UOContent/Accounting/Firewall.cs
Projects/UOContent/Commands/Object Creation/Decorate.cs
Projects/UOContent/Commands/Object Creation/DecorateMag.cs
Projects/UOContent/Network/Packets/IncomingPlayerPackets.cs
Projects/UOContent/Special Systems/Engines/TestCenter.cs
Projects/UOContent/UOContent.csproj
Projects/UOContent/World Saves/AutoArchive.cs
README.md
azure-pipelines.yml
docs/installation.md
global.json
version.json

- Updating to .NET 8 - Required O/S's have slightly changed.

feat: Updates to .NET 8.

---

Projects/Server/Main.cs

Fixes an issue where a save/shutdown (or restart) from admin menu would freeze the process and take up 100% CPU.

fix: Fixes save+shutdown

---

Projects/Server/Items/Item.cs

fix: Fixes negative weight issue

---

README.md

The requirements had an image of dot net 8.0, but the link pointed to 7.0. The installation.md doc explicitly states it wants 8.0, so I updated the link in the readme.md

doc(chore): Update README.md - .Net 8.0 Link

---

Projects/Server/Main.cs

Russian language is not writing the correct characters

fix: Update Main.cs to accept utf8 on console

---

.config/dotnet-tools.json
Projects/Server/Migrations/Server.Items.Container.v0.json
Projects/Server/Server.csproj
Projects/UOContent/Migrations/Server.Items.Hold.v0.json
Projects/UOContent/Migrations/Server.Items.Plank.v1.json
Projects/UOContent/Migrations/Server.Items.TillerMan.v0.json
Projects/UOContent/Migrations/Server.Multis.BaseBoat.v4.json
Projects/UOContent/Migrations/Server.Multis.BaseBoatDeed.v0.json
Projects/UOContent/Migrations/Server.Multis.BaseCamp.v1.json
Projects/UOContent/Migrations/Server.Multis.BaseDockedBoat.v0.json
Projects/UOContent/Migrations/Server.Multis.BrigandCamp.v0.json
Projects/UOContent/Migrations/Server.Multis.LizardmenCamp.v0.json
Projects/UOContent/Migrations/Server.Multis.OrcCamp.v0.json
Projects/UOContent/Migrations/Server.Multis.RatCamp.v0.json
Projects/UOContent/Multis/Camps/BrigandCamp.cs
Projects/UOContent/Multis/Camps/LizardmenCamp.cs
Projects/UOContent/Multis/Camps/OrcCamp.cs
Projects/UOContent/Multis/Camps/RatCamp.cs
Projects/UOContent/UOContent.csproj

- Bumps serialization generator. v2.10.9 fixes an issue with nuget publishing where files were missing.
- Fixes camps missing serialization of their prisoner.
- Adds missing serialization migration files.

fix: Adds missing migration files.

---

Projects/UOContent/Mobiles/AI/AnimalAI.cs
Projects/UOContent/Mobiles/AI/ArcherAI.cs
Projects/UOContent/Mobiles/AI/BaseAI.cs
Projects/UOContent/Mobiles/AI/BerserkAI.cs
Projects/UOContent/Mobiles/AI/MageAI.cs
Projects/UOContent/Mobiles/AI/MeleeAI.cs
Projects/UOContent/Mobiles/AI/PredatorAI.cs
Projects/UOContent/Mobiles/AI/ThiefAI.cs

- Fixes crash bugs with combatant checks in AI
- Fixes mobs not facing each other while in combat. (Old RunUO bug)
- Fixes predators not actually going into guard when their combatant dies.
- Adds missing checks for combatant in various AI.
Note: Much easier to understand changes if whitespace is off - https://github.com/modernuo/ModernUO/pull/1644/files?diff=split&w=1

fix: Fixes crash with combatant and mobs facing each other

---

Projects/UOContent/Items/Weapons/Abilities/Feint.cs
Projects/UOContent/Items/Weapons/BaseWeapon.cs
Projects/UOContent/Spells/Base/SpellHelper.cs

fix: Fixes Feint so it properly reduces damage

---

Projects/Server/Maps/Map.cs
Projects/Server/Regions/Region.cs
Projects/UOContent/Gumps/HouseDemolishGump.cs
Projects/UOContent/Multis/Houses/BaseHouse.cs

- Fixes an issue where regions are added twice to a sector causing them to never get unregistered.

fix: Fixes region duplicates

---

Projects/Server.Tests/Tests/Serialization/DecimalSerializationTests.cs
Projects/Server.Tests/Tests/Serialization/EnumConversionTests.cs
Projects/Server/AssemblyHandler.cs
Projects/Server/Serialization/BufferWriter.cs
Projects/Server/Serialization/IGenericWriter.cs
Projects/UOContent/Engines/Spawners/BaseSpawner.cs
Projects/UOContent/Items/Skill Items/Magical/Misc/PotionKeg.cs
Projects/UOContent/Misc/AccountPrompt.cs

* Fixes spawner timer deserialization
* Adds a check for a null timer and allows the timer to get recreated
* Adds PotionKeg reverse lookup
* Heavily optimizes decimal serialize/deserialize

fix: Fixes spawner timer deserialization, decimal deserialization, and adds potion keg reverse lookup

---

Projects/Server/Console/ConsoleInputHandler.cs
Projects/Server/Serialization/AdhocPersistence.cs
Projects/Server/World/EntityPersistence.cs
Projects/UOContent/Console/ConsoleCommands.cs
Projects/UOContent/Misc/AccountPrompt.cs

* Adds console command support.
* Adds `save`, `restart`, and `shutdown` commands.

feat: Adds console commands

---

Projects/Server.Tests/Tests/Utility/StringHelperTests.cs
Projects/UOContent/Mobiles/Townfolk/BaseEscortable.cs

View with whitespace off: https://github.com/modernuo/ModernUO/pull/1724/files?diff=split&w=1

fix: Fixes missing destinations crashing

---

Projects/UOContent/Engines/CannedEvil/ChampionSpawn.cs
Projects/UOContent/Items/Special/Special Scrolls/ScrollofTranscendence.cs

- Fixes which maps can drop SoT and PS
- Fixes the percentage chance that SoT/PS can drop

fix: Fixes champion drop logic

---

Projects/UOContent/Assistants/AssistantHandler.cs
Projects/UOContent/Commands/Generic/Commands/Commands.cs
Projects/UOContent/Commands/Generic/Commands/DesignInsert.cs
Projects/UOContent/Commands/Handlers.cs
Projects/UOContent/Gumps/AdminGump.cs
Projects/UOContent/Gumps/HouseGumpAOS.cs
Projects/UOContent/Gumps/NoticeGump.cs
Projects/UOContent/Gumps/StaticNoticeGump.cs
Projects/UOContent/Gumps/StaticWarningGump.cs
Projects/UOContent/Gumps/WarningGump.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleManagementGump.cs
Projects/UOContent/Items/Special/House Raffle/HouseRaffleStone.cs
Projects/UOContent/Misc/ClientVerification.cs
Projects/UOContent/Mobiles/Familiars/HordeMinion.cs
Projects/UOContent/Mobiles/PlayerMobile.cs
Projects/UOContent/Multis/Houses/BaseHouse.cs
Projects/UOContent/Multis/Houses/HousePlacementTool.cs
Projects/UOContent/Multis/Houses/HouseSign.cs
Projects/UOContent/Regions/HouseRegion.cs

* Adds `StaticNoticeGump<T>` and `StaticWarningGump<T>`
* Converts NoticeGump/WarningGump to use `DynamicGump`
* Changes various uses of notice gump and warning gump to their static counterpart.

fix: Adds static warning/notice gumps.

---

Projects/UOContent/Misc/ProfessionInfo.cs

* Fixes reading the professions file.
> [!Note]
> Recommend reviewing the files with [whitespaces off](https://github.com/modernuo/ModernUO/pull/1745/files?diff=split&w=1).

fix: Fixes reading prof.txt

---

Projects/UOContent/Items/Misc/Firebomb.cs
Projects/UOContent/Migrations/Server.Items.ArcaneFocus.v0.json
Projects/UOContent/Migrations/Server.Items.TransientItem.v1.json
Projects/UOContent/Migrations/Server.Mobiles.ArcaneFey.v0.json
Projects/UOContent/Migrations/Server.Mobiles.ArcaneFiend.v0.json
Projects/UOContent/Migrations/Server.Mobiles.NatureFury.v0.json
Projects/UOContent/Migrations/Server.Spells.Fifth.PoisonField.v0.json
Projects/UOContent/Migrations/Server.Spells.Fourth.FireFieldItem.v0.json
Projects/UOContent/Migrations/Server.Spells.Seventh.EnergyField.v1.json
Projects/UOContent/Migrations/Server.Spells.Seventh.GateTravelMoongate.v0.json
Projects/UOContent/Migrations/Server.Spells.Sixth.ParalyzeField.v0.json
Projects/UOContent/Migrations/Server.Spells.Third.WallOfStone.v0.json
Projects/UOContent/Spells/Fifth/PoisonField.cs
Projects/UOContent/Spells/Fourth/FireField.cs
Projects/UOContent/Spells/Seventh/EnergyField.cs
Projects/UOContent/Spells/Seventh/GateTravel.cs
Projects/UOContent/Spells/Sixth/ParalyzeField.cs
Projects/UOContent/Spells/Spellweaving/ArcaneCircle.cs
Projects/UOContent/Spells/Spellweaving/Items/ArcaneFocus.cs
Projects/UOContent/Spells/Spellweaving/Items/TransientItem.cs
Projects/UOContent/Spells/Spellweaving/Mobiles/ArcaneFey.cs
Projects/UOContent/Spells/Spellweaving/Mobiles/ArcaneFiend.cs
Projects/UOContent/Spells/Spellweaving/Mobiles/NatureFury.cs
Projects/UOContent/Spells/Third/Teleport.cs
Projects/UOContent/Spells/Third/WallOfStone.cs

- Fixes some serialization issues with spell items
- Fixes accessibility issues with field spells and removes the awkward "InternalItem" concept
- Codegens the fields/items used in spells

fix: Codegens spell items

---

Projects/Server/Gumps/DynamicGumpBuilder.cs
Projects/Server/Gumps/StaticGumpBuilder.cs
Projects/Server/Serialization/GenericEntityPersistence.cs
Projects/Server/Utilities/Html.cs

- Fixes infinite loop in gump builders
- Removes allocations for centering/coloring html in builders

fix: Fixes infinite loop in gump builders

---

Projects/UOContent/Items/Weapons/Abilities/WeaponAbility.cs

- Removes weapon ability context
- Renames context related functions to Cooldown
Note: View with [whitespace off](https://github.com/modernuo/ModernUO/pull/1776/files?diff=split&w=1).

fix: Removes weapon ability context

---

Projects/Server/Events/EventSink.cs
Projects/UOContent/Items/Weapons/Fists.cs
Projects/UOContent/Mobiles/AI/MageAI.cs
Projects/UOContent/Mobiles/AI/ThiefAI.cs
Projects/UOContent/Network/Packets/IncomingExtendedCommandPackets.cs

#1779 Removed StunRequest and DisarmRequest EventSinks

---

Projects/Server/Serialization/BinaryFileWriter.cs
Projects/Server/Serialization/BufferWriter.cs
Projects/Server/Serialization/GenericEntityPersistence.cs
Projects/Server/Serialization/IGenericWriter.cs
Projects/Server/World/EntityPersistence.cs
Projects/UOContent/Mobiles/Vendors/GenericBuy.cs

- Fixes infinite loop with binary file writer
- Removes extra buffer copying with binary file writer
- Removes storing type counts during world save file writing
- Fixes display cache self-deletion warning during world load

fix: Fixes infinite loop in BinaryFileWriter

---

Projects/Application/Application.csproj
Projects/Server/Server.csproj
Projects/UOContent/UOContent.csproj
publish.cmd
publish.sh

- Fixes publishing issues when the Application project was created.
- Fixes missing dotnet clean file deletions

fix: Fixes publishing

---

Projects/Server/Items/Item.cs

- Adds missing IgnoreDupe attributes to Item.cs

fix: Adds missing dupe ignore

---

Projects/UOContent/Gumps/AdminGump.cs

Added option to generated everything at once, in one single click. (Button ID 114)

AdminGump: added option 'Do everything'.

---

Projects/UOContent/Misc/CharacterCreation.cs

Updates character creation so that a newly staff member looks like a GM (Similar to `[ResetStaffDress`).

fix: Creates new staff properly on creation

---

Projects/Application/Application.cs
Projects/Server.Tests/Fixtures/ServerFixture.cs
Projects/Server.Tests/Tests/Network/Packets/Outgoing/GumpPackets.cs
Projects/Server/Events/EventSink.cs
Projects/Server/Items/VirtualCheck.cs
Projects/UOContent.Tests/Tests/Multis/Houses/HousePackets.cs
Projects/UOContent/Engines/Veteran Rewards/RewardSystem.cs
Projects/UOContent/Items/Misc/GumpToggleItems.cs
Projects/UOContent/Items/Misc/WindChimes.cs
Projects/UOContent/Items/Special/MonsterStatuette.cs
Projects/UOContent/Misc/CrashGuard.cs

- Generalizes the On/Off toggle items concept
- Updates the OnOffGump so it is static
- Standardizes OnOff items so they can be used by staff
Decided to not fix #1417 because it is not clear that the clilocs or errors are for that purpose. Can't test this on OSI anyways.

fix: Fixes edge cases with on off items

---

Projects/Server/Mobiles/Mobile.cs

Fixes skills property not being editable in-game.

fix: Fixes skills property not editable in-game

---

Projects/UOContent/Engines/Help/HelpGump.cs

- Updates help gump to use clilocs
- Updates help gump to use new DynamicGump API
> [!Note]
> The help gump needs to be overhauled. The current one is not accurate to OSI, and we should not follow OSI for this feature.

fix: Updates help gump, converts to dynamic gump

---

.github/workflows/code_quality.yml

Adds qodana for code quality static analysis.

chore: Adds Qodana for code quality

---

Projects/UOContent/Multis/Camps/BaseCamp.cs

fix: Fixes camps so they properly respawn

---

Projects/UOContent/Items/Talismans/BaseTalisman.cs

Add missing 'AddLocalized' for summoning Talisman

---

Projects/UOContent/Commands/Object Creation/AddGump.cs

convert the gump shown when using the commands `[addmenu` or `[add <searchString>` to a `DynamicGump` (?) I'm not sure if this makes sense, it has conditionally rendered components

fix: AddGump (for [add <searchString>)

---

Projects/UOContent/Gumps/RunebookGump.cs
Projects/UOContent/Items/Skill Items/Magical/Runebook.cs

migrated `RunebookGump` to `DynamicGump`, cleaned up some of the repeated logic, reduced nesting

fix: migrate RunebookGump to DynamicGump

---

Projects/UOContent/Engines/Bulk Orders/LargeBOD.cs
Projects/UOContent/Engines/Bulk Orders/LargeBODAcceptGump.cs
Projects/UOContent/Engines/Bulk Orders/LargeBODGump.cs
Projects/UOContent/Engines/Bulk Orders/SmallBOD.cs
Projects/UOContent/Engines/Bulk Orders/SmallBODAcceptGump.cs
Projects/UOContent/Engines/Bulk Orders/SmallBODGump.cs
Projects/UOContent/Mobiles/Vendors/BaseVendor.cs

Migrate the most basic BOD gumps to `DynamicGump`.  I've done no larger refactoring of the BOD system in this PR.  Updating the whole system will be an iterative process.
* LargeBODAcceptGump
* LargeBODGump
* SmallBODAcceptGump
* SmallBODGump

fix: migrate BOD gumps

---

Projects/UOContent/Items/Weapons/BaseWeapon.cs

Fix Velocity property not displaying value

---

Projects/UOContent/Engines/Advanced Search/AdvancedSearchCommand.cs
Projects/UOContent/Engines/Advanced Search/AdvancedSearchGump.cs

- Fixes advanced search crash from reverse sorting.
- Moves advanced search processing block to a background thread.

fix: Fixes Advanced Search crash

---

Projects/Server/Utilities/Utility.cs

feat: Adds partial keyword to the Server.Utility class

---

Projects/UOContent/Gumps/Houses/ConfirmDemolishHouseGump.cs
Projects/UOContent/Mobiles/Townfolk/Banker.cs

* Fixes players with no bank box failing to demolish their house.
* Fixes players getting a deed, and a house infinitely.

fix: Fixes demolishing house for a deed

---

Projects/UOContent/Gumps/AddDoorGump.cs

feat: Adds missing door types to [adddoor

---

Projects/UOContent/Misc/DoorGenerator.cs

feat: Adds wall z-offset detection for doorgen

---

Projects/UOContent/Spells/Necromancy/BloodOathSpell.cs

Closes #2026 and thank you @Bohicatv

fix: Fixes blood oath duration

---

Projects/Server/Network/TcpServer.cs

Adds TCP Server exception message to logging.
Based on #2035 and #2036. Thank you for the suggestion @MaxKellermann.

Adds exception message to logger for TCP Server.

---

Projects/UOContent/Gumps/AdminGump.cs

feat: Add shutdown button with 15-minute delay and notification messages

---

Projects/UOContent/Commands/Dupe.cs

Fixes duping items in a container not working properly.

fix: Fixes duping bags

---

Projects/UOContent.Tests/Tests/Accounting/AccountHandlerTests.cs
Projects/UOContent.Tests/Tests/Accounting/Security/PasswordProtectionTest.cs
Projects/UOContent/Accounting/AccountHandler.cs

Optimizes account validation:
```cs
| Method              | Mean       | Error     | StdDev    |
|-------------------- |-----------:|----------:|----------:|
| ForLoopUsernameSafe | 158.536 ns | 1.6247 ns | 1.5198 ns |
| SVUsernameSafe      |   2.859 ns | 0.0581 ns | 0.0796 ns |
```

fix: Use vectorized search for username-password validation.

---

Projects/UOContent.Tests/Tests/Misc/NameVerificationTests.cs
Projects/UOContent.Tests/Tests/Misc/ProfanityProtectionTests.cs
Projects/UOContent/Engines/Character Creation/CharacterCreation.cs
Projects/UOContent/Gumps/Guilds/New Guild System/BaseGuildGump.cs
Projects/UOContent/Items/Deeds/NameChangeDeed.cs
Projects/UOContent/Misc/NameVerification.cs
Projects/UOContent/Misc/ProfanityProtection.cs
Projects/UOContent/Misc/RenameRequests.cs
Projects/UOContent/Mobiles/Vendors/PlayerVendor.cs

Significantly improves the performance of NameVerification & ProfanityProtection:
```cs
| Method         | Mean      | Error     | StdDev    |
|--------------- |----------:|----------:|----------:|
| ValidateName   | 728.34 ns | 13.244 ns | 11.059 ns |
| ValidateNameSV |  26.62 ns |  0.233 ns |  0.207 ns |
```

fix: Fixes and optimizes NameVerification and ProfanityProtection

---

Projects/Server/Mobiles/Mobile.cs

* Fixes the accidental limitation of dead character speech (OoOo) to 256 characters.
* Optimizes it by 1.5x
```cs
| Method                  | Mean      | Error    | StdDev   | Allocated |
|------------------------ |----------:|---------:|---------:|----------:|
| ManuaLoopMutation       | 147.01 ns | 1.298 ns | 1.084 ns |         - |
| SpanLoopMutation        |  92.03 ns | 0.583 ns | 0.487 ns |         - |
```

fix: Fixes mutate speech character limit

---

README.md

chore: Updates JB logo per Jetbrain's request.

---

Projects/Server/Buffers/SpanReader.cs

From issue https://github.com/modernuo/ModernUO/issues/2210

fix: Fixes read method bounds checking and position tracking

---

Projects/UOContent/Engines/Pathing/FastAStarAlgorithm.cs
version.json

* Replaces the node chain with a PriorityQueue.
* Performance difference is up to 3x faster.
```cs
| Method              | Mean     | Error     | StdDev    | Gen0   | Allocated |
|-------------------- |---------:|----------:|----------:|-------:|----------:|
| FastAStar_PQueue    | 2.112 us | 0.0186 us | 0.0165 us | 0.0038 |      64 B |
| FastAStar_NodeChain | 6.430 us | 0.0800 us | 0.1807 us |      - |      64 B |
```
https://github.com/user-attachments/assets/3edd2524-5146-4775-be45-3516f0b01c27

feat: Refactors A* Movement to use PriorityQueue

---

Projects/UOContent/Engines/Bulk Orders/Books/BOBGump.cs
Projects/UOContent/Engines/Bulk Orders/Books/BODBuyGump.cs

* Moves BOBGump to DynamicGump.
* BOBGump no longer creates a whole new gump context object on every send.
* Moves BODBuyGump to StaticGump.

fix: Updates BOB/BOD gumps to the new API
