- Scripts/Engines/Quests/The Summoning/Mobiles/Chyloth.cs
- Scripts/Items/Special/House Raffle/HouseRaffleStone.cs
- Server/Item.cs
- Server/Layer.cs
- Server/LightType.cs
- Server/Mobile.cs
- Server/Network/Packets.cs
- Server/Network/StaticPacketHandlers.cs
- Server/ObjectPropertyList.cs
- Server/Server.csproj
Moves item/mobile locks to a handler. This frees up unused references for the majority of items/mobiles.
Initial test with 15mill items and 1mill mobiles show a 750MB reduction in memory usage.
Also did some cleanup. Sorry for the large diff >.<
> Moves Item/Mobile locks to a handler.

- Projects/Server/Gumps/Gump.cs
Restore Gump.AddTextEntry overload without size parameter as sending GumpTextEntryLimited with size = 0 makes it unusable in standard client.
> Restore Gump.AddTextEntry overload without size parameter

- Projects/Server/Network/Packets.cs
Currently the server tracks item amounts via an int or uint. The network packets, however, expect this value to be transmitted in a 2 byte ushort. The casting truncates the 16 high order bits, causing the client to receive a bizare number. This fix is simple in that it will just pass the max ushort value if the server side Amount field is too high. This really only is an issue when dealing with currencies such as Gold or Tokens.
Scenario: Spawn a large pile of 1M gold and attempt to move it. Only a max of 16960 (Amount & 0xFFFF) can be moved and this value changes each time the Amount changes. It can also cause unpredictable behaviour in the Client if the gold Amount gets truncated to `0` (i.e. 1M-16960 & 0xFFFF).
> Fixes uint to ushort truncation issue for Amount

- Projects/Scripts/Commands/Dupe.cs
[dupe command could not instantiate items that had a constructor with all optional params. Converted the command over to using the new ActivatorUtil class to safely retrieve the correct constructor.
> fixes [dupe for items with optional param constructors

- Projects/Scripts/Gumps/Props/PropsGump.cs
You couldn't modify Attributes property (for example) in [props because the setter for for Attributes is private, which is fine, as you don't need to update the reference.
Changed logic so it only checks prop.CanWrite if the type is a value type, thoughts?
> PropertiesGump only check prop.CanWrite if type is value type.

- Projects/Scripts/Commands/Generic/Commands/Commands.cs
- Projects/Scripts/Commands/LocationCommand.cs
It was a bit annoying trying to get the XYZ location within the environment. This command will place a temporary graphic on any environment tile while also stating its XYZ position. It will also display a label on any item or mobile targeted displaying their position as well. Can be used with the `[multi` command.
Aliases: `[location`, `[loc`, `[pos`
> Adds a new [location command for easy display of target XYZ

- Directory.Build.props
- Projects/Server.Tests/packages.lock.json
- Projects/Server/Server.csproj
- Projects/Server/packages.lock.json
- Projects/UOContent.Tests/packages.lock.json
- Projects/UOContent/UOContent.csproj
- Projects/UOContent/packages.lock.json
- README.md
Adds specific support for:
- Ubuntu 20 won't be supported until the next .NET Core release
Note:
- NON-LTS versions of Linux WILL NOT be supported. There will be workarounds to install the native binaries. I'll add them to the wiki eventually. This includes (but not limited to): Ubuntu 14 (any version), Ubuntu 16.10, Ubuntu 18.10, Ubuntu 20.10, Ubuntu 21 (any version).
> Adds specific linux operating system support

- Projects/UOContent/Engines/Spawners/GenerateSpawners.cs
Fixes a crash when the file pattern potentially matches non-spawner json files in other directories, e.g. `[GenerateSpawners felucca.json` matching `Locations\felucca.json` and `Spawns\felucca.json` in the distro
> Fix GenerateSpawners command

- Projects/Server/Serialization/BufferedFileWriter.cs
Fixes an `ArgumentOutOfRange` exception when the `byte[]` value is bigger than the default buffer expansion size. This will increase buffer until the value fits.
> expand buffer until large enough for input bytes

- Projects/UOContent/Engines/ConPVP/DuelContext.cs
This PR fixes this problem. Strangely the build pipeline doesnt seem to have a problem with that, neither does Rider.
But when you run ./publish locally you get this.
```
D:\Code\_Extern\ModernUO\Projects\UOContent\Engines\ConPVP\DuelContext.cs(2073,39):
error CS8846: The switch expression does not handle all possible values of its input type (it is not exhaustive).
For example, the pattern '_' is not covered. However, a pattern with a 'when' clause might successfully match this value.
[D:\Code\_Extern\ModernUO\Projects\UOContent\UOContent.csproj]
```
> Fix switch-expression related error message

- Projects/Server.Tests/Network/Packets/Old/Outgoing/AccountPacketTests.cs
- Projects/Server.Tests/Network/PipeTests.cs
- Projects/Server/Buffers/CircularBufferReader.cs
- Projects/Server/Buffers/CircularBufferWriter.cs
- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Network/PacketHandlers.cs
- Projects/Server/Network/Packets/AccountPackets.cs
- Projects/Server/Network/Pipe.cs
> Updates networking to make pipe writer awaitable

- Projects/Server.Tests/Tests/Network/Packets/Outgoing/EquipmentPacketTests.cs
- Projects/Server.Tests/Tests/Network/Packets/Outgoing/EquipmentPackets.cs
- Projects/Server/Items/Containers.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/Packets/OutgoingEquipmentPackets.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Items/Armor/BaseArmor.cs
- Projects/UOContent/Items/Clothing/BaseClothing.cs
- Projects/UOContent/Items/Skill Items/Magical/Spellbook.cs
- Projects/UOContent/Items/Skill Items/Musical Instruments/BaseInstrument.cs
- Projects/UOContent/Items/Wands/BaseWand.cs
- Projects/UOContent/Items/Weapons/BaseWeapon.cs
- Projects/UOContent/Mobiles/Vendors/BaseVendor.cs
The packet now takes a string. The current implementation fixes a RunUO bug by passing in a crafter's RawName. Also fixes another bug where an empty, black, or null string will not send the `crafted by`.
Note for future changes:
* Add a field `CrafterName` so if a player changes their name, they cannot be tracked by the crafted property.
* Might want to optimize EquipUpdate later for broadcasting.
> Converts equipment packets

- Projects/Server/Network/Packets/IncomingMovementPackets.cs
- Projects/Server/Network/Packets/OutgoingMessagePackets.cs
> Fixes messages and removes movement console logs

- Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/Packets/IncomingAccountPackets.cs
- Projects/Server/Network/Packets/IncomingPlayerPackets.cs
- Projects/Server/Network/Packets/MobilePackets.cs
- Projects/UOContent/Commands/VisibilityList.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Multis/Boats/BaseBoat.cs
This PR supersedes changes in #337. That PR will need to be redone and broken out anyway.
> fix(net): Clean up for mobile packets

- Projects/Server/Buffers/CircularBuffer.cs
Fixes an issue where the circular buffer was out of bounds due to bad math.
Closes #343
> fix(core): Fixes wrong offset for CircularBuffer

- Projects/Server/Buffers/CircularBufferWriter.cs
- Projects/Server/Serialization/BufferWriter.cs
- Projects/Server/Serialization/IGenericWriter.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Mobiles/Townfolk/BaseEscortable.cs
This doesn't seem to address #349. That issue requires more investigation because I am not seeing where the issue would be.
Closes #347
Closes #322
> fix(core): Serialization issues

- Projects/Server/Serialization/BinaryFileWriter.cs
- Projects/Server/Serialization/BufferReader.cs
- Projects/Server/Serialization/BufferWriter.cs
- Projects/Server/World/World.cs
> fix(core): Fixes BufferWriter Seek and removes World.SaveBuffers

- Directory.Build.props
- Projects/Benchmarks/Packets/BenchmarkPacketBroadcast.cs
- Projects/Server.Tests/Tests/Network/Packets/Outgoing/EffectPacketTests.cs
- Projects/Server/Effects.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/PacketUtilities.cs
- Projects/Server/Network/Packets/OutgoingEffectPackets.cs
- Projects/Server/Network/Packets/OutgoingEntityPackets.cs
- Projects/Server/Network/Packets/OutgoingItemPackets.cs
- Projects/Server/Network/Packets/OutgoingMessagePackets.cs
- Projects/Server/Network/Packets/OutgoingMobilePackets.cs
- Projects/Server/Sector.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Commands/Handlers.cs
- Projects/UOContent/Commands/VisibilityList.cs
- Projects/UOContent/Engines/Doom/LeverPuzzle/LeverPuzzleController.cs
- Projects/UOContent/Engines/MLQuests/Mobiles/SirHelper.cs
- Projects/UOContent/Engines/Party/Party.cs
- Projects/UOContent/Items/Games/BaseBoard.cs
- Projects/UOContent/Items/Misc/Blocker.cs
- Projects/UOContent/Items/Misc/LOSBlocker.cs
- Projects/UOContent/Misc/Guild.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
> fix(core): Adds SkipLocalsInitAttribute support, optimizes broadcasted packets

- Directory.Build.props
- Projects/Server.Tests/Server.Tests.csproj
- Projects/Server.Tests/Tests/Buffers/SpanWriterTests.cs
- Projects/Server/Buffers/CircularBufferReader.cs
- Projects/Server/Buffers/CircularBufferWriter.cs
- Projects/Server/Buffers/SpanReader.cs
- Projects/Server/Buffers/SpanWriter.cs
- Projects/UOContent.Tests/UOContent.Tests.csproj
- Projects/UOContent/Gumps/Guilds/New Guild System/WarDeclarationGump.cs
- Projects/UOContent/Gumps/Props/SetPoint2DGump.cs
- Projects/UOContent/Gumps/Props/SetPoint3DGump.cs
- Projects/UOContent/Gumps/Props/SetTimeSpanGump.cs
- Projects/UOContent/Items/Skill Items/Specialized/GlassblowingBook.cs
- Projects/UOContent/Items/Skill Items/Specialized/MasonryBook.cs
- Projects/UOContent/Items/Skill Items/Specialized/SandMiningBook.cs
- Projects/UOContent/Items/Special/SoulStone.cs
- Projects/UOContent/Mobiles/Monsters/ML/Humanoid/Magic/MLDryad.cs
- Projects/UOContent/UOContent.csproj
SpanWriter now has an argument that allows it to be resizable.
```cs
public SpanWriter(Span<byte> initialBuffer, bool resize = false)
public SpanWriter(int initialCapacity, bool resize = false)
```
If a SpanWriter is set to be resizable, or given an initial capacity instead of a buffer, it must be disposed:
```cs
public static void SomeMethod()
{
using var writer = new SpanWriter(stackalloc byte[512], true);
// stuff
// Automatic Dispose of writer
}
```
This is because the SpanWriter uses `ArrayPool<byte>.Shared` _rented buffers_ to resize. If the writer is not disposed, those buffers will never be reused resulting in a _memory leak_.
It is possible that the SpanWriter will outright ditch the initial buffer if resize is set to true and growing is needed. To check/account for that we can …
> feat(core): Makes spanwriter resizable

- Projects/Server/Buffers/SpanWriter.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Network/Packets/IncomingEntityPackets.cs
- Projects/Server/ObjectPropertyList.cs
- Projects/UOContent/Items/Misc/Corpses/Corpse.cs
- Projects/UOContent/Multis/HouseFoundation.cs
> fix(core): Fixes OPL packets

- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Network/PacketHandler.cs
- Projects/Server/Network/Packets/IncomingAccountPackets.cs
- Projects/Server/Network/Packets/IncomingEntityPackets.cs
- Projects/Server/Network/Packets/IncomingExtendedCommandPackets.cs
- Projects/Server/Network/Packets/IncomingHousePackets.cs
- Projects/Server/Network/Packets/IncomingItemPackets.cs
- Projects/Server/Network/Packets/IncomingMessagePackets.cs
- Projects/Server/Network/Packets/IncomingMobilePackets.cs
- Projects/Server/Network/Packets/IncomingMovementPackets.cs
- Projects/Server/Network/Packets/IncomingPackets.cs
- Projects/Server/Network/Packets/IncomingPlayerPackets.cs
- Projects/Server/Network/Packets/IncomingTargetingPackets.cs
- Projects/Server/Network/Packets/IncomingVendorPackets.cs
- Projects/UOContent/Engines/Chat/Chat.cs
- Projects/UOContent/Engines/MLQuests/Gumps/RaceChangeGump.cs
- Projects/UOContent/Items/Books/BaseBook.cs
- Projects/UOContent/Items/Bulletin Boards/BulletinBoard.cs
- Projects/UOContent/Items/Games/Mahjong/MahjongPacketHandlers.cs
- Projects/UOContent/Items/Maps/MapItem.cs
- Projects/UOContent/Misc/HardwareInfo.cs
- Projects/UOContent/Multis/HouseFoundation.cs
- Projects/UOContent/Network/ProtocolExtensions.cs
- Projects/UOContent/Skills/Tracking/Tracking.cs
> fix(core): Removes 6017 handler

- Projects/Server.Tests/Tests/Collections/OrderedHashSetTests.cs
- Projects/Server/Collections/HashHelpers.cs
- Projects/Server/Collections/OrderedHashSet.cs
TODO:
Optimized the OrderedHashSet. See this:
* https://github.com/dotnet/runtime/issues/10050
Looks like the OrderedDictionary that I based this structure from was not updated.
See the source for diffing:
https://github.com/dotnet/runtime/blob/master/src/libraries/System.Private.CoreLib/src/System/Collections/Generic/HashSet.cs
Difference between a HashSet and an OrderedHashSet is updating the indexes of the entries after fixing the chain to preserve insertion order.
> fix(core): Adds ability to store null value in ordered hash set

- Projects/Server/Network/Packets/IncomingAccountPackets.cs
Allows for `EventSink.InvokeGameLogin` to set a custom packet encoder.
> fix(network): Adds setting NetState.PacketEncoder only if not null

- Projects/UOContent/Mobiles/Vendors/GenericBuy.cs
Notes: I broke up the deletion here because I didn't want to have to clear the mobiles list and trim excess. It is easier to just build a list of objects to delete and give the display cache a new list.
Closes #470
> fix(vendors): Fixes DisplayCache deserialization

- docs/quick-start.md
Current documentation incorrectly states that to run **ModernUO** you must use the ``./dotnet ModernUO.dll``.
This is untrue, since ``./dotnet`` will treat this as an instruction to execute the ``dotnet`` file in current context. This is true for the following shell types: **zsh** (Mac OS X Default), **bash** (Linux default), **sh** (Linux default on minimal distributions).
This small PR fixes this inconsistency.
> Modified quick-start to correctly invoke dotnet in *Nix

- Projects/Server/IAccount.cs
- Projects/Server/Network/Pipe.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/Persistence.cs
- Projects/Server/World/EntityPersistence.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Accounting/AccountComment.cs
- Projects/UOContent/Accounting/AccountTag.cs
- Projects/UOContent/Accounting/Accounts.cs
If you get a compile error due to `Persistence.Serialize`, you must switch to `GenericPersistence`.
World serialization is now broken up into two phases, Serialization (to memory), and Snapshotting (to disk).
Look at `UOContent/Accounting/Accounts.cs` as an example. Contact us on [discord](https://discord.gg/NUhe7Pq9gF) for help.
> fix(serialization): Updates serialization flow & fixes serializing accounts

- Projects/Server/Commands.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/IPLimiter.cs
- Projects/UOContent/Commands/Generic/Commands/BaseCommand.cs
- Projects/UOContent/Commands/Object Creation/Decorate.cs
- Projects/UOContent/Commands/Object Creation/DecorateMag.cs
- Projects/UOContent/Commands/Properties.cs
- Projects/UOContent/Engines/Harvest/Core/HarvestDefinition.cs
- Projects/UOContent/Engines/ML Quests/MLQuest.cs
- Projects/UOContent/Engines/Spawners/EditSpawnCommand.cs
- Projects/UOContent/Engines/Spawners/GenerateSpawners.cs
- Projects/UOContent/Engines/Spawners/RespawnCommand.cs
- Projects/UOContent/Engines/Spawners/SpawnPropsGump.cs
- Projects/UOContent/Engines/Spawners/SpawnPropsGumpCommand.cs
- Projects/UOContent/Gumps/Props/GlobalPropsGump.cs
- Projects/UOContent/Gumps/Props/PropsConfig.cs
- Projects/UOContent/Gumps/Props/PropsGump.cs
- Projects/UOContent/Gumps/Props/SetBodyGump.cs
- Projects/UOContent/Gumps/Props/SetCustomEnumGump.cs
- Projects/UOContent/Gumps/Props/SetGump.cs
- Projects/UOContent/Gumps/Props/SetListOptionGump.cs
- Projects/UOContent/Gumps/Props/SetObjectGump.cs
- Projects/UOContent/Gumps/Props/SetObjectTarget.cs
- Projects/UOContent/Gumps/Props/SetPoint2DGump.cs
- Projects/UOContent/Gumps/Props/SetPoint3DGump.cs
- Projects/UOContent/Gumps/Props/SetTimeSpanGump.cs
- Usage: `[global editspawner <type> <arguments> set <properties>`
- This command replaces the arguments (optional) and properties of the affected spawners for that type
- Usage: `[area spawnprops`
- This command brings up a gump to modify targeted spawners based on the targeted entity.
- To do this, the props/values are copied and then used to construct a properties list for the spawner entry.
Closes #531
> feat(spawners): Adds Respawn, EditSpawner, and SpawnProps commands

- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/World/EntityPersistence.cs
Example:
```cs
namespace Server
{
public static class ExampleSystem
{
public static void Configure()
{
GenericPersistence.Register("ExampleSystem", Serialize, Deserialize);
}
public static void Serialize(IGenericWriter writer)
{
// Do serialization here
writer.WriteEncodedInt(0); // version
}
public static void Deserialize(IGenericReader reader)
{
// Do deserialization here
var version = reader.ReadEncodedInt();
}
}
}
```
> fix(core): Fixes generic persistence

- Projects/Server/Network/NetState/NetState.cs
Thanks to @jaedan for this fix.
> fix(core): Fixes netstate dropping late

- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/NetState/NetState.cs
Setting `m.NetState = null` from a different thread caused `Mobile.Delta` and `NetState.Send` to run from a separate thread which cannot happen.
> fix(core): Fixes threading issue and adds threadguard

- Projects/UOContent/Multis/Boats/BaseBoat.cs
- Projects/UOContent/Multis/Boats/BoatPackets.cs
TODO: Implement packet of packets for displaying boats
Notes:
- In the future, we will have z-sorted lists, and we can iterate from highest to lowest, which will avoid the llama problem naturally.
> fix(boats): Fixes boat movement issues

- Projects/Server/Configuration/ServerConfiguration.cs
Expansion was not being set when reading ServerConfiguration, causing it to be always `Expansion.None` and many features to not work.
> fix: Configure expansion from config

- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Engines/CannedEvil/ChampionSpawn.cs
- Projects/UOContent/Engines/ML Quests/Objectives/GainSkillObjective.cs
- Projects/UOContent/Items/Addons/SHTeleporter.cs
- Projects/UOContent/Items/Special/SoulStone.cs
- Projects/UOContent/Items/Special/Special Scrolls/ScrollofTranscendence.cs
- Projects/UOContent/Spells/Bushido/SamuraiSpell.cs
Note:
- I am not going to go through the entire code base and fix rounding errors for doubles. It is true that most of the variables _should have been integers anyway_ and then divided into the appropriate value w/ truncation when displayed. I'll leave that up to others to make PRs to fix if they feel the need.
> fix(core): Fixes displaying some doubles

- Projects/Server/Attributes.cs
- Projects/Server/Skills.cs
- Projects/UOContent/Engines/ConPVP/Arena.cs
- Projects/UOContent/Engines/ConPVP/Ladder.cs
- Projects/UOContent/Engines/ConPVP/Preferences.cs
- Projects/UOContent/Engines/ConPVP/Tournament.cs
- Projects/UOContent/Engines/ConPVP/TournamentController.cs
- Projects/UOContent/Gumps/Props/PropsGump.cs
- Projects/UOContent/Items/Armor/BaseArmor.cs
- Projects/UOContent/Items/Armor/Glasses/ElvenGlasses.cs
- Projects/UOContent/Items/Clothing/BaseClothing.cs
- Projects/UOContent/Items/Jewels/BaseJewel.cs
- Projects/UOContent/Items/Quivers/BaseQuiver.cs
- Projects/UOContent/Items/Skill Items/Magical/Spellbook.cs
- Projects/UOContent/Items/Talismans/BaseTalisman.cs
- Projects/UOContent/Items/Weapons/BaseWeapon.cs
Example of how to make this work:
```cs
[CommandProperty(AccessLevel.GameMaster, canModify: true)]
public AosWeaponAttributes WeaponAttributes { get; private set; }
```
This fix is necessary because in release mode the optimizer will sometimes _entirely remove the setter_ because it knows it can do something that is more efficient _when the property setter is private_. RunUO got around this by declaring a public setter explicitly that _was empty_.
> fix(core): Fixes some properties that cannot be modified ingame

- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.DeserializeMethod.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.MetadataTypes.cs
- Projects/Server/Serialization/AfterDeserialization.cs
Added the ability to execute arbitrary code after deserialization.
Example, let's say you want to delete an item after you deserialize it:
```cs
[AfterDeserialization]
private void OnAfterDeserialization()
{
Delete();
}
```
Generates this:
```cs
public override void Deserialize(IGenericReader reader)
{
base.Deserialize(reader);
var version = reader.ReadEncodedInt();
Timer.DelayCall(OnAfterDeserialization);
}
```
> feat(codegen): Adds AfterDeserialization support

- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.MetadataTypes.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Property.cs
- Projects/Server/Serialization/InvalidatePropertiesAttribute.cs
Adds invalidate properties to code genned fields.
Example:
```cs
[InvalidateProperties]
[EncodedInt]
private int _number; // Cliloc
```
Generates:
```cs
public int Number
{
get => _number;
set
{
if (value != _number)
{
_number = value;
((ISerializable)this).MarkDirty();
InvalidateProperties();
}
}
}
```
> feat(codegen): Adds InvalidateProperties

- Projects/SerializationGenerator/EntitySerializationGenerator.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.DeserializeMethod.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.SerializeMethod.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/ArrayMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/HashSetMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/KeyValuePairMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/ListMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/SerializableMetadata.cs
- Projects/SerializationGenerator/SerializableMigration/SerializableMigrationRulesEngine.cs
- Projects/SerializationGenerator/SerializableMigration/SerializableProperty.cs
- Projects/SerializationGenerator/SerializableMigration/SerializablePropertyComparer.cs
- Projects/SerializationGenerator/SerializerSyntaxReceiver.cs
- Projects/SerializationGenerator/SourceGeneration/SourceGeneration.Namespace.cs
- Projects/Server/Serialization/SerializableFieldAttribute.cs
- Projects/Server/Serialization/SerializableFieldAttributeAttribute.cs
Example:
```cs
private int _myExistingField;
[SerializableField(1)]
public int MyExistingProperty
{
get => _myExistingField;
set
{
if (value == 0)
{
Parent = null;
}
if (value != _myExistingField)
{
((ISerializable)this).MarkDirty();
_myExistingField = value;
}
}
}
```
> feat(codegen): Adds opt-in with existing properties for sourcegen

- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Class.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.Property.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.SerialCtor.cs
- Projects/SerializationGenerator/SerializableEntityGeneration/SerializableEntityGeneration.SerializeMethod.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/PrimitiveTypeMigrationRule.cs
- Projects/SerializationGenerator/SourceGeneration/SourceGeneration.Property.cs
- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/ISerializable.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Automatically opts-out `Item/Mobile/Guild/Accounts` from dirty checking with a new property `UseDirtyChecking`
- Codegen now enables `UseDirtyChecking` via getter. This requires that the property is `virtual` for derived types.
- Fixes `EncodedInt` being broken
- Fixes issues with new custom serializable types that are not derived from Item/Mobile/etc.
- Removes double dirty checking.
User created code:
```cs
using System;
namespace Server.Items
{
[Serializable(0)]
public partial class NewTestEntityObject : ISerializable
{
[EncodedInt]
[SerializableField(0)]
private int _someProperty;
public NewTestEntityObject()
{
SetTypeRef(GetType());
// Add to serial tracking like World.Item
/*
Serial = World.NewEntity;
World.AddEntity(this);
*/
}
[AfterDeserialization]
private void …
```
> fix(core): Fixes encoded int. Adds dirty checking opt-out

- Projects/SerializationGenerator/SerializableMigration/Rules/ArrayMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/HashSetMigrationRule.cs
- Projects/SerializationGenerator/SerializableMigration/Rules/ListMigrationRule.cs
- Projects/Server/Serialization/IGenericReader.cs
- Projects/Server/Server.csproj
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Migrations/Server.Accounting.Account.v2.json
- Projects/UOContent/UOContent.csproj
- It will be up to the user (for now) to null out empty lists using `[AfterDeserialization]`. Convenience may be added later.
- This was caused by a duplicate entry. Don't have protection against this _yet_.
> fix(core): Fixes various issues with codegen

- Directory.Build.props
- Projects/SerializationGenerator/SerializationGenerator.csproj
- Projects/SerializationSchemaGenerator/SerializationSchemaGenerator.csproj
- Projects/Server/Server.csproj
- Projects/UOContent/UOContent.csproj
**Note for Rider users** Code generation only works with Rider v2021.1+. For Rider 2021.1.x you must set a global msbuild attribute so that the IDE can recognize generated code after building. JetBrains claims this will be fixed in Rider 2021.2.
**Rider 2021.1 Required Setting for Code Generation**
**Note for VS 2019+ users**: Code generation requires completely cleaning your solution, doing a full build, closing VS 2019, and then opening the solution. This is a known issue and there are no plans to fix this multiple restart requirement for VS 2022 at this time.
> fix(build): Fixes building with VS 2019 16.10+

- Projects/SerializationGenerator/SerializableMigration/Rules/TimerMigrationRule.cs
- Projects/Server/NativeReader.cs
When a timer is null, the code generator will use `TimeSpan.MinValue` as the delay.
> fix(codegen): Fixes codegenning timers when they are null.

- Distribution/Data/assemblies.json
- Projects/Server/AssemblyHandler.cs
- Projects/Server/Configuration/ServerConfiguration.cs
- Projects/Server/Configuration/ServerSettings.cs
- Projects/Server/Main.cs
* `AssemblyHandler.Assemblies` will now only contain assemblies listed in `assemblies.json`
* `assemblies.json` has been updated to only contain asssemblies directly loaded by the server. Namely, only `UOContent.dll`.
* Specifically assemblies loaded by assemblies.json are subject to check for `Configure` and `Initialize` methods.
* `modernuo.json` now has a new property called `assemblyDirectories`. This will be automatically set to `Distribution/Assemblies` (absolute path on your machine).
* You can add more directories to this list.
* All assemblies in assemblies.json _AND_ dependents of any assembly will be searched for in the directories specified by `assemblyDirectories`.
> fix: Fixes assembly loading.

- Projects/Server/Items/Container.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Network/Packets/OutgoingItemPackets.cs
- Projects/UOContent/Gumps/AdminGump.cs
- Projects/UOContent/Items/Addons/AddonComponent.cs
- Projects/UOContent/Items/Addons/AddonContainerComponent.cs
- Projects/UOContent/Items/Addons/ArcaneBookshelfEastAddon.cs
- Projects/UOContent/Items/Addons/BaseAddonContainer.cs
- Projects/UOContent/Items/Containers/Container.cs
* Fixes tooltip for container furniture so it works. This doesn't work on ClassicUO.
* Fixes double click opening container furniture by double clicking the addon component.
* Fixes the context menu not showing up sometimes on the addon piece.
> fix: Uses client bug to make addon containers work

- Projects/Server/Timer/Timer.DelayCall.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Timer/Timer.cs
1. Stopping a different timer, on the same slot as the timer being executed during OnTick
* Adds a check for the timer wheel currently being executed and does not detach the timer on Stop().
1. Timers are added to the current slot if they need 4095 slots, before the chain is fully detached/executed
* Removes all chains that will be executed from the timer wheel before executing.
Closes #781
> fix: Fixes timer wheel edge cases

- Projects/Server/AssemblyHandler.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Text/StringHelpers.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Utilities/PathUtility.cs
- Projects/Server/Utilities/Utility.cs
- Projects/Server/World/EntityPersistence.cs
- Projects/Server/World/World.cs
- Projects/UOContent.Tests/Fixtures/ServerFixture.cs
- Projects/UOContent/Accounting/Account.Migrations.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Compression/TarArchive.cs
- Projects/UOContent/Compression/ZstdArchive.cs
- Projects/UOContent/Engines/Spawners/Commands/ConvertPremiumSpawners.cs
- Projects/UOContent/Engines/Spawners/Commands/ExportSpawnersCommand.cs
- Projects/UOContent/Misc/CrashGuard.cs
- Projects/UOContent/World Saves/AutoArchive.cs
* Makes EnsureDirectory properly work for relative and absolute paths
* Adds a `PathUtility.GetFullPath` which returns full paths for relative paths to `Core.BaseDirectory`. If the path is absolute, it will return as-is.
* Moves EnsureDirectory to `PathUtility`. So `ScriptsHandler.EnsureDirectory` and `AssemblyHandler.EnsureDirectory` are now `PathUtility.EnsureDirectory`
* Fixes crash guard so that it copies accounts properly.
* Changes world save and auto archive to use a random folder name inside of the temp folder.
If the system volume is slow (not SSD), it is highly recommended that the following settings are _added_ to modernuo.json:
```json
{
...
"settings": {
...
"world.tempSavePath": "path to temporary folder on fast hard drive",
"autoArchive.tempArchivePath": "path to temporary …
```
> fix: Cleans up file system paths and archiving

- Projects/Server/Buffers/CircularBuffer.cs
- Projects/Server/Buffers/CircularBufferReader.cs
- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Text/HexStringConverter.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Network/NetworkCommands.cs
`[packetlogging on` and target the user.
Supports command modifiers such as:
`[online packetlogging on where accesslevel = player`
Logs are saved in `path/<ip address>/packets.log`. It is a simple append-format log with no date splitting.
> fix: Adds packet logging

- Projects/SerializationGenerator/SerializableMigration/Rules/PrimitiveUOTypeMigrationRule.cs
- Projects/SerializationGenerator/SourceGeneration/SymbolMetadata/SymbolMetadata.UO.cs
- Projects/Server/Collections/BitArray.cs
- Projects/Server/Collections/CollectionThrowStrings.cs
- Projects/Server/Serialization/BinaryFileReader.cs
- Projects/Server/Serialization/BufferReader.cs
- Projects/Server/Serialization/BufferWriter.cs
- Projects/Server/Serialization/IGenericReader.cs
- Projects/Server/Serialization/IGenericWriter.cs
* Adds a custom BitArray class with the following added features:
* ctor for creating BitArray against read only span
* ctor for creating BitArray against BinaryReader
* CopyTo to copy a BitArray to a Span
* Adds BitArray to UO Primitive serialization so it can be codegenned.
See the following:
https://github.com/dotnet/runtime/issues/30821
https://github.com/dotnet/runtime/issues/62680
> fix: Adds BitArray support with codegen

- Projects/UOContent/Accounting/AccountHandler.cs
- Projects/UOContent/Misc/AccountPrompt.cs
- Projects/UOContent/Misc/PacketThrottles.cs
- Projects/UOContent/Misc/ServerAccess.cs
Adds a configuration file to specify protected accounts:
_Distribution/Configuration/server-access.json_
```json
{
"newPasswordOnReset": false,
"protectedAccounts": ["admin"]
}
```
Protected accounts are unbanned and reset to `AccessLevel.Owner` upon login.
The option `newPasswordOnReset` will create a new password for a protected account if it needs to be reset. The password is a random GUID and logged to the console.
_**Note:**_ If your player character was accidentally modified, simply make a new character to fix the old one.
> fix: Adds server access with protected accounts

- Directory.Build.props
Fixes culture not found exception with global invariance set through builds in VS.
Closes #920 as a more proper fix.
> fix: Fixes en-us forced pricing culture throwing when bulding in VS

- Projects/Server/Network/ContainerGridPacketHandler.cs
- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Network/PacketHandler.cs
- Projects/Server/Network/Packets/IncomingAccountPackets.cs
- Projects/Server/Network/Packets/IncomingEntityPackets.cs
- Projects/Server/Network/Packets/IncomingExtendedCommandPackets.cs
- Projects/Server/Network/Packets/IncomingHousePackets.cs
- Projects/Server/Network/Packets/IncomingItemPackets.cs
- Projects/Server/Network/Packets/IncomingMessagePackets.cs
- Projects/Server/Network/Packets/IncomingMobilePackets.cs
- Projects/Server/Network/Packets/IncomingMovementPackets.cs
- Projects/Server/Network/Packets/IncomingPackets.cs
- Projects/Server/Network/Packets/IncomingPlayerPackets.cs
- Projects/Server/Network/Packets/IncomingTargetingPackets.cs
- Projects/Server/Network/Packets/IncomingVendorPackets.cs
- Projects/UOContent/Engines/Chat/ChatPackets.cs
- Projects/UOContent/Engines/ML Quests/Gumps/RaceChangeGump.cs
- Projects/UOContent/Engines/UltimaStore/UltimaStorePackets.cs
- Projects/UOContent/Items/Books/BookPackets.cs
- Projects/UOContent/Items/Bulletin Boards/BulletinBoardPackets.cs
- Projects/UOContent/Items/Games/Mahjong/MahjongPackets.cs
- Projects/UOContent/Items/Maps/MapItemPackets.cs
- Projects/UOContent/Misc/HardwareInfo.cs
- Projects/UOContent/Misc/PacketThrottles.cs
- Projects/UOContent/Multis/Houses/HouseFoundation.cs
- Projects/UOContent/Network/ConnectUO.cs
- Projects/UOContent/Network/MapUO.cs
- Projects/UOContent/Network/ProtocolExtensions.cs
- Projects/UOContent/Network/UOGateway.cs
- Projects/UOContent/Skills/Tracking/Tracking.cs
Fixes an issue with DropReq where an old client was sending in 14 bytes, but the server was expecting 15 bytes.
To fix this we introduced a new packet handler, `ContainerGridPacketHandler` and changed the code to determine the length of the packet dynamically using `GetLength(NetState)`.
Also fixed throttling so dropped packets are properly skipped.
> fix: Fixes packet length checks

- Projects/Benchmarks/Benchmarks/Collections/BenchmarkPooledRefQueue.cs
- Projects/Benchmarks/Benchmarks/Collections/BenchmarkSTArray.cs
- Projects/Benchmarks/Program.cs
- Projects/Server.Tests/Tests/Buffers/STArrayPoolTests.cs
- Projects/Server/Collections/PooledRefQueue.cs
- Projects/Server/Collections/STArrayPool.cs
- Projects/Server/Maps/Map.cs
- Projects/UOContent/Mobiles/Monsters/Misc/Melee/BladeSpirits.cs
- Projects/UOContent/Mobiles/Monsters/Misc/Melee/EnergyVortex.cs
Adds a single threaded array pool that works exactly the same as `ArrayPool<T>.Shared`.
The `STArrayPool<T>.Shared` can only be used on a single thread, the main game thread of the server.
Note: Unlike the built-in array pool, there is no hook into the _GC Gen 2_. This means to relieve potentially high memory pressure, `ArrayPool<T>.Shared.Trim()` must be called. The pool will only release arrays _after two successive calls within 10 seconds or longer_. If the server is at less than 70% total memory usage, or the server is not going to use this pool for something egregious, then don't bother ever calling Trim().
Closes #683
> feat: Adds a single threaded array pool

- Projects/Server/Buffers/STArrayPool.cs
- Projects/Server/GarbageCollection/Gen2GcCallback.cs
Adds. Gen2Callback for STArrayPool so it can purge the internal array stacks properly. This only happens if significant timed has passed, 2 Gen 2's have been run, and memory pressure exceeds a threshold.
> fix: Adds Gen2 callback for each STArrayPool

- Projects/Benchmarks/Benchmarks/Timers/BenchmarkTimerExecutions.cs
- Projects/Benchmarks/Benchmarks/Timers/BenchmarkTimerInserts.cs
- Projects/Benchmarks/Benchmarks/Timers/RUOTimer.cs
- Projects/Benchmarks/Program.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
Adds benchmarks for RUO vs MUO timers:
For both tests about 125us is spent creating the objects.
```
|          Method |     Mean |    Error |    StdDev |   Gen 0 |  Gen 1 | Allocated |
|---------------- |---------:|---------:|----------:|--------:|-------:|----------:|
| RUOTimerInserts | 888.6 us | 47.70 us | 137.64 us | 11.7188 | 5.8594 |    102 KB |
| MUOTimerInserts | 157.0 us |  3.01 us |   2.81 us | 11.4746 | 6.1035 |     94 KB |
```
This test is partially synthetic since the RUO thread is waiting for the timers to be inserted and then executed all at once.
There is no real thread contention. With an organic test, the times fluctuated wildly up to 25ms.
```
|             Method |       Mean |     Error |    StdDev |   Gen 0 |  Gen 1 |  Gen 2 | Allocated |
|------------------- …
```
> chore: Adds benchmarks for RunUO vs ModernUO Timers

- Projects/Server/Timer/Timer.TimerWheel.cs
Resolves an issue where only the root timer was counted in the ring slot.
> fix: Properly count timers for DumpInfo

- Projects/Server/Main.cs
- Projects/Server/MultiData.cs
* Changes reading multi.mul/multi.idx so it is loaded entirely during bootup.
* Fixes finding files in Linux.
* Fixes handling HS format.
* Removes verdata support.
ModernUO will still have issues if there is a multi.mul that is pre-HS loaded when it detects a client that is 7.0.9+.
> fix: Fixes loading multi where client is missing

- Projects/Server.Tests/Tests/Collections/BitArrayTests.cs
- Projects/Server/Collections/BitArray.cs
- Projects/Server/Serialization/BufferReader.cs
- Projects/Server/Serialization/BufferWriter.cs
Fixes bit array serialization. This may cause objects that were serialized by bit array to fail to deserialize. I am sorry, please accept my condolences. It is probably easiest to just delete those objects. If it becomes a major problem, contact me and I'll help with a hacky per-case solution.
> fix: Fixes BitArray serialization

- Projects/Server/World/EntityPersistence.cs
Fixes an issue where 0 byte objects are improperly deserialized. They should not be deserialized at all and instead deleted.
> fix: Fixes pool of acid and other empty serializations

- Projects/Server/Network/Packets/IncomingItemPackets.cs
Removing DropReq6017 method, is not being use since the following function takes care of the packet Length change.
IncomingPackets.Register(new ContainerGridPacketHandler(0x08, 14, true, DropReq));
> Removed DropReq6017

- Projects/Server/Buffers/ValueStringBuilder.cs
- Projects/Server/Main.cs
Added multithread optional flag to ValueStringBuilder for multithread contexts.
Enabled new flag for VerifyType method.
Resolves #1032
> fix: Adds multithread optional flag to ValueStringBuilder

- Projects/Server.Tests/Tests/Buffers/STArrayPoolTests.cs
- Projects/Server.Tests/Tests/Localization/LocalizationEntryTests.cs
- Projects/Server/Buffers/PooledArraySpanFormattable.cs
- Projects/Server/Buffers/STArrayPool.cs
- Projects/Server/Localization/Localization.cs
- Projects/Server/Localization/LocalizationEntry.cs
Adds an optimized formatter for localization. Example:
```cs
string localizationText = Localization.Format(1050039, "enu", $"{m_Amount}\t{LabelNumber:#}");
```
Fixes #1044
> fix: Adds optimized formatter for clilocs

- Projects/Server.Tests/Tests/SerialTests.cs
- Projects/Server/Guild.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serial.cs
- Projects/UOContent/Accounting/AccountHandler.cs
- Projects/UOContent/Commands/Generic/Commands/Interface.cs
- Projects/UOContent/Commands/Logging.cs
- Projects/UOContent/Commands/Object Creation/Add.cs
- Projects/UOContent/Gumps/ClientGump.cs
- Projects/UOContent/Gumps/Props/PropsGump.cs
- Projects/UOContent/Items/Armor/BaseArmor.cs
- Projects/UOContent/Items/Clothing/BaseClothing.cs
- Projects/UOContent/Items/Jewels/BaseJewel.cs
- Projects/UOContent/Items/Skill Items/Magical/Spellbook.cs
- Projects/UOContent/Items/Weapons/BaseWeapon.cs
- Projects/UOContent/Misc/AOS.cs
- Projects/UOContent/Misc/CrashGuard.cs
Updates `Serial` so string interpolation is automatic and optimized (no allocation):
```cs
$"{serial}" // 0x12345678
```
This means you don't have to do the following:
```cs
$"{serial.Value:X}"
```
Also Serial will respect custom formatters. For example if you want a normal integer representation:
```cs
$"{serial:##}"
```
> fix: Adds ISpanFormattable support to Serial

- Projects/UOContent/Engines/Spawners/BaseSpawner.cs
- Projects/UOContent/Engines/Spawners/Commands/ExportSpawnersCommand.cs
- Projects/UOContent/Engines/Spawners/SpawnerGump.cs
This update changes the default RunUO SpawnerGump's overall look and feel and expands slightly some functionality. Inspired by the XmlSpawner gump.
1. The name of the spawner is displayed
2. This displays the total current spawn with the current allowed max spawn
3. Cleans up the display of the current count and the max count
4. The ability to turn on/off the spawner
5. Several changes to buttons 
- Simple Save and Cancel instead of Okay, Cancel and Apply.
- Props button to display spawner properties
- Goto button to teleport to the spawner
- Reset button that will clear all the spawned mobs and turn off the spawner
- Repositioned the buttons to make a little more sense
6. The sum of all the max spawn values per entry, from all pages
> Visual and functional updates to SpawnerGump

- Projects/UOContent/Engines/Craft/Core/CraftItem.cs
- Projects/UOContent/Engines/Craft/Core/Recipes.cs
- Projects/UOContent/Engines/Craft/DefAlchemy.cs
- Projects/UOContent/Engines/Craft/DefBlacksmithy.cs
- Projects/UOContent/Engines/Craft/DefBowFletching.cs
- Projects/UOContent/Engines/Craft/DefCarpentry.cs
- Projects/UOContent/Engines/Craft/DefCartography.cs
- Projects/UOContent/Engines/Craft/DefCooking.cs
- Projects/UOContent/Engines/Craft/DefGlassblowing.cs
- Projects/UOContent/Engines/Craft/DefInscription.cs
- Projects/UOContent/Engines/Craft/DefMasonry.cs
- Projects/UOContent/Engines/Craft/DefTailoring.cs
- Projects/UOContent/Engines/Craft/DefTinkering.cs
The `[LearnAllRecipes` command does not work unless all of the crafting systems are initialized. This is a really old bug that went completely unnoticed.
Since memory and speed is not really a concern during initialization of the server, this change initializes all crafting systems before the world is loaded.
> fix: Fixes LearnAllRecipes

- Projects/UOContent/Mobiles/Townfolk/TownCrier.cs
That list being null on a fresh town crier would cause this error on MUO and forces the client to disconnect.
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Server.Mobiles.TownCrier.GetRandomEntry() in D:\Programming\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 382
at Server.Mobiles.TownCrierGump..ctor(Mobile from, ITownCrierEntryList owner) in D:\Programming\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 210
at Server.Mobiles.TownCrier.OnDoubleClick(Mobile from) in D:\Programming\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 467
at Server.Mobile.Use(Mobile m) in D:\Programming\ModernUO\Projects\Server\Mobiles\Mobile.cs:line 4885
at Server.Network.IncomingEntityPackets.UseReq(NetState state, …
```
> fix: init Entries to prevent client crash

- Projects/Server/AssemblyHandler.cs
- Projects/Server/Items/Item.cs
- Projects/Server/MultiData.cs
- Projects/UOContent/Engines/Craft/Core/CraftGumpItem.cs
- Projects/UOContent/Engines/Craft/Core/CraftItem.cs
- Projects/UOContent/Engines/Craft/Core/CraftRes.cs
- Projects/UOContent/Engines/Craft/Core/CraftSystem.cs
- Projects/UOContent/Engines/Craft/DefAlchemy.cs
- Projects/UOContent/Engines/Craft/DefBlacksmithy.cs
- Projects/UOContent/Engines/Craft/DefCooking.cs
- Projects/UOContent/Engines/Craft/DefInscription.cs
- Projects/UOContent/Engines/Craft/DefTailoring.cs
> fix: Delays getting item id of craftables until they are needed

- Projects/UOContent/Items/Skill Items/Tools/BaseRunicTool.cs
* Weapons sometimes dropping a property when a slayer group with no lesser slayers is rolled e.g. undead
> * Weapons sometimes dropping a property

- Projects/UOContent/Mobiles/Animals/Mounts/Ethereals.cs
- Projects/UOContent/Skills/SpiritSpeak.cs
- Projects/UOContent/Spells/Base/Spell.cs
- Projects/UOContent/Spells/Base/SpellState.cs
I've fixed the fizzle bug and done some refactoring of the code to avoid duplicating. 
There is one thing extra I have changed as well which might seem irrelevant, but I think it should still be changed:
* Instead of checking if someone is casting by: using State == SpellState.Casting
* I use the Spell.IsCasting bool which underneath does exactly the same check: State == SpellState.Casting
* The reason is that this bool is what's used by other parts of the server e.g. dont let someone move if they are casting.
* In the future if someone does a custom change like letting people use spirit speak whilst holding a spell, they will want to make changes to the Spell.IsCasting bool so that the other parts are also checking if they are casting spirit speak
> * Fix players casting is sometimes not disturbed

- Projects/UOContent/Mobiles/Townfolk/TownCrier.cs
- Double clicking a town crier as staff results in server crash every time. This extra null check prevented that in testing.
`System.NullReferenceException: Object reference not set to an instance of an object.
at Server.Mobiles.TownCrier.GetRandomEntry() in C:\Users\Dan\Desktop\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 386
at Server.Mobiles.TownCrierGump..ctor(Mobile from, ITownCrierEntryList owner) in C:\Users\Dan\Desktop\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 210
at Server.Mobiles.TownCrier.OnDoubleClick(Mobile from) in C:\Users\Dan\Desktop\ModernUO\Projects\UOContent\Mobiles\Townfolk\TownCrier.cs:line 468
at Server.Mobile.Use(Mobile m) in C:\Users\Dan\Desktop\ModernUO\Projects\Server\Mobiles\Mobile.cs:line 4888
at …
> Town Crier Crash Fix

- Distribution/Data/expansion.json
- Projects/Server.Tests/Tests/Network/Packets/Outgoing/MobilePacketTests.cs
- Projects/Server/ExpansionInfo.cs
- Projects/Server/Network/Packets/OutgoingMobilePackets.cs
- Projects/UOContent/Assistants/AssistantProtocol.cs
Adds a mobile status version setting that can be changed per expansion.
Removes the mobile status version override from modernuo.json.
Gracefully downgrades the version if the client doesn't support it. (This heavily relies on expansion.json).
Note: This unfortunately tightly couples `ExpansionInfo.ID` to `Expansion`. We do this in other places, but long-term, we should probably come up with a better way to address expansions.
> fix: Adds expansion specific mobile status version

- Projects/UOContent/Items/Maps/TreasureMap.cs
Spawn TreasureChestDirt next to treasure location, not ontop of it. Else it will be found in the Map.CanFit() check and cancel the digging prcess with 503024 (You stop digging because something is directly on top of the treasure chest.)
> spawn TreasureChestDirt next to treasure location, not ontop of it

- Projects/UOContent/Spells/Base/SpellHelper.cs
As we see together a minor bug fix so that Mobile.GetDirectionTo() is only called when the target mobile is different from the current mobile
> fix: Casting changes player direction to Down

- Projects/Server/AssemblyHandler.cs
- Projects/Server/Configuration/ServerConfiguration.cs
Adds better error messaging for when the server cannot find a dependency. The most common error is MimeKit is missing because the assemblyDirectories field in modernuo.json does not have any valid paths.
> fix: Adds better error message for missing assemblies

- Projects/UOContent/Mobiles/AI/BaseAI.cs
min/max were calculated with this formula:
```cs
var min = delay * (9 / 10); // 13s at 1000 int, 33s at 400 int, 54s at <250 int
var max = delay * (10 / 9); // 16s at 1000 int, 41s at 400 int, 66s at <250 int
```
Because of int type:
- (9 / 10) is always 0
- (10 / 9) is always 1
Changed to milliseconds and removed the need of TimeSpan conversion
> BaseAI: Fix wrong min/max delay for detect hidden NPC ability

- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Accounts.cs
Note: Max() is not very fast because `Serial` is a struct, and we don't use int directly. This is ok since we really don't care about world loading performance.
> fix: Use the latest number for the next serial after world load.

- Projects/Server/Items/Item.cs
- Projects/UOContent/Items/Weapons/Abilities/Disarm.cs
- Projects/UOContent/Misc/Notoriety.cs
- Projects/UOContent/Mobiles/AI/BaseAI.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Spells/Base/SpellHelper.cs
- Projects/UOContent/Spells/Chivalry/CleanseByFire.cs
- Projects/UOContent/Spells/Eighth/AirElemental.cs
- Projects/UOContent/Spells/Eighth/EarthElemental.cs
- Projects/UOContent/Spells/Eighth/FireElemental.cs
- Projects/UOContent/Spells/Eighth/SummonDaemon.cs
- Projects/UOContent/Spells/Eighth/WaterElemental.cs
- Projects/UOContent/Spells/First/Clumsy.cs
- Projects/UOContent/Spells/First/Feeblemind.cs
- Projects/UOContent/Spells/First/Weaken.cs
- Projects/UOContent/Spells/Fourth/Curse.cs
- Projects/UOContent/Spells/Necromancy/Strangle.cs
- Projects/UOContent/Spells/Second/Agility.cs
- Projects/UOContent/Spells/Second/Cunning.cs
- Projects/UOContent/Spells/Second/Cure.cs
- Projects/UOContent/Spells/Second/Protection.cs
- Projects/UOContent/Spells/Second/Strength.cs
- Projects/UOContent/Spells/Sixth/MassCurse.cs
- Projects/UOContent/Spells/Third/Bless.cs
* items sometimes going to floor
* disarm broken
* monster summons do no dmg in tramm and cant attack monster summons in tramm
* innocent creatures killing each other
* 25% dmg boost to first attacker going to wrong player
* DamageStore comparer didnt work properly
* put into heat of battle when attacked by someone else
* summons wrong durations
* refreshing strangle and curse not working
* cure sending fail msg to wrong player
* protection spell broken
> fix: Fixes disarm, strangle, curse, summons, looting rights, creatures attacking, and items going to the floor

- Projects/UOContent/Mobiles/AI/BaseAI.cs
Hey @kamronbatman,
Previously the monster AcquireFocusMob() would ignore player summons which was being abused by casting energy vortexes etc. out of range, the monster would not detect any players around and enter idle mode and die easily to the EVs; "player versus engine". 
With this change the monster still tries to acquire players but falls back to a player summon target if no valid player targets can be found.
> Fix abusing summons offscreen

- Projects/Server/AssemblyHandler.cs
- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Container.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/AdhocPersistence.cs
- Projects/Server/Serialization/BinaryFileReader.cs
- Projects/Server/Serialization/BinaryFileWriter.cs
- Projects/Server/Serialization/BufferReader.cs
- Projects/Server/Serialization/BufferWriter.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/IGenericReader.cs
- Projects/Server/Serialization/IGenericWriter.cs
- Projects/Server/Serialization/ISerializable.cs
- Projects/Server/Serialization/Persistence.cs
- Projects/Server/Server.csproj
- Projects/Server/Utilities/HashUtility.cs
- Projects/Server/Utilities/Utility.cs
- Projects/Server/World/EntityPersistence.cs
- Projects/Server/World/EntitySpan.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Accounting/Accounts.cs
- Projects/UOContent/Items/Armor/Cloth/GargishClothKiltType2.cs
- Projects/UOContent/Mobiles/Monsters/Reptile/Magic/SkeletalDragon.cs
- Projects/UOContent/Spells/Chivalry/NobleSacrifice.cs
- version.json
* Improves type hashing by introducing xxHash3 (64bit)
* Removes individual `tdb` files in favor of a single `SerializedTypes.db` file. This file is only used to identify a type that is being deserialized, which doesn't exist.
* Adds duplicate type alias detection
* Adds `AssemblyHandler.FindTypeByHash`
View changed files whitespaces: https://github.com/modernuo/ModernUO/pull/1172/files?diff=split&w=1
The serialized types file is used to get back the original name of a type in case it no longer exists in code. This can easily be necessary if a class is renamed in code and no `TypeAlias` is provided.
byte[4] - version
byte[4] - count
--array--
byte[8] - xxHash
byte[1] - flag, 0 - null, 1 - not null
byte[n] - Full class name in UTF8
Serialized 500 Type fields. The 8192bytes comes from the …
> fix: Adds ReadType/Write(Type) and improves type referencing

- Projects/Server/Timer/Timer.DelayCall.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Timer/Timer.cs
* Fixes an edge case where a check to see if a timer was being executed resulted in it not being properly detached on stop. Fixed this by changing how we determine what timer is currently being executed.
* Adds execution count to #DEBUG_TIMERS so shards can get notified (rudimentarily for now) about sequentially executing long chains of timers.
Unfortunately, for now, there is no good option when it comes to executing timers. If we execute let's say 500, and defer the rest, that makes all timers effectively 8ms off until it "catches up". Depending on the shard, that may never happen.
> fix: Fixes timer orphaning issue

- Projects/Server.Tests/Tests/Geometry/Point2DTests.cs
- Projects/Server/Geometry/Point2D.cs
Point2D implements a basic TryFormat function. Only a single format is supported: "(X, Y)" where X and Y are base 10 integers.
Uses recent improvements in string interpolation to write the characters to the destination without first allocating memory for boxed arguments or intermediate strings.
This is a partial solution to issue #1067. A similar solution well be implemented in other classes in Geometry if it looks promising.
Benchmarks
---
https://github.com/harleyholt/ModernUOBenchmarks/blob/d6f8dabf3c813937e65874ea82004701be0153c4/Program.cs
Before change:
```
BenchmarkDotNet=v0.13.2, OS=ubuntu 22.04
Intel Core i7-9700K CPU 3.60GHz (Coffee Lake), 1 CPU, 8 logical and 8 physical cores
.NET SDK=6.0.402
[Host]     : .NET 6.0.10 (6.0.1022.47605), X64 RyuJIT AVX2
DefaultJob : .NET 6.0.10 …
```
> Point2D implements ISpanFormattable

- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Main.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/ISerializable.cs
- Projects/Server/Serialization/Persistence.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Misc/Guild.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Multis/Boats/BaseBoat.cs
* Implements an AfterSerialize method that is executed synchronously.
* Removes `BeforeSerialize` support since it was dangerous in its current implementation.
* Moves PlayerMobile kill/virtual decay to AfterSerialize.
* Adds kill decay to after Deserialize.
> fix: Adds AfterSerialize support. Removes BeforeSerialize support.

- Projects/Server/Client/ClientVersion.cs
- Projects/Server/Items/Item.cs
- Projects/UOContent/Engines/CannedEvil/ChampionSkullBrazier.cs
- Projects/UOContent/Items/Minor Artifacts/WrathOfTheDryad.cs
- Projects/UOContent/Items/Misc/Corpses/Corpse.cs
* Fixes a major bug where players can stack items into their backpack infinitely even if they get a message saying they can't.
* Fixes other minor issues and cleans up code.
> fix: Fixes serious stacking issue

- Projects/Server.Tests/Tests/Geometry/Point2DTests.cs
- Projects/Server.Tests/Tests/Geometry/Point3DTests.cs
- Projects/Server.Tests/Tests/Geometry/Rectangle2DTests.cs
- Projects/Server.Tests/Tests/Geometry/Rectangle3DTests.cs
- Projects/Server.Tests/Tests/Geometry/WorldLocationTests.cs
- Projects/Server/Geometry/Point2D.cs
- Projects/Server/Geometry/Point3D.cs
- Projects/Server/Geometry/Rectangle2D.cs
- Projects/Server/Geometry/Rectangle3D.cs
- Projects/Server/Geometry/WorldLocation.cs
- Projects/Server/Maps/Map.cs
- Projects/Server/Serial.cs
* Adds ISpanFormattable to geometry structs and makes ToString() near-zero-allocation.
* Adds IEquatable, and Parsable to Rectangle3D to get it in-line with the other structs.
Closes #1067
> fix: Adds ISpanFormattable to Geometry structs

- Projects/Server/Serial.cs
- Projects/Server/World/World.cs
Adds logging for `World.AddEntity<T>` and `World.AddGuild` just in case.
> fix: Adds logging for possible duplicate objects being added

- Projects/UOContent/Items/Special/Solen Items/BraceletOfBinding.cs
- Projects/UOContent/Regions/BaseRegion.cs
- Projects/UOContent/Regions/GreenAcresRegion.cs
- Projects/UOContent/Regions/JailRegion.cs
- Projects/UOContent/Regions/MondainRegion.cs
- Projects/UOContent/Regions/NoTravelSpellsAllowedRegion.cs
- Projects/UOContent/Spells/Base/SpellHelper.cs
- Projects/UOContent/Spells/Chivalry/SacredJourney.cs
- Projects/UOContent/Spells/Fourth/Recall.cs
- Projects/UOContent/Spells/Ninjitsu/ShadowJump.cs
- Projects/UOContent/Spells/Seventh/GateTravel.cs
- Projects/UOContent/Spells/Sixth/Mark.cs
- Projects/UOContent/Spells/Third/Teleport.cs
> fix: Fixes travel restriction messages

- Projects/UOContent/Items/Skill Items/Magical/Potions/Explosion Potions/BaseExplosionPotion.cs
* Fix: The potion explodes on the user if it is thrown with not enough time. Instead, the timer is stopped, and the potion explodes instantly at the target location.
* Fix: When the potion appears based on how far you throw it.
* Fix: Fixes total timer amount of time.
> fix: Smooths out throwing explosion potions

- .gitattributes
- .github/workflows/build-test.yml
- .github/workflows/create-release.yml
- Projects/Server.Tests/Server.Tests.csproj
- Projects/UOContent.Tests/UOContent.Tests.csproj
- Projects/UOContent/UOContent.csproj
- README.md
- azure-pipelines.yml
> fix: Adds migration checks to CICD, updates dependencies, adds Fedora 37, alpine 3.17 support

- Projects/Server/Maps/Map.cs
Fixes a bug where items that are large (big ItemData.CalcHeight), like harps (10), will cause an LOS error because the calculation uses the target item's height instead of the container it's in. In this edge case, the harp's height was 27 + 10, and the roof tile was 28 + 3.
> fix: Fixes LOS house bug

- Projects/UOContent/Misc/Notoriety.cs
Fixes an issue where young players cannot heal their own pets, or other young players/pets.
Closes #1344
> fix: Fixes young healing each other

- Projects/Server/Mobiles/Mobile.cs
- Projects/UOContent/Engines/Pathing/PathFollower.cs
- Projects/UOContent/Mobiles/AI/BaseAI.cs
Fixes an issue with monsters where they "run" "stop" "run" "stop" because the running flag is used.
While we could have monsters properly run when necessary, it would have to work in conjunction with their animation cadence (200ms for humanoid, 100ms for other monsters).
The use-case and game logic for this feature is out of scope and nobody has asked for it so I am not inclined to bother.
> fix: Removes run flag from NPC movement

- Projects/Server/Gumps/Gump.cs
- Projects/Server/Utilities/HashUtility.cs
Changes gumps to use the old xxHash32 algorithm so the type id is deterministic.
Also added a comment so someone can revert back to the old .NET Framework one if they want.
> fix: Makes gump type id stable

- Projects/Server/Serialization/BufferWriter.cs
Updates BufferWriter with more standard ways of writing primitives. Eliminates looping to write a string per @jaedan's suggestion.
Note: This change assumes we don't have crazy large strings.
> fix: Updates BufferWriter with more streamlined code

- Projects/Server/Interfaces.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/UOContent/Items/Weapons/Ranged/BaseRanged.cs
- Projects/UOContent/Spells/Base/Spell.cs
Hi @kamronbatman 
As we discussed together, on OSI they are sending Paralyze flag when a player casts a spell. This helps players with high ping as the client will not attempt to move whilst the paralyze flag is true. 
Previously the paralyze flag was not being sent, and when attempting to move the server would reject the move and therefore trigger a rubber band
> fix: Fixes casting by sending ParalyzeFlag to client while animating

- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Skills/AntiMacroSystem.cs
- Projects/UOContent/Skills/SkillCheck.cs
> fix: Overhauls antimacro system

- Projects/UOContent/Items/Special/House Raffle/HouseRaffleStone.cs
- Projects/UOContent/Migrations/Server.Mobiles.Meraktus.v1.json
- Projects/UOContent/Mobiles/Monsters/ML/Special/Meraktus.cs
Recommend viewing with [_whitespace disabled_](https://github.com/modernuo/ModernUO/pull/1404/files?diff=split&w=1)
> fix: Fixes leaking/errors caused by categorization

- .github/workflows/build-test.yml
- .github/workflows/create-release.yml
- Projects/Server/Gumps/GumpAlphaRegion.cs
- Projects/Server/Gumps/GumpBackground.cs
- Projects/Server/Gumps/GumpButton.cs
- Projects/Server/Gumps/GumpCheck.cs
- Projects/Server/Gumps/GumpECHandleInput.cs
- Projects/Server/Gumps/GumpEntry.cs
- Projects/Server/Gumps/GumpGroup.cs
- Projects/Server/Gumps/GumpHtml.cs
- Projects/Server/Gumps/GumpHtmlLocalized.cs
- Projects/Server/Gumps/GumpImage.cs
- Projects/Server/Gumps/GumpImageTileButton.cs
- Projects/Server/Gumps/GumpImageTiled.cs
- Projects/Server/Gumps/GumpItem.cs
- Projects/Server/Gumps/GumpItemProperty.cs
- Projects/Server/Gumps/GumpLabel.cs
- Projects/Server/Gumps/GumpLabelCropped.cs
- Projects/Server/Gumps/GumpMasterGump.cs
- Projects/Server/Gumps/GumpPage.cs
- Projects/Server/Gumps/GumpRadio.cs
- Projects/Server/Gumps/GumpSpriteImage.cs
- Projects/Server/Gumps/GumpTextEntry.cs
- Projects/Server/Gumps/GumpTextEntryLimited.cs
- Projects/Server/Gumps/GumpTooltip.cs
- README.md
- azure-pipelines.yml
.NET 6 had a bug that required the `scoped` keyword for the gump AppendTo. It looks like this was fixed since then.
> fix: Removes scoped for gump AppendTo

- Projects/UOContent/Spells/Fourth/ManaDrain.cs
Crashes on debug build when a player or mobile casts a mana drain on a player that has 0 mana and doesn't resist it. ManaDrain.cs line 71 uses Utility.Random(1, m.Mana), but there's a debug assert  in BaseRandomSource.cs that makes sure the count parameter (m.Mana in this case) is not 0.
> Fix mana drain debug build crash

- Projects/Server/Mobiles/Mobile.Migrations.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/SerializationExtensions.cs
- Projects/UOContent/Commands/Handlers.cs
- Projects/UOContent/Items/Misc/Teleporter.cs
- Projects/UOContent/Items/Special/Solen Items/BallOfSummoning.cs
- Projects/UOContent/Mobiles/Abilities/MonsterAbility.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Mobiles/Vendors/NPC/AnimalTrainer.cs
- Projects/UOContent/Spells/Necromancy/AnimateDeadSpell.cs
- Projects/UOContent/Spells/Ninjitsu/MirrorImage.cs
- Projects/UOContent/Spells/UnsummonTimer.cs
* `Stabled` has been moved to `PlayerMobile`.
* New methods added, `PlayerMobile.AddStabled` and `PlayerMobile.RemoveStabled`.
* Added `PlayerMobile.AddFollower` and `PlayerMobile.RemoveFollower`.
* `Stabled`, `AutoStabled`, and `AllFollowers` are now `HashSet` and **_CAN BE NULL_**.
* Fixes monster abilities causing harm to the monster through reflect
* Adds `CanTriggerAgainstSelf` to override this for healing or some other self-affecting ability
* Fixes a major memory leak where `UnsummonTimer` from animated dead spell lasts up-to 24hrs and therefore holds onto references of dead/deleted mobs.
* Fixes another minor leak where a mob is not unregistered from the animated dead spell list until the next spell cast.
> fix: Fixes stabled, abilities targeting self, and unsummon memory leak

- Projects/UOContent/Engines/Spawners/SpawnerEntry.cs
- Projects/UOContent/Items/Weapons/Staves/ShepherdsCrook.cs
- Projects/UOContent/Regions/HouseRegion.cs
On Dark Factions, untamed creatures were unable to move into houses (e.g., if attacked and lured). I noticed 2 places where the Controlled flag was checked in HouseRegion.cs OnMoveInto(). They both seem to be doing the same thing except one checks if AoSRules and if it's public. I'm guessing the latter is the one wanted. This removes the first check.
> fix: Fixes untamed creatures not entering houses

- Projects/Server/Items/Container.cs
Fix wrong else condition in FindItemsByType<T> that block recursion when used with "Container" and derived types and with "Item" type
> fix: Fixes FindItemsByType<T> that block recursion

- Projects/Server/Client/ClientVersion.cs
- Projects/Server/Client/UOClient.cs
Since we can't detect the version of a client older than v5.0.4d, we should return null. This fixes a bug where it was crashing.
Also fixes detecting the proper patch version.
Closes #1455 
Closes #1456
> fix: Fixes crashing while trying to detect old clients

- ModernUO.sln
- Projects/Server/Items/Container.cs
- Projects/UOContent/Engines/Craft/Core/CraftGump.cs
- Projects/UOContent/Engines/Craft/Core/CraftItem.cs
- Projects/UOContent/Engines/Treasures of Tokuno/TreasuresOfTokuno.cs
- Projects/UOContent/Items/Containers/SalvageBag.cs
- Projects/UOContent/Items/Food/Beverage.cs
- Projects/UOContent/Mobiles/Townfolk/Banker.cs
Replaced FindItem(s)ByType(s) implementation with BFS strategy.
Some minor changes due to different output collection.
> Replaced FindItem(s)ByType(s) implementation with BFS strategy

- Projects/Server.Tests/Fixtures/ServerFixture.cs
- Projects/Server.Tests/Tests/Serialization/TypeConverterTests.cs
- Projects/Server/Json/Converters/TypeConverter.cs
- Projects/UOContent.Tests/Fixtures/ServerFixture.cs
TypeConverter wasn't checking for fully qualified type names, which meant it couldn't convert type names into types that have been serialized by it.
Fixed this and added a test. Would be possible to expand this test into a full suite of conversion tests...
> fix: Fixes JSON TypeConverter so that it can deserialize full name types

- Distribution/Data/expansions.json
When the expansions.json file is deserialized to ExpansionInfo[], it has been clearing the feature flags. This is because the json deserializer has been looking for "FeatureFlags" but the name in the json is "SupportedFeatures". I've corrected expansions.json to match this, and verified it now works.
> fix: Fixes expansions.json to correctly reflect name of supported feature flags

- Projects/Server/Main.cs
- Projects/Server/Network/PingServer.cs
- Projects/Server/Network/TcpServer.cs
- Projects/UOContent/Misc/ServerList.cs
Adds ping listener so that server listings do not time out when the client tries to get the ping.
Note: CUO does a standard ping, not the same one as the EA client. So it is recommended that this ping listener is disabled and regular pings are enabled.
Configurations added:
```json
"settings": {
"pingServer.enabled": "True",
"pingServer.port": "12000",
"pingServer.maxConnections": "2048"
}
```
> feat: Adds ping listener on port 12000 for server list

- Projects/Server/Server.csproj
Fixes an issue with linux arm support where the epoll struct is not supposed to be packed.
> fix: Bumps PollGroup to fix arm support

- Projects/Server.Tests/Tests/Items/ContainerTests.cs
- Projects/Server/Items/Container.Enumerable.cs
- Projects/Server/Items/Container.cs
- Projects/Server/Mobiles/IMount.cs
- Projects/UOContent/Commands/Generic/Implementors/ContainedCommandImplementor.cs
- Projects/UOContent/Engines/ConPVP/Games/BombingRun.cs
- Projects/UOContent/Engines/ConPVP/Games/CTF.cs
- Projects/UOContent/Engines/Craft/Core/CraftGump.cs
- Projects/UOContent/Engines/Craft/Core/CraftItem.cs
- Projects/UOContent/Engines/Factions/Core/Faction.cs
- Projects/UOContent/Engines/Factions/Mobiles/Guards/BaseFactionGuard.cs
- Projects/UOContent/Engines/Harvest/Fishing.cs
- Projects/UOContent/Engines/ML Quests/Objectives/CollectObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/DeliverObjective.cs
- Projects/UOContent/Engines/Plants/MainPlantGump.cs
- Projects/UOContent/Engines/Plants/PlantSystem.cs
- Projects/UOContent/Items/Aquarium/Aquarium.cs
- Projects/UOContent/Items/Containers/SalvageBag.cs
- Projects/UOContent/Items/Food/Beverage.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/BasePotion.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Mobiles/Townfolk/Banker.cs
- Projects/UOContent/Spells/Seventh/GateTravel.cs
Container enumeration is in dire need of optimization. Thanks to @stefanomerotta for initiating this work with PR #1443. This PR handles a small part of what Stefan started. Also included are some bug fixes.
```cs
// Use with foreach without moving/deleting items
FindItemsByTypeEnumerator<T> FindItemsByType<T>(bool recurse = true, Predicate<T> predicate = null)
// Use with foreach when moving/deleting items
QueuedItemsEnumerator<T> EnumerateItemsByType<T>(bool recurse = true, Predicate<T> predicate = null)
// Use when iterating multiple times or queuing
PooledRefQueue<T> QueueItemsByType<T>(bool recurse = true, Predicate<T> predicate = null)
// Use when iterating multiples times or manipulating elements without traversing
PooledRefList<T> ListItemsByType<T>(bool recurse = true, …
```
> fix: Optimizes FindItemsByType by removing allocations.

- Projects/Server/Items/Container.Enumerable.cs
- Projects/Server/Items/Container.cs
- Projects/Server/TileData.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Commands/Generic/Implementors/ContainedCommandImplementor.cs
- Projects/UOContent/Engines/Craft/Core/CraftGump.cs
- Projects/UOContent/Engines/Craft/Core/CraftItem.cs
- Projects/UOContent/Engines/ML Quests/Objectives/CollectObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/DeliverObjective.cs
- Projects/UOContent/Engines/Plants/MainPlantGump.cs
- Projects/UOContent/Engines/Treasures of Tokuno/BasePigmentsOfTokuno.cs
- Projects/UOContent/Engines/Treasures of Tokuno/TreasuresOfTokuno.cs
- Projects/UOContent/Items/Containers/SalvageBag.cs
- Projects/UOContent/Items/Misc/Key.cs
- Projects/UOContent/Misc/Gifts/Winter2004/PileOfGlacialSnow.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Mobiles/Vendors/BaseVendor.cs
Changes nominal use of `FindItemsByType(type)` with `FindItems()` and `EnumerateItems()`
> fix: Cleans up FindItems and removes allocations

- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/GenericEntitySerialization.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/ISerializable.cs
- Projects/Server/Serialization/SerializationExtensions.cs
- Projects/Server/World/EntityPersistence.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BOBEntries.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BOBLargeEntry.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BOBLargeSubEntry.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BOBSmallEntry.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BaseBOBEntry.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BulkOrderBook.cs
- Projects/UOContent/Engines/Bulk Orders/Books/IBOBEntry.cs
- Projects/UOContent/Migrations/Server.Engines.BulkOrders.BOBLargeEntry.v1.json
- Projects/UOContent/Migrations/Server.Engines.BulkOrders.BOBLargeSubEntry.v0.json
- Projects/UOContent/Migrations/Server.Engines.BulkOrders.BOBSmallEntry.v1.json
- Projects/UOContent/Migrations/Server.Engines.BulkOrders.BaseBOBEntry.v1.json
- Projects/UOContent/Mobiles/Healers/BaseHealer.cs
Adds a generic entity persistence. This can be used to create new entity types that have a `Serial`.
Here is an example:
```cs
public class BOBEntries : GenericEntitySerialization<IBOBEntry>
{
public static void Configure()
{
Configure("BOBEntries");
}
}
```
The annotation tells the system what folder to serialize the entries to. The class/interface (`IBOBEntry`) is the root type that implements `ISerializable`.
> fix: Adds generic entity persistence support and BOBEntry as entities

- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Main.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/PingServer.cs
- Projects/Server/Serialization/GenericEntityPersistence.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/ISerializable.cs
- Projects/Server/Serialization/Persistence.cs
- Projects/Server/World/IGenericSerializable.cs
- Projects/Server/World/World.cs
> fix: Fixes serialization threading, moves world save to end of loop, and eliminates Parallel.ForEach.

- Projects/UOContent/Mobiles/Vendors/NPC/AnimalTrainer.cs
Changes:
* Changed the `break` to `continue` so the foreach loop will continue looping in order to list out all pets. 
* Previously, the `break` would cause it to always list the first stabled pet and stop there.
Screenshot:
Shows the new implementation (using `claim l`) in action and the regular `claim` command's text output (after claiming and restabling).
> fix: Fix animal trainer pet list only showing first pet.

- Projects/Server/Items/Container.cs
Issue:
* The Items queue was never actually getting populated with any items, so the `ConsumeTotal` call was always returning false, causing the vendor to always say the user doesn't have enough gold.
Changes:
* Removed the `Item.add()` call and added an `items.Enqueue()` call to items.
> Fix for vendors not actually selling anything (except via Buy Agent)

- Projects/Server.Tests/Tests/Collections/ValueLinkListTests.cs
- Projects/Server/Collections/ValueLInkList.cs
Adds a `struct` based link list called `ValueLinkList`. To use this link list, elements must have the interface `IValueLinkListNode<T>`.  This means that a particular object can only be on one list, and it can only have one set of linking fields (next or previous) with a type of that class or it's parent.
```cs
public struct ValueLinkList<T> where T : class, IValueLinkListNode<T>
{
void AddFirst(T node);
void AddLast(T node);
void AddBefore(T before, T node);
void AddAfter(T after, T node);
// Moving from one list to another
void AddLast(ref ValueLinkList<T> otherList, T start, T end);
void Remove(T node);
void RemoveAllBefore(T node);
void RemoveAllAfter(T node);
// Iterating
DescendingValueListEnumerator ByDescending();
}
```
```cs
public class Item : IValueLinkListNode<Item>
{
public …
```
> feat: Adds ValueLinkList

- Projects/UOContent/Items/Food/Beverage.cs
The Witch's Apprentice quest was not beatable. The check would only allow players to fill up a pitcher with swamp water if the quest was completed, which made it unbeatable.
> Fix for witch's apprentice quest - was not "beatable"

- Projects/UOContent/Items/Misc/FlippableAttribute.cs
Using a decorator tool on certain items (example: some Paragon Chests) will cause clients to crash, throwing a `IndexOutOfRangeException`.
It depends on the ItemIDs property, and we were only checking if it's null or not, not if it has any elements, which ended up causing it to set `item.ItemID = ItemIDs[index];` (or null).
> fix: FlippableAttribute with empty list will crash the client.

- Projects/Server.Tests/Tests/Network/Packets/Outgoing/AccountPacketTests.cs
- Projects/Server/IAccount.cs
- Projects/Server/Serialization/IGenericReader.cs
- Projects/UOContent/Accounting/Account.Migrations.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Accounting/Accounts.cs
- Projects/UOContent/Migrations/Server.Accounting.Account.v5.json
- Projects/UOContent/Misc/SerializationExt.cs
- Projects/UOContent/Misc/ServerAccess.cs
- Fixes usernames not being `Intern`ed
- Reverts methods related to getting accounts from returning `Account` to `IAccount`.
- Makes `IAccount` also `ISerializable`
- Adds `IGenericReader.ReadAccount()` and `IGenericWriter.Write(IAccount)` -> The read method supports the original serialization of username, and using `IAccount.Serial`. The write method only serializes the `Serial`.
- Exposes `ReadStringRaw()` to allow some advanced scenarios.
> fix: Reverts GetAccount to use IAccount. Adds IAccount to serialization.

- Projects/Server/Effects.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Maps/Map.ClientEnumerator.cs
- Projects/Server/Maps/Map.ItemEnumerator.cs
- Projects/Server/Maps/Map.cs
- Projects/Server/Maps/PooledEnumeration.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/UOContent/Engines/ConPVP/Games/BombingRun.cs
- Projects/UOContent/Engines/Doom/LeverPuzzle/LeverPuzzleController.cs
- Projects/UOContent/Engines/Veteran Rewards/Character Statue Maker/CharacterStatue.cs
- Projects/UOContent/Items/Skill Items/Camping/Campfire.cs
- Projects/UOContent/Skills/Snooping.cs
Eliminates `IPooledEnumerable<NetState>` and `eable.Free()` from `Map` for clients. This drastically simplifies code that iterates in range, for example:
```cs
foreach (var m in m.GetClientsInRange(5))
{
}
```
The code above no longer requires an eable and calling `Free()`.
> fix: Adds GetClients to map iterators

- Projects/UOContent/Mobiles/Animals/Mounts/Ethereals.cs
Fixed missing label for ethereal horse statues.  Issue can be seen in screen shot.
> Fix for missing ethereal horse label

- Directory.Build.props
- Projects/Server/Json/Converters/Point2DConverter.cs
- Projects/Server/Json/Converters/Point3DConverter.cs
- Projects/Server/Json/Converters/Rectangle3DConverter.cs
- Projects/Server/Json/Converters/WorldLocationConverter.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Module.cs
- Projects/Server/Network/PacketUtilities.cs
- Projects/Server/Network/Packets/OutgoingEntityPackets.cs
- Projects/Server/Network/Packets/OutgoingMobilePackets.cs
- Projects/Server/Text/StringHelpers.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Engines/Party/PartyPackets.cs
- Projects/UOContent/Engines/Quests/Collector/Items/ImageTypeInfo.cs
- Projects/UOContent/Items/Bulletin Boards/BulletinBoardPackets.cs
- Projects/UOContent/Module.cs
- Projects/UOContent/Multis/Boats/BoatPackets.cs
- Projects/UOContent/Multis/Houses/HousePackets.cs
- Works around a sneaky edge case bug in the JIT with stackalloc where sometimes the buffer is not zero'd.
- Fixes SendDisplayBoatHS
- Fixes sending health bars in the `SendEverything()` logic.
- Fixes a bug in sizing for some string helper functions.
We are enabled `SkipLocalsInit` - do not rely on `stackalloc` to be zero'd. To zero the buffer, use `span.Clear();`
Closes #1606
> fix: Fixes sending packets and sidesteps a major issue with stackalloc and PGO in .NET 8 

- Projects/UOContent.Tests/Tests/Utilities/TryParseTests.cs
- Projects/UOContent/Utilities/Types.cs
Server.TryParse() function was failing to parse "True" or "False" as bools. I've fixed this and added tests.
> Fix Server.TryParse so it works for Boolean types

- Projects/Server.Tests/Tests/Client/ClientVersionTests.cs
- Projects/UOContent/Engines/ConPVP/Gumps/TournamentBracketGump.cs
- Projects/UOContent/Engines/Spawners/BaseSpawner.cs
- Projects/UOContent/Items/Bulletin Boards/BulletinBoardPackets.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/BasePotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Conflagration Potions/BaseConflagrationPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Confusion Blast Potions/BaseConfusionBlastPotion.cs
- Projects/UOContent/Items/Skill Items/Misc/Bandage.cs
- Projects/UOContent/Misc/BuffIcons.cs
- Projects/UOContent/Misc/ClientVerification.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Mobiles/Vendors/BaseVendor.cs
- Projects/UOContent/Spells/Base/SpellHelper.cs
- Projects/UOContent/Spells/Spellweaving/Items/TransientItem.cs
- Projects/UOContent/World Saves/AutoArchive.cs
- Projects/UOContent/World Saves/AutoSave.cs
TLDR - .NET Framework rounded TimeSpan (and some DateTime) methods to the nearest millisecond. This was actually _expected_ accidentally for parts of RunUO.
We are aiming to fix this and clean up some other bad assumptions.
Closes #1604
> fix: Fixes TimeSpan rounding issues

- Projects/UOContent.Tests/Tests/Utilities/TryParseTests.cs
- Projects/UOContent/Accounting/AccountHandler.cs
- Projects/UOContent/Misc/CharacterCreation.cs
- Moves starting city info from AccountHandler to CharacterCreation
- Simplifies the logic of determining the starting cities
- Adds support for Trammel & Felucca for non-young accounts
- Fixes fall through starting city for v6+ in UOR era.
- All staff are force-sent to GA.
- Move the starting cities to JSON files
- Add in New Magincia (`1075077`) to the client versions/eras that support it.
Closes #1408
> fix: Fixes character starting cities.

- Projects/Server.Tests/Tests/Network/Packets/Outgoing/PlayerPacketTests.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Network/Packets/OutgoingPlayerPackets.cs
- Projects/UOContent/Gumps/Props/PropsGump.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Utilities/Types.cs
- Removes old death packet that isn't used. Doubtful this causes issues with clients that are v4+.
- Removes duplicate incoming packets. Again, probably to fix some old client issues, doubtful it affects clients v4+.
- Fixes setting serials and entities in props/commands. Note: Disabled setting `Parent` since the new sector code has issues. We shouldn't rely on it anyway!
- Reverts a recent change to healthbars that should not have been made. Oops!
> fix: Fixes various mobile packets and setting serials

- Projects/Server/Maps/Map.StaticTileEnumerator.cs
- Projects/Server/TileMatrix/TileMatrix.cs
Fixed wrong sector shift for TileMatrix iteration
Added SectorShift constant to clarify right shift for TileMatrix
> fix: Fixes wrong sector shift for TileMatrix iteration

- Projects/Server/Items/Container.cs
Fixes GumpID and DropSound default value for containers that will be set as -1.
Fixes for already saved containers can be done with following commands:
```
[global set gumpid -1 where container gumpid == 0
```
```
[global set dropsound -1 where container dropsound == 0
```
> fix: Fixes default GumpID and DropSound serialization for containers

- Projects/UOContent/Mobiles/Townfolk/Banker.cs
Discovered when players would use a House Placement Tool to make a large purchase. When this code would check their bank box:
1. It wouldn't recursively check containers in the bank box for gold/checks.
2. It would crash when players had check(s) and gold in their bank box. Full Disclaimer: I'm by no means a .NET expert. I don't know how the code works that I removed (Feel free to explain!). It seemed to act like the two variables were references to one another. When my test character had 2 piles of gold and 2 checks in their main bank box, it would return both `gold` AND `checks` as lists with FOUR objects each. This caused a client crash in Banker.cs line 138, when it was attempting to cast a `Gold` object into a `BankCheck` object. It most likely caused issues on line 122, as well, …
> fix: Client crash when banker tries to use checks & gold for a purchase

- Projects/Server/Collections/PooledRefList.cs
- Projects/Server/Collections/PooledRefQueue.cs
Added an additional check to pooled collection dispose method so it can be used also against defaults
> fix: Fixes pooled ref collections dispose on defaults

- Projects/UOContent/Engines/Advanced Search/AdvancedSearchCommand.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchConfirmBringGump.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchConfirmDeleteGump.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchFilter.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchGump.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchResult.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchResultComparers.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchThreadWorker.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchUtilities.cs
- Projects/UOContent/Engines/Advanced Search/AdvancedSearchWarningGump.cs
Adds Advanced Search (XmlFind) using `[AS` command.
Notable differences from XmlFind:
* No save to file.
* No "Display from" option (might add that later).
* No advanced XmlSpawner property test syntax. Only basic property operator comparisons.
* This version will freeze your shard, but fans out to all processors just like world saves. (So it should be stupid fast, especially if you have lots of cores)
* Does not support spawn entry/type/error searching. We have a spawn search command to do that already.
* I haven't set up correct "defaults" for the options when you first open it. I'll do that later.
> feat: Adds AdvancedSearch (XmlFind)

- Projects/UOContent/Items/Special/Solen Items/BagOfSending.cs
You couldn't actually set the hue (randomly/automatically or manually) on item creation.
> Fix hues for Bags of Sending

- Projects/Server/Items/BaseMulti.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Maps/Map.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/World/EntityPersistence.cs
- Projects/UOContent/World Saves/AutoSave.cs
> [!Important]
> **This fixes a major issue with [dupe and serialization!**
- Fixes [dupe sharing the same SaveBuffer, causing serialization clobbering.
- Fixes an issue with Mobile.SetLocation() -> UpdateRegion() -> OnRegionChange() -> having side effects that makes calling Map.OnMove(0 later in the SetLocation invalid.
- Fixes disabling AutoSave not working.
> fix: Fixes issue with duping items and serialization, and sector lists.

- Projects/Server/Items/Item.cs
- Projects/UOContent/Engines/Treasures of Tokuno/LesserArtifacts.cs
- Projects/UOContent/Misc/Loot.cs
- Projects/UOContent/Misc/LootPack.cs
* Adds logging if Amount goes to zero. It should never go to zero!
* Deletes an item if it mutates with zero amount.
* Eliminates possible allocation from `params` for `Type[][]` loot pack construction.
* Renames `Loot.ChestOfHeirloomsContains` to `Loot.RandomChestOfHeirloomsContent`.
> fix: Fixes loot with zero amount

- Projects/UOContent/Items/Special/Special Scrolls/PowerScroll.cs
- Projects/UOContent/Items/Special/Special Scrolls/ScrollofAlacrity.cs
- Projects/UOContent/Items/Special/Special Scrolls/ScrollofTranscendence.cs
- Projects/UOContent/Items/Special/Special Scrolls/SpecialScroll.cs
- Projects/UOContent/Items/Special/Special Scrolls/StatCapScroll.cs
- Projects/UOContent/Misc/AOS.cs
- Fixes edge case calculations with values that aren't exact.
- Fixes skill text casing.
- Fixes cliloc error for stat cap scroll gump.
- Adds `AosSkillBonuses.GetLowercaseLabel()` for lower case localized skill names.
- Fixes initial value for constructing a stat scroll so it isn't negative.
- Fixes message for Scroll of Alacrity gump.
- Fixes missing property invalidation for Skill/Value.
> fix: Fixes special scroll logic and display

- Projects/Server/Buffers/SpanReader.cs
- Projects/Server/Gumps/RelayInfo.cs
- Projects/UOContent/Network/Packets/IncomingPlayerPackets.cs
Removed TextEntry struct and added deferred text response handling for gumps with spans.
The string instantiation is deferred to GetTextEntry method.
> fix: Make RelayInfo zero allocation

- Projects/Server/Maps/Map.StaticTileEnumerator.cs
Fixes a bug with iterating a sector and multiple multis (boats/houses).
Closes #1702, #1705
> fix: Fixes multiple multis in a sector iteration

- Distribution/Data/npc-speeds.json
- Projects/Server/Mobiles/Mobile.cs
- Projects/UOContent/Engines/Factions/Mobiles/Guards/GuardAI.cs
- Projects/UOContent/Engines/ML Quests/Objectives/EscortObjective.cs
- Projects/UOContent/Engines/Pathing/MoveResult.cs
- Projects/UOContent/Engines/Pathing/PathFollower.cs
- Projects/UOContent/Items/Weapons/BaseWeapon.cs
- Projects/UOContent/Mobiles/AI/AnimalAI.cs
- Projects/UOContent/Mobiles/AI/ArcherAI.cs
- Projects/UOContent/Mobiles/AI/BaseAI.cs
- Projects/UOContent/Mobiles/AI/BerserkAI.cs
- Projects/UOContent/Mobiles/AI/MageAI.cs
- Projects/UOContent/Mobiles/AI/MeleeAI.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/Familiars/BaseFamiliar.cs
- Projects/UOContent/Mobiles/Healers/BaseHealer.cs
- Projects/UOContent/Mobiles/NPCSpeeds.cs
- Projects/UOContent/Mobiles/Special/Neira.cs
- Projects/UOContent/Mobiles/Townfolk/BaseEscortable.cs
- Projects/UOContent/Spells/Ninjitsu/MirrorImage.cs
> [!IMPORTANT]  
> Please read through these changes, as they changed certain expectations for how the internal AI thinking/movement work.
> Note that some mobs still don't have smooth movement on ClassicUO due to how the client handles animations/movement.
- **Important Change**: Mobs will now move at a more regular pace. If the OnThink results in a move, but the cooldown would otherwise prevent the move, then the movement is scheduled on another timer.
- Added a 400ms delay to mobs turning to face a player to attack in order to avoid glitching between moving and turning.
- Reverted AI thinking speeds back to RunUO specific speeds.
- Reverted the AI thinking to moving conversion delays back to RunUO.
- For thinking speeds that are not exactly the predefined speeds from RunUO, there is a …
> fix: Reverts to RunUO speeds, fixes direction glitching, adds movement speed interpolation

- Projects/Server/Random/BuiltInRng.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Engines/Quests/Collector/Items/ImageTypeInfo.cs
- Projects/UOContent/Items/Special/8th Anniversary Items/Dawn's Music Box/DawnsMusicBox.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
* Removes unnecessary extra loops in increasing loyalty while feeding pets.
* Adds `Utility.CoinFlips` for batch 50/50 successive calls to RNG
* Removes improper usage of `Utility.RandomSample()` and instead uses `Shuffle()`
> [!NOTE]
> **DEVELOPER NOTE**
> 1. Use `Utility.CoinFlips(amount) or `Utility.CoinFlips(amount, max)` instead of looping and doing `Utility.RandomBool()` multiple times. The new method is up to 60x faster.
> 2. Utility.RandomSample is for sampling unique `indices` and has no guard rails against duplicate values
> fix: Cleans up code with feeding pets and adds batch coin flips random check

- Projects/Server/Attributes.cs
- Projects/Server/Console/ConsoleInputHandler.cs
- Projects/Server/Main.cs
- Projects/UOContent/Misc/AccountPrompt.cs
Fixes an issue where the call priority of `Initialize` functions causes a dead lock because the console input handler was not initialized.
> fix: Fixes unresponsive console input

- Projects/UOContent/Items/Special/Holiday/SnowStatue.cs
- Projects/UOContent/Spells/First/CreateFood.cs
- Apparently affixes and other old packets do not support unicode, so we can't translate them. On OSI they use English for quite a bit.
> fix: Fixes bad localized messages

- Projects/UOContent/Misc/StaminaSystem.cs
- Projects/UOContent/Mobiles/Animals/Mounts/BaseMount.cs
- Projects/UOContent/Mobiles/Animals/Mounts/Ethereals.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/VirtualMountItem.cs
* Makes mount stamina significantly faster.
* Reduces absolute reset from 24 hours to 4 hours.
* Adds Pub 46+ Ethereal stamina where the stamina is global to all mounts for the player
* Removes serialization of stamina entirely because it's ok if it gets reset during shard restarts.
> fix: Fixes mount stamina, adds Pub46+ Ethereal stamina

- Projects/Server/Network/TcpServer.cs
Adds back the `SocketConnected` event. This event only fires asynchronously! (TcpServer thread).
Example:
```cs
public static void Configure()
{
TcpServer.EventSink.SocketConnected += OnSocketConnected;
}
// WARNING: Executed on the TcpServer thread!
private static void OnSocketConnected(TcpServer.SocketConnectedEventArgs args)
{
if (... logic here...)
{
AdminFirewall.Add(((IPEndPoint)Socket.RemoteEndPoint)!.Address);
}
}
```
> fix: Adds back socket connected event

- Projects/Server/Items/Container.cs
Fixes an issue where max items is deserialized as 0 instead of -1. To fix broken containers, run the following in-game:
`[global set maxitems -1 where container maxitems = 0`
In vanilla MUO, there are no containers that actually have max items set to 0.
> fix: Fixes max items serialization issue

- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Commands/Batch.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BulkOrderBook.cs
- Projects/UOContent/Engines/Help/PageQueue.cs
- Projects/UOContent/Engines/Help/SpeechLogGump.cs
- Projects/UOContent/Gumps/Guilds/New Guild System/CreateGuildGump.cs
- Projects/UOContent/Gumps/Guilds/New Guild System/GuildInfoGump.cs
- Projects/UOContent/Gumps/Guilds/New Guild System/GuildMemberInfoGump.cs
- Projects/UOContent/Gumps/Guilds/New Guild System/OtherGuildInfo.cs
- Projects/UOContent/Gumps/RunebookGump.cs
- Projects/UOContent/Holiday Stuff/Valentine/2011/Items/StValentinesBears.cs
- Projects/UOContent/Items/Books/BookPackets.cs
- Projects/UOContent/Items/Guilds/Guildstone.cs
- Projects/UOContent/Items/Misc/Key.cs
- Projects/UOContent/Items/Special/Veteran Rewards/WeaponEngravingTool.cs
- Projects/UOContent/Mobiles/Vendors/PlayerVendor.cs
- Projects/UOContent/Multis/Houses/BaseHouse.cs
- Projects/UOContent/Multis/Houses/HouseSign.cs
- Fixes a bug where FixHtml was not releasing the pooled array
- Cleans up usages of FixHtml and similar functions
> fix: Cleans up FixHtml

- Projects/Server/Gumps/GumpStringsBuilder.cs
- Projects/Server/Text/TextDefinitionExtensions.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Engines/Bulk Orders/SmallBODAcceptGump.cs
- Projects/UOContent/Engines/ConPVP/Gumps/TournamentBracketGump.cs
- Projects/UOContent/Engines/Help/PageQueueGump.cs
- Projects/UOContent/Engines/ML Quests/Gumps/BaseQuestGump.cs
- Projects/UOContent/Engines/ML Quests/Gumps/InfoNPCGump.cs
- Projects/UOContent/Engines/ML Quests/Gumps/QuestCancelConfirmGump.cs
- Projects/UOContent/Engines/ML Quests/Objectives/BaseObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/CollectObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/DeliverObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/EscortObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/GainSkillObjective.cs
- Projects/UOContent/Engines/ML Quests/Objectives/KillObjective.cs
- Projects/UOContent/Engines/ML Quests/Rewards/BaseReward.cs
- Projects/UOContent/Engines/Plants/MainPlantGump.cs
- Projects/UOContent/Engines/Quests/Core/QuestSystem.cs
- Projects/UOContent/Engines/Quests/Terrible Hatchlings/Objectives.cs
- Projects/UOContent/Gumps/BaseConfirmGump.cs
- Projects/UOContent/Gumps/RewardGump.cs
- Projects/UOContent/Gumps/StaticWarningGump.cs
- Projects/UOContent/Gumps/WarningGump.cs
- Projects/UOContent/Gumps/YoungGumps.cs
- Projects/UOContent/Items/Aquarium/AquariumGump.cs
- Projects/UOContent/Items/Containers/TreasureMapChest.cs
- Projects/UOContent/Items/Special/Special Scrolls/SpecialScroll.cs
- Fixes an issue that causes CUO to crash due to bad string caching in static gumps
- Fixes wrong/bad 16bit html gump hues.
- Moves `C16232` (16-bit to 32-bit) and `C32216` (32-bit to 16-bit) to Utility class for broader use.
TODO:
- Some gumps have different 32bit (for string content) vs 16bit (for localized content) strings. Does this matter?
> fix: Fixes issue with cached static gump strings. Fixes bad gump colors

- .github/workflows/build-test.yml
- Projects/Server.Tests/Tests/Network/Packets/Outgoing/GumpPackets.cs
- Projects/Server/Compression/Deflate.cs
- Projects/Server/MultiData.cs
- Projects/Server/Network/Packets/OutgoingGumpPackets.cs
- Projects/Server/Server.csproj
- Projects/UOContent.Tests/Tests/Multis/Houses/HousePackets.cs
- Projects/UOContent/Multis/Houses/HousePackets.cs
- Projects/UOContent/UOContent.csproj
- README.md
- version.json
> [!Warning]
> Users on Linux/OSX will need to follow the Readme
> and make sure `libdeflate` is properly installed
> [!Note]
> **Developer Note**
> The API for compression has changed. Use `Deflate.Standard` for the same functionality.
* Replaces Zlib with LibDeflate for a 50% performance improvement!
* Adds MacOS 14 to properly test Arm64
> feat: Replaces Zlib with LibDeflate

- Projects/UOContent/Items/Skill Items/Misc/RecipeScroll.cs
Needs to be list.AddLocalized, otherwise property list will display the cliloc number instead of the name...
Before:
After:
> Fix RecipeScroll displays cliloc number in properties instead of name

- Projects/Server/Gumps/Legacy/GumpHtmlLocalized.cs
- Projects/Server/Gumps/Legacy/GumpImage.cs
- Fixes wrong interpolation.
> [!Important]
> *Developer Note*
> Do not use ternary/switch expressions inside arguments to functions that take custom interpolations.
> Doing so will result in the interpolation handler not being used, and a **string will be allocated instead**.
> fix: Fixes incorrect interpolation in legacy gumps

- Projects/Server/Console/ConsoleInputHandler.cs
Fix a rare Input/Output bug in Console Input Handler for Linux users, as discussed in [Discord](https://discord.com/channels/751317910504603701/751348235116871711/1245159640287678507):
```
Error:
System.IO.IOException: Input/output error
at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirError)
at Interop.CheckIo(Int64 result, String path, Boolean isDirError)
at System.IO.StdInReader.ReadKey()
at System.IO.StdInReader.ReadLineCore(Boolean consumeKeys)
at System.IO.StdInReader.ReadLine()
at System.IO.SyncTextReader.ReadLine()
at System.Console.ReadLine()
at Server.ConsoleInputHandler.ProcessConsoleInput() in ...ModernUO/Projects/Server/Console/ConsoleInputHandler.cs:line 156
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
at …
```
> Fix ConsoleInput for Linux users with try/catch.

- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Utilities/ActivatorExtensions.cs
- Projects/UOContent/Commands/Dupe.cs
- Projects/UOContent/Items/Aquarium/Aquarium.cs
- Removes copying private setters
- Fixes duping containers
- Adds public `Dupe.DoDupe` functions for external scripts to hook into the existing logic.
> fix: Fixes duping containers and removes copying private setter properties

- Projects/UOContent/Accounting/AccountHandler.cs
- Projects/UOContent/Misc/CharacterCreation.cs
- Removes new player "Haven Only" starting city.
- Fixed New/Old haven placement.
- Removed force-profession starting location for SA+.
- Added Royal City for SA+
- Removed Occlo for Pre-AOS.
> fix: Fixes character creation issues. Adds Royal City

- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Network/PacketHandler.cs
- Projects/Server/Network/Packets/IncomingPackets.cs
- Projects/UOContent/Assistants/AssistantProtocol.cs
- Projects/UOContent/Network/ContainerGridPacketHandler.cs
- Projects/UOContent/Network/FreeshardProtocol.cs
- Projects/UOContent/Network/Packets/IncomingAccountPackets.cs
- Projects/UOContent/Network/Packets/IncomingExtendedCommandPackets.cs
- Projects/UOContent/Network/Packets/IncomingItemPackets.cs
- Projects/UOContent/Network/ProtocolExtensions.cs
- Fixes various exploits that can crash the shard when the client misbehaves.
- Clients will now be disconnected if they send packets that are marked as out of game only (new flag), while they are in-game.
> [!Note]
> **Developer Note**
> Added an `OutOfGameOnly` which should be used to flag packets as only available out of the game.
> This is the opposite of, yet not the converse to `InGameOnly`.
> fix: Fixes crashing due to bad packet assumptions.

- Projects/UOContent/Items/Misc/Blighted Grove/MelisandesFermentedWine.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Agility Potions/BaseAgilityPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/BasePotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Conflagration Potions/BaseConflagrationPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Confusion Blast Potions/BaseConfusionBlastPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Cure Potions/BaseCurePotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Explosion Potions/BaseExplosionPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Heal Potions/BaseHealPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/InvisibilityPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/NightSight.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Refresh Potions/BaseRefreshPotion.cs
- Projects/UOContent/Items/Skill Items/Magical/Potions/Strength Potions/BaseStrengthPotion.cs
Most potions have various checks, such as a cooldown. This fixes an edge case where potions get split from their stack before erroring.
> fix: Fixes splitting potions before error

- Projects/UOContent/Items/Food/Cooking.cs
- Projects/UOContent/Items/Resources/Blacksmithing/Ingots.cs
- Projects/UOContent/Items/Resources/Blacksmithing/Ore.cs
- Projects/UOContent/Items/Resources/Blacksmithing/Scales.cs
- Projects/UOContent/Items/Resources/Masonry/Granite.cs
- Projects/UOContent/Items/Resources/Tailor/Hides.cs
- Projects/UOContent/Items/Resources/Tailor/Leathers.cs
- Projects/UOContent/Items/Skill Items/Carpenter Items/Board.cs
- Projects/UOContent/Items/Skill Items/Fishing/Misc/MessageInABottle.cs
- Projects/UOContent/Items/Skill Items/Fishing/Misc/SOS.cs
- Projects/UOContent/Items/Skill Items/Lumberjack/Log.cs
- Projects/UOContent/Items/Special/MiniHouses.cs
- Fixes resource commodities so the hue changes when setting the resource
- Fixes some commodities not being able to be modified in-game.
> fix: Fixes commodity resource property hue

- Projects/Server.Tests/Tests/Timer/TimerTests.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Timer/Timer.cs
- Projects/Server/Utilities/Utility.cs
Timers that have no more counts left are considered _Stopped_ (`Running` = `false`). This means that an OnTick that calls Start(), should start properly. GreenThorns uses this for it's multiple effect transitions.
> fix: Fixes timers not stopping before OnTick

- Projects/UOContent/Items/Clothing/Artifacts/CrimsonCincture.cs
Previously displayed as 'half apron'
> CrimsonCinture add missing LabelNumber

- Projects/UOContent/Commands/AddonGenerator.cs
- Projects/UOContent/Items/Special/House Raffle/HouseRaffleManagementGump.cs
House raffle (as an example) was comparing IP Addresses byte by byte to sort them on the gump. We recommend using the `ToUInt128` convenience to avoid memory allocations (40bytes), and because it is up to 3x faster.
> fix: Changes IPAddress comparison to use UInt128

- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Gumps/AdminGump.cs
- Fixed a bug caused by a bad assumption. If `m_List[index]` is sparse and null values are casted, the server does not crash.
- Fixed a bug where `PooledRefList.ToList` extension method returned the wrong list size.
> fix: Fixes PooledRefList ToList returning wrong size

- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Timer/Timer.cs
- Projects/UOContent/Items/Weapons/Abilities/ForceOfNature.cs
- Projects/UOContent/Spells/Spellweaving/GiftOfRenewal.cs
- Fixes timer intervals not continuing
- Fixes `Timer.Index` being off by 1. Should start at 0 for the first OnTick
- Simplifies Gift of Renewal end check
- Fixes force of nature not applying at the proper time and simplifies the timer logic.
> fix: Fixes timer interval & index offset

- Projects/UOContent/Engines/Factions/Items/Power Faction Items/UrnOfAscension.cs
- Projects/UOContent/Engines/Virtues/Sacrifice.cs
- Projects/UOContent/Gumps/PricedResurrectGump.cs
- Projects/UOContent/Gumps/ResurrectGump.cs
- Projects/UOContent/Items/Skill Items/Misc/Bandage.cs
- Projects/UOContent/Items/Special/Veteran Rewards/AnkhOfSacrifice.cs
- Projects/UOContent/Mobiles/Healers/PricedHealer.cs
- Projects/UOContent/Spells/Chivalry/NobleSacrifice.cs
- Projects/UOContent/Spells/Eighth/Resurrection.cs
Looked into migrating the `ResurrectionGump`.
It turns out that it covers both the regular use and a special RunUO gump for the `PricedHealer`.  Therefore I split it into two new `StaticGump` implementations.  They share much of the same logic in their response handler, and I'm open to suggestions for how to abstract that out.
> fix: Converts ResurrectGump to Static/Dynamic Gumps

- Projects/UOContent/Engines/ConPVP/AcceptDuelGump.cs
- Projects/UOContent/Engines/ConPVP/DuelContext.cs
- Projects/UOContent/Gumps/Base/GumpSystem.IncomingPackets.cs
- Projects/UOContent/Gumps/Base/GumpSystem.cs
- Projects/UOContent/Gumps/Base/NetStateGumps.cs
- Projects/UOContent/Gumps/PricedResurrectGump.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- global.json
Fixes wrong behavior of NetStateGumps: added null check to send gump in case of null NetState and removed empty list.
Added gump list max size checks.
Removed unused/unwanted methods.
> fix: Fix NetStateGumps and other Gumps cleanup

- Projects/UOContent/Spells/Seventh/GateTravel.cs
Should be the linked gates Map, not TargetMap, as that is the map you're gating from...
Therefore, gating across maps sends you to the correct location on the original map...
Example, gating to Luna bank...
> Typo in GateTravel sends you to the origin map

- Projects/Server/Utilities/Utility.cs
Assuming this is correct like in FixHtml, without it my guild abbreviation becomes whatever is left over the in the shared buffer.
> Fix missing CopyTo in FixHtmlFormattable

- Projects/UOContent/Items/Talismans/TalismanSummons.cs
Actually reported by a player on my shard, and I can re-create...
Talisman such as Totem Of The Void (didn't test with anything else)
> Releasing a Talisman summon deletes your character

- .editorconfig
Edited the config file to ignore some of the common suggestions and warnings peppering the unchangeable legacy code.
Commented for easy of understanding and review. 
The expression-bodies one specifically is a red warning.
> Remove warnings/suggestions

- Projects/Server.Tests/Tests/Network/Packets/Outgoing/AccountPacketTests.cs
- Projects/Server/Guild.cs
- Projects/Server/IEntity.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Mobiles/Mobile.cs
- Projects/Server/Serialization/AdhocPersistence.cs
- Projects/Server/Serialization/BinaryFileReader.cs
- Projects/Server/Serialization/BufferWriter.cs
- Projects/Server/Serialization/GenericEntityPersistence.cs
- Projects/Server/Serialization/GenericPersistence.cs
- Projects/Server/Serialization/IGenericSerializable.cs
- Projects/Server/Serialization/MemoryMapFileWriter.cs
- Projects/Server/Serialization/Persistence.cs
- Projects/Server/Serialization/SerializationExtensions.cs
- Projects/Server/Serialization/SerializationThreadWorker.cs
- Projects/Server/World/World.cs
- Projects/UOContent/Accounting/Account.cs
- Projects/UOContent/Engines/Bulk Orders/Books/BaseBOBEntry.cs
- Projects/UOContent/Engines/Ethics/Core/EthicsEntity.cs
- Projects/UOContent/Gumps/AdminGump.cs
- `GenericEntityPersistence` is now a type of `GenericPersistence`. This allows developers to serialize both entities and non-entities in the same system. 🎉
- Each `SerializationThreadWorker` now allocates 1MB of heap for serialization _permanently_. If more memory is needed, that thread will double it's memory, not to exceed increments of 64MB.
- Several bugs with serialization introduced with the pure MMF implementation have been fixed.
- `BinaryFileReader` has been added back. 🎉
- Adds `world.useMultithreadedSaves` to allow disabling threaded saves.
> [!IMPORTANT]
> **Developer Note**
> The split file serialization has been deprecated and is no longer used. We have effectively gone back to the same file writing we had before the pure MMF implementation.
> feat: Upgrades serialization v4 (Threaded Heap Serialization)

- Projects/Server/Events/SocketConnectionEvent.cs
- Projects/Server/Main.cs
- Projects/Server/Network/Firewall/Firewall.cs
- Projects/Server/Network/IPLimiter.cs
- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Network/PingServer.cs
- Projects/Server/Network/TcpServer.cs
- Projects/UOContent/Gumps/AdminGump.cs
- Projects/UOContent/Misc/AdminFirewall.cs
- version.json
- Puts back `EventSink.SocketConnect`.
- Reverts networking change to push the networking to a separate thread.
- Reverts changes to the firewall by removing the firewall queue.
- Fixes listeners not shutting down with the server.
- Fixes race condition causing connections to get stuck even after they are disposed.
> [!NOTE]
> **Developer Note**
> Networking has been reverted back to using the main thread instead of a background thread. This alleviated complexity and the requirement for concurrent queues all over the place.
> fix: Fixes networking issues

- Projects/UOContent/Misc/ServerList.cs
This is important for container management hosts where the server container doesn't have access to the host IP.
The following scenarios were tested:
| scenario                                                   | public ip | private ip |
|:-----------------------------------------------------------|:---------:|:----------:|
| Docker and client on same host                          | Y         | Y          |
| Docker and client on different hosts, same network      | Y         | Y          |
| Docker and client on different hosts, different network | Y         | N/A        |
> fix: Ensure server listing address is used when set in config

- Projects/Server/Buffers/STArrayPool.cs
- Projects/Server/PropertyList/ObjectPropertyList.cs
- Projects/Server/Utilities/Utility.cs
- Fixes double return issue with object property list that is causing corruption.
- Adds DEBUG_ARRAYPOOL define constant which will crash on double return or invalid return scenarios.
> [!IMPORTANT]
> **Developer Notes**
> STArrayPool rented arrays **MUST NOT** be returned **ONLY ONCE** otherwise there will be corruption from double-use.
> Use `DEBUG_ARRAYPOOL` to test potential broken STArrayPool use cases.
> [!NOTE]
> **Why can't I enable the debug all the time?**
> Other than the fact that it will crash due to bad code, the actual tracking system is highly detrimental/problematic for performance and memory consumption by creating objects that have a stack trace.
> fix: Fixes ObjectPropertyList double return issue

- Distribution/Data/Decoration/Felucca/ocllo.cfg
Statics do not have player mobile integrations.
> fix: Fixes Occlo so it uses the actual addon when decorations are generated.

- Projects/Server.Tests/Tests/Timer/TimerTests.cs
- Projects/Server/Timer/Timer.TimerWheel.cs
- Projects/Server/Timer/Timer.cs
Fixes a few minor issues with timers:
- Timer.Delay and Timer.Interval was not reflecting the actual tick time (aligned to the next 8ms)
- Negative delay values were causing a crash when DateTime.Now - delay was below DateTime.MinValue
- Timer.Next now reflects the correct wall clock tick time based on the adjusted Delay.
- Timer.Next is not assigned when the timer is started. This was important for timers that were created, but started later.
> fix: Fixes Timer crash due to negative inputs.

- .config/dotnet-tools.json
- .github/workflows/build-test.yml
- .github/workflows/create-release.yml
- Directory.Build.props
- Projects/Server.Tests/Server.Tests.csproj
- Projects/Server/Client/ArtData.cs
- Projects/Server/Client/UOClient.cs
- Projects/Server/Items/Item.cs
- Projects/Server/Localization/Localization.cs
- Projects/Server/Network/NetState/NetState.cs
- Projects/Server/Serial.cs
- Projects/Server/Server.csproj
- Projects/Server/Text/StringHelpers.cs
- Projects/Server/TileMatrix/TileMatrix.cs
- Projects/Server/TileMatrix/TileMatrixPatch.cs
- Projects/Server/Utilities/HashUtility.cs
- Projects/UOContent.Tests/UOContent.Tests.csproj
- Projects/UOContent/Special Systems/Engines/TestCenter.cs
- Projects/UOContent/UOContent.csproj
- README.md
- azure-pipelines.yml
- docs/starting-server.md
- global.json
- version.json
* Bumps to .NET 9 with updated dependencies
* Comparing a value type against null is no longer allowed
* CI/CD now uses the version specified in global.json
* Serialization generator updated to .NET 9 with bug fixes, fixes to turkish language, and parallelization
> feat: Updates to .NET 9

- Projects/UOContent/Gumps/TithingGump.cs
X coordinate is wrong for 'Tithe:' text, therefore 'Gold:' and 'Tithe:' display overlapping
> fix: Fixes overlapping text in TithingGump

- Projects/UOContent/Items/Guilds/GuildTeleporter.cs
- Adjusted condition to prevent unnecessary "one guildstone per house" restriction when moving the guildstone inside the same house since the guildstone does not disappear after teleporter generation.
Refactors the teleportation logic for improved user experience.
> fix: Allow guildstone movement within the same house

- CONTRIBUTING.md
- version.json
> [!important]
> ModernUO v0.13.x and below is now **dual licensed**, GPLv3, and a personal unrestricted license to @kamronbatman.
> ModernUO v0.14.x and above is **ONLY** GPLv3 and no longer requires a CLA to contribute. All contributors will maintain their copyright, and all contributions will be licensed under GPLv3 per the existing license.
- This doesn't materially affect most contributors.
- For contributors that hesitated or did not want to contribute due to the CLA, now they do not have to worry about the CLA.
> chore(license): Removes CLA

- Projects/UOContent/Engines/Help/HelpEvents.cs
- Projects/UOContent/Engines/Help/PageQueue.cs
- Projects/UOContent/Engines/Help/StuckMenu.cs
It would be much simpler to expose pages to external webhooks such as Discord or Slack without significantly modifying the core codebase if we adopt some simple `event`s for actions taken by players and staff.  Given this addition an ambitious ModernUO developer (probably me) could [create an addon](https://github.com/modernuo/ModernUO/tree/addon-tutorial/Projects/AddonExample) that implements the aforementioned webhook behavior by adding delegates to the events in this PR.
This PR is a suggested approach, it includes the following events:
* `PageEnqueued`
* `PageRemoved`
* `PageHandlerChanged`
* `PageWaiting`
* `StuckMenu`
> feat: events for Help system

- Projects/UOContent/Items/Armor/BaseArmor.cs
- Projects/UOContent/Items/Clothing/BaseClothing.cs
- Projects/UOContent/Items/Quivers/BaseQuiver.cs
- Projects/UOContent/Items/Weapons/BaseWeapon.cs
Fixes issue where exceptionally crafted weapons would lose makers mark after restart.
> fix: Ensure ShouldSerializeCrafter serializes when _crafter is not null or empty

- Projects/UOContent/Items/Containers/Fillable Containers/FillableContainer.cs
Not sure if there is a way to set a default value when using SerializableProperty...
But FillableContentType.None is -1, whilst FillableContentType.Weaponsmith is 0, and AcquireContent doesn't do anything if the ContentType is not .None, therefore all FillableContainer's end up being Weaponsmith
> fix: Fix FillableContainer default WeaponSmith

- Projects/Server/Mobiles/Mobile.cs
- Projects/UOContent/Items/Skill Items/Misc/Bandage.cs
- Projects/UOContent/Misc/Notoriety.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Projects/UOContent/Skills/Stealing.cs
- Projects/UOContent/Spells/Base/Spell.cs
* Adds `As a young player, you may not use beneficial skills on older players.` for healing.
* Adds `You cannot steal from people or monsters right now. Practice on chests and barrels.` for stealing.
* Adds fix to prevent stealing from young players with the message `You cannot steal from the Young.`
* Adds `As a young player, you may not cast beneficial spells onto older players.` for beneficial spells.
* Fixes stealing heavy items error message to `This item is too heavy to steal from someone's backpack.`
* Fixes notoriety issue where young players cannot heal their own horse.
* Fixes notoriety issue where pets bypass beneficial checks in some circumstances.
> feat: Fixes beneficial notoriety checks and adds better young restrictions/messaging

- Projects/UOContent/Engines/BuffIcons/BuffIconPackets.cs
- Projects/UOContent/Mobiles/PlayerMobile.cs
- Fixes the wrong unit sent into the BuffIcons system. Simplified this so the packet takes seconds and the conversion is done on the implementation layer.
> fix: Fixes the wrong unit used for BuffIcon Timers

- Projects/Server/Maps/Map.cs
- Projects/UOContent/Gumps/Houses/HouseGumpAOS.cs
It's an old school RunUO bug that people squirreled away to day 1 balron/boss monsters. Essentially by standing on a door way, the HasLineOfSight() of sight check returns false and the monster just stands there, doing nothing, not even returning melee swings
> fix: Fixes door monster LOS exploit & AOS House Gump NPE

- Projects/Server/Main.cs
- Projects/Server/World/World.cs
* Fixes a race condition where the snapshot path isn't between the request snapshot being set on a background thread, and the main loop consuming that flag.
Closes #2102
> fix: Fixes race condition with world save snapshot request

- Projects/Server/Items/Container.cs
- Projects/Server/Regions/Region.cs
- Projects/Server/Utilities/Utility.cs
- Projects/UOContent/Engines/Spawners/BaseSpawner.cs
- Projects/UOContent/Engines/Spawners/ProximitySpawner.cs
- Projects/UOContent/Engines/Spawners/RegionSpawner.cs
- Projects/UOContent/Engines/Spawners/Spawner.cs
- Projects/UOContent/Gumps/AdminGump.cs
- Projects/UOContent/Items/Misc/FlippableAddonAttribute.cs
- Projects/UOContent/Misc/InhumanSpeech.cs
- Projects/UOContent/Misc/Loot.cs
- Projects/UOContent/Misc/Weather.cs
- Projects/UOContent/Mobiles/AI/HealerAI.cs
- Projects/UOContent/Multis/ComponentVerification.cs
- Projects/UOContent/Regions/BaseRegion.cs
If you don't need to use the array built by `params`, then changing `params T[]` to `params ReadOnlySpan<T>` will hint to the compiler to make a global static array and to not allocate the input as an array.
> feat: Replaces params array with params ReadOnlySpan

- Projects/UOContent/Engines/BuffIcons/BuffInfo.cs
- Projects/UOContent/Gumps/PetResurrectGump.cs
- Projects/UOContent/Gumps/SelectAddonDirectionGump.cs
- Projects/UOContent/Holiday Stuff/Christmas/2004/Mistletoe.cs
- Projects/UOContent/Holiday Stuff/Christmas/2010/Addons/FireFliesDeed.cs
- Projects/UOContent/Items/Deeds/IDirectionAddonDeed.cs
- Projects/UOContent/Items/Special/Broken Furniture Collection/BrokenBed.cs
- Projects/UOContent/Items/Special/Broken Furniture Collection/BrokenVanity.cs
- Projects/UOContent/Items/Special/Gifts/HearthOfHomeFire.cs
- Projects/UOContent/Items/Special/Heritage Items/Curtains.cs
- Projects/UOContent/Items/Special/Heritage Items/HangingAxes.cs
- Projects/UOContent/Items/Special/Heritage Items/HangingSwords.cs
- Projects/UOContent/Items/Special/Heritage Items/HouseLadder.cs
- Projects/UOContent/Items/Special/Heritage Items/Statue.cs
- Projects/UOContent/Items/Special/Heritage Items/UnmadeBed.cs
- Projects/UOContent/Items/Special/Heritage Items/Vanity.cs
- Projects/UOContent/Items/Special/Heritage Items/WoodenCoffin.cs
- Projects/UOContent/Items/Special/Holiday/Wreath.cs
- Projects/UOContent/Items/Special/Veteran Rewards/Banner.cs
- Projects/UOContent/Items/Special/Veteran Rewards/HangingSkeleton.cs
- Projects/UOContent/Mobiles/Monsters/Summons/SummonedAirElemental.cs
- Standardizes East/South addon selection gumps by creating an abstract `SelectAddonDirectionGump` static gump.
> feat: Standardizes South/East selection gumps

- Projects/Server/Network/Packets/OutgoingContainerPackets.cs
- Fixes a regression of displaying spellbooks for Pre-AOS that affects EA clients.
> fix: Fixes empty spellbooks with EA client on Pre-AOS

- Projects/UOContent/Misc/AccountPrompt.cs
- Updates AccountPrompt to use `logger` to avoid console clobbering
> fix: Fixes console clobbering when prompted to add an owner account

- Projects/UOContent/Misc/Notoriety.cs
- Projects/UOContent/Mobiles/AI/BaseAI.cs
- Projects/UOContent/Mobiles/BaseCreature.cs
- Projects/UOContent/Mobiles/Monsters/Misc/Melee/BladeSpirits.cs
- Projects/UOContent/Mobiles/Monsters/Misc/Melee/EnergyVortex.cs
At some point EVs and BSs changed from attacking players (and their caster) to following normal spell casting rules of not attacking blues. We will assume it was at AOS+.
Introduced a new overridable property `BaseCreature.FollowsAcquireRules` to mediate this.
> fix: Fixes EVs/BSs attacking players in Pre-AOS

- Projects/Server/Network/TcpServer.cs
Fixes an issue where CUO was sending multiple packets at once during login for older client versions.
> fix: Fixes CUO connecting with new TCP Peek Filtering

- Projects/UOContent/Misc/Guild.cs
Because the guild they resigned from, would not calculate a new GM if all the members were a low rank, and so when the server next restarted, they would be loaded up as a Guild Leader in whatever clan they joined
> fix: Fixes edge cases where a leader resigns and becomes promoted in their new guild.

- Projects/UOContent/Mobiles/Guards/BaseGuard.cs
- Projects/UOContent/Regions/GuardedRegion.cs
- Fixes infinite teleport from guard refactor for spawners
- Fixes guards not attacking Always Murderer creatures
- Fixes crash when calling guards due to map modification while enumeration
> fix: Fixes guards attacking mobs & crash when calling guards

- Projects/Server/Main.cs
On some operating systems (like hosted Linux VMs), the `TimeStamp.GetTimeStamp()` CPU tick count will wrap around. This is generally not an issue, except for legacy reasons the TickCount is returned in milliseconds instead of ticks. This means when the values wrap around, they are already divided by the CPU Frequency (usually 1million) and then converted to milliseconds. That means the delta between the tick count before and after wrapping is off by a magnitude of (Frequency / 1000).
Example:
TimeStamp A = 9223372036654775807
Some time has passed:
TimeStamp B = -9223372036654775809
The raw delta is 400_000_000 (400ms) when you do `unchecked(A - B)`.
If we do the calculation AFTER converting it to milliseconds, then:
TickCount A = 9223372036654
TickCount B = -9223372036654
The raw delta is …
> fix: Fixes critical bug in TickCount calculation.

- Projects/Server/Buffers/ValueStringBuilder.cs
- Projects/Server/Text/TextEncoding.cs
* Optimized GetString by eliminating the intermediate string allocation.
** Note **: Encoding.GetChars() is still really inefficient, especiall when strings are not aligned or have regular ascii/unicode characters. Thankfully we generally don't have to worry about these odd edge cases, but if they happen then GetChars can allocate hundreds of bytes.
This is a benchmark for just the related changes. NonSpecial are just ascii characters, while the other tests include control codes.
```cs
| Method                         | Mean     | Error   | StdDev  | Gen0   | Allocated |
|------------------------------- |---------:|--------:|--------:|-------:|----------:|
| GetString                      | 306.7 ns | 5.96 ns | 6.86 ns | 0.0124 |     200 B |
| GetStringNotSpecial            | 257.0 ns | …
```
> fix: Optimizes GetString to eliminate allocations

- Projects/UOContent/Spells/Fifth/DispelField.cs
- Projects/UOContent/Spells/Fifth/PoisonField.cs
- Projects/UOContent/Spells/Fourth/FireField.cs
- Projects/UOContent/Spells/Seventh/EnergyField.cs
- Projects/UOContent/Spells/Sixth/ParalyzeField.cs
- Projects/UOContent/Spells/Targeting/ITargetingSpell.cs
- Projects/UOContent/Spells/Third/WallOfStone.cs
Adjusts spell ranges according to OSI. Specifically, the [April 14, 1999 patch](https://uo.com/wiki/ultima-online-wiki/technical/previous-publishes/1999-2/1999-06-14th-april/) changed spell ranges to 10 tiles, and 15 tiles for fields.
> fix: Adjusts spell ranges to match OSI

- Projects/UOContent/Engines/Craft/Core/CraftGump.cs
This has been bothering me for a while:
Been broken forever... I just corrected the offset:
> fix: Fixes craft gump non-cliloc label offsets.

- Projects/UOContent/Items/Weapons/BaseWeapon.cs
Fixes weapons not serializing lesser poison.
> [!NOTE]
> Dev Note: After applying this fix, fix weapons already in-game using the following command
> `[global set poison lesser where baseweapon poison = null poisoncharges > 0`
> fix: Fixes weapons not serializing lesser poison

- Projects/UOContent/Mobiles/Hireables/BaseHire.cs
There was a duplicate 'Open Paperdoll' context menu entry in all hireables, being added in BaseHire:
I've removed it.
> fix: Do not add an extraneous Open Paperdoll context menu entry

- Projects/UOContent/Skills/Begging.cs
- Projects/UOContent/Skills/DetectHidden.cs
- Projects/UOContent/Skills/Stealing.cs
Stealing, Detect Hidden, and Begging will now give credit for the time it took the player to use the targeter against the total skill cooldown. So if the player takes longer than 10s to target, then they can use a skill again immediately.
> [!NOTE]
> This does not change the requirement that players can no longer stack target these skills.
> fix: Fixes skill cooldown for some target skills
